/**
 * Classification of a Recommendation (US098).
 */
export enum RecommendationType {
  REPEAT_EXPERIMENT = 'REPEAT_EXPERIMENT',
  EXPAND_SCOPE = 'EXPAND_SCOPE',
  VERIFY_RESULT = 'VERIFY_RESULT',
  INVESTIGATE_ANOMALY = 'INVESTIGATE_ANOMALY',
  COMPARE_MODELS = 'COMPARE_MODELS',
  COLLECT_MORE_DATA = 'COLLECT_MORE_DATA',
}
