/**
 * W3-O05-a — Monitoring & Security Health Inventory & Honest Baseline.
 *
 * Discovery and classification only.
 * Not monitoring implementation. Not health evaluation. Not alerting.
 * Not dashboards. Not persistence. Not restart recovery. Not operational continuity.
 * Not Monitoring Complete. Not W3-O05 CLOSED.
 *
 * Capability labels MN-02 / MN-03 / SEC-13 / SEC-15 are inventory vocabulary only —
 * not authorization to invent a second monitoring platform or incident system.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate target on existing Security Platform / Audit / Continuity owners.
 * - EPHEMERAL: artifact is transient, computed, stub, UI-only, process-local,
 *   or missing — must not be treated as durable monitoring truth on paper.
 */

export const W3_O05_A_SLICE_ID = 'W3-O05-a' as const;

export const W3_O05_A_ALLOWED_OWNERS = Object.freeze([
  'security-platform',
  'security-audit',
  'operational-continuity',
  'connection-management',
  'notification-delivery',
  'trading-session',
  'runtime-platform',
  'command-center',
  'release-governance',
  'wave-3-documentation',
  'authentication',
  'authorization',
  'workspace-isolation',
  'live-trading-deferred',
  'wave-5-deferred',
  'wave-6-deferred',
  'wave-7-deferred',
  'market-data-deferred',
  'qualification-deferred',
  'continuity-products-deferred',
  'analytical-stores',
  'notification-queue',
  'recovery-residual',
  'kill-switch-deferred',
] as const);

export type W3O05AOwner = (typeof W3_O05_A_ALLOWED_OWNERS)[number];

/** Existing monitoring substrate owners — no new owner. */
export const W3_O05_A_SUBSTRATE_OWNERS = Object.freeze([
  'security-platform',
  'security-audit',
  'operational-continuity',
  'connection-management',
] as const);

export const W3_O05_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W3O05AArtifactKind = (typeof W3_O05_A_ARTIFACT_KINDS)[number];

export const W3_O05_A_REQUIRED_ARTIFACT_KINDS = W3_O05_A_ARTIFACT_KINDS;

export const W3_O05_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W3O05ADurabilityClass = (typeof W3_O05_A_DURABILITY_CLASSES)[number];

export const W3_O05_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W3O05ADependencyDirection = (typeof W3_O05_A_DEPENDENCY_DIRECTIONS)[number];

export const W3_O05_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W3-O05-b',
  'W3-O05-c',
  'W3-O05-d',
  'W3-O05-e',
  'honesty-baseline',
  'out-of-scope-w3-o01',
  'out-of-scope-w3-o02',
  'out-of-scope-w3-o03',
  'out-of-scope-w3-o04',
  'out-of-scope-live-trading',
  'out-of-scope-bc-ha-dr',
  'out-of-scope-wave-5',
  'out-of-scope-wave-6',
  'out-of-scope-wave-7',
  'out-of-scope-second-monitoring-platform',
  'out-of-scope-second-incident-system',
  'out-of-scope-domain-health',
] as const);

export type W3O05AFutureResponsibility = (typeof W3_O05_A_FUTURE_RESPONSIBILITIES)[number];

export type W3O05AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W3O05AArtifactKind;
  owner: W3O05AOwner;
  durabilityClass: W3O05ADurabilityClass;
  dependencyDirection?: W3O05ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW3O05Responsibility: W3O05AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  isPaperProduct: boolean;
  authorizesMonitoringComplete: boolean;
}>;

/**
 * Frozen inventory of monitoring, security health, runtime health, operational
 * health, projections, dependencies, ownership, honesty-boundary, and explicit OUT.
 */
export const W3_O05_A_MONITORING_INVENTORY: readonly W3O05AInventoryRow[] = Object.freeze([
  // ── Commands (health read surfaces) ─────────────────────────────────────
  Object.freeze({
    artifactId: 'cmd-get-runtime-health',
    artifact: 'GET /health — unversioned runtime health probe (MN-01)',
    kind: 'command' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Implemented — returns computed RuntimeHealthReport per request',
    honestyRequirement:
      'Process health probe ≠ Monitoring Complete; ≠ operator security health dashboard',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/health/runtime-health.controller.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-get-operational-readiness',
    artifact: 'GET /v1/operational-continuity/readiness — Platform Readiness (workspace-scoped)',
    kind: 'command' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Implemented — post-restart continuity projection; not ongoing monitoring',
    honestyRequirement: 'Platform Readiness ≠ Monitoring Complete; honest degraded/unavailable',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath:
      'apps/api/src/modules/operational-continuity/operational-continuity.controller.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-get-prometheus-metrics',
    artifact: 'GET /v1/metrics — Prometheus scrape endpoint (US112)',
    kind: 'command' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Implemented — public scrape; in-process metrics driver',
    honestyRequirement: 'Prometheus scrape ≠ MN-02 Observability product Complete',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'apps/api/src/metrics/metrics.controller.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-get-security-audit-timeline',
    artifact: 'GET /v1/security-audit/workspaces/:id/timeline — RoleAdmin audit navigation',
    kind: 'command' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Implemented — reads durable audit store; no operator web UI today',
    honestyRequirement: 'Audit timeline API ≠ SEC-15 Security Health dashboard Complete',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/security-audit/security-audit-timeline.controller.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-get-live-health',
    artifact: 'GET /v1/live/health — live workspace health (Wave 6)',
    kind: 'command' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Implemented — live-only; hidden from paper product routes',
    honestyRequirement: 'Live health ≠ paper Monitoring Complete; out of O05 paper scope',
    futureW3O05Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading.controller.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesMonitoringComplete: false,
  }),

  // ── State ───────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'state-security-audit-records',
    artifact: 'SecurityAuditRecord durable store — authoritative audit trail',
    kind: 'state' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — Prisma security_audit_records; survives restart',
    honestyRequirement: 'Audit store is SoT for security events; not a second incident platform',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/security-audit/prisma-security-audit.repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-security-incident-records',
    artifact: 'SecurityAuditIncident durable store — investigation lifecycle',
    kind: 'state' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — Prisma security_audit_incidents; internal API today',
    honestyRequirement: 'Incident store ≠ Incident Management product Complete; consume only',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath:
      'apps/api/src/modules/security-audit/prisma-security-audit-incident.repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-queue-continuity-status',
    artifact: 'NotificationQueueContinuityStatus — post-restart queue recovery record',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — W3-O02-c recovery substrate; consumed by readiness projection',
    honestyRequirement: 'Queue continuity state ≠ MN-03 alerting product Complete',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-queue-continuity-status.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-kill-switch-continuity-status',
    artifact: 'KillSwitchContinuityStatus — post-restart Kill Switch recovery record',
    kind: 'state' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — W3-O04-c recovery substrate; consumed by readiness projection',
    honestyRequirement: 'Kill Switch continuity ≠ Monitoring Complete; O04 foundation only',
    futureW3O05Responsibility: 'out-of-scope-w3-o04' as const,
    evidencePath: 'apps/api/src/modules/trading-session/domain/kill-switch-continuity-status.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-analytical-owner-continuity',
    artifact: 'AnalyticalOwnerContinuityStatus — boot outcome registry (W3-O01-d)',
    kind: 'state' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — analytical owner boot outcomes; Platform Readiness input',
    honestyRequirement: 'Analytical continuity ≠ monitoring health product Complete',
    futureW3O05Responsibility: 'out-of-scope-w3-o01' as const,
    evidencePath: 'apps/api/src/persistence/analytical-owner-continuity-status.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-runtime-health-report',
    artifact: 'RuntimeHealthReport — computed per-request health aggregation',
    kind: 'state' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Transient — recomputed each GET /health; not persisted',
    honestyRequirement: 'Runtime report lost on restart semantics irrelevant; probe is ephemeral',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/health/runtime-health-report.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-prometheus-instruments',
    artifact: 'In-process Prometheus metric instruments (HTTP interceptor, live-market)',
    kind: 'state' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Process-local counters/histograms — reset on API restart',
    honestyRequirement:
      'In-memory metrics ≠ durable observability product; honest reset on restart',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'apps/api/src/metrics/instrument-repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-security-health-dashboard',
    artifact: 'SEC-15 Security Health dashboard durable state / projection',
    kind: 'state' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — 0% product readiness; no operator security health dashboard',
    honestyRequirement: 'Missing state must not be faked green; W3-O05-b…e required',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Projections ─────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'proj-exchange-session-health',
    artifact: 'ExchangeHealthProjection on ExchangeSessionView — connection health',
    kind: 'projection' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Computed from session state — HEALTHY/UNAVAILABLE/EXPIRED/etc.',
    honestyRequirement: 'Connection health projection ≠ unified monitoring dashboard Complete',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-session.health.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-notification-queue-continuity',
    artifact: 'NotificationQueueContinuityView — queue health on Platform Readiness',
    kind: 'projection' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Computed at bootstrap from durable continuity status + live queue counts',
    honestyRequirement: 'Queue projection on readiness page ≠ MN-03 alerting Complete',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-queue-operational-continuity.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-kill-switch-continuity',
    artifact: 'KillSwitchContinuityView — Kill Switch health on Platform Readiness',
    kind: 'projection' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Computed at bootstrap from durable continuity status + armed counts',
    honestyRequirement: 'Kill Switch continuity projection ≠ Monitoring Complete',
    futureW3O05Responsibility: 'out-of-scope-w3-o04' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/domain/kill-switch-operational-continuity.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-platform-operational',
    artifact: 'PlatformOperationalProjection — aggregated readiness evaluation',
    kind: 'projection' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Computed after bootstrap — Ready/Degraded/Unavailable per owner',
    honestyRequirement: 'Platform Readiness projection ≠ ongoing Monitoring product Complete',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-live-health-alerts',
    artifact: 'LiveHealthReport alerts including kill_switch_active',
    kind: 'projection' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Live-only health alerts — not paper monitoring product',
    honestyRequirement: 'Live health alert ≠ SEC-13/SEC-15 Complete on paper',
    futureW3O05Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/health-monitor.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-unified-monitoring-dashboard',
    artifact: 'Unified operator monitoring / security health dashboard projection',
    kind: 'projection' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no unified connection/security/incident dashboard on paper',
    honestyRequirement: 'Missing projection must not be implied Complete from readiness page alone',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Runtime ─────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'runtime-health-service',
    artifact: 'RuntimeHealthService — aggregates API/DB/migration/version checks',
    kind: 'runtime' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'In-process health evaluation — no durable monitoring store',
    honestyRequirement: 'Runtime evaluation ≠ monitoring persistence; restart recomputes',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/health/runtime-health.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-startup-verification',
    artifact: 'Startup verification — RC-01 fail-closed bootstrap health gate',
    kind: 'runtime' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Code/config gate — prevents unhealthy startup in production',
    honestyRequirement: 'Startup gate ≠ operator monitoring dashboard; process-level only',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/health/startup-verification.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-security-platform-bootstrap',
    artifact: 'SecurityPlatformBootstrap — security config verification at startup',
    kind: 'runtime' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Wave 1 substrate — verifies security configuration validity',
    honestyRequirement: 'Security bootstrap ≠ SEC-13 monitoring product Complete',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'apps/api/src/security-platform/security-platform.bootstrap.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-platform-abuse-protection',
    artifact: 'PlatformAbuseProtection — rate limiting / abuse detection substrate',
    kind: 'runtime' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'In-process counters — SEC-13 substrate; not operator dashboard',
    honestyRequirement: 'Abuse protection runtime ≠ security monitoring product Complete',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'apps/api/src/security-platform/platform-abuse-protection.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-operational-continuity-service',
    artifact: 'OperationalContinuityService — builds Platform Readiness after bootstrap',
    kind: 'runtime' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Bootstrap-time evaluation — not continuous monitoring loop',
    honestyRequirement: 'Continuity service ≠ MN-02/MN-03 monitoring product Complete',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-security-audit-emitter',
    artifact: 'SecurityAuditEmitter — emits security events to durable audit store',
    kind: 'runtime' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persists audit records — consumed by timeline/incident services',
    honestyRequirement: 'Audit emitter ≠ SOC/SIEM; single authoritative audit owner',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/security-audit/security-audit-emitter.adapter.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-metrics-http-interceptor',
    artifact: 'MetricsHttpInterceptor — HTTP request instrumentation for Prometheus',
    kind: 'runtime' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'In-process instrumentation — metrics reset on restart',
    honestyRequirement: 'HTTP metrics ≠ MN-02 observability product Complete',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'apps/api/src/metrics/metrics-http.interceptor.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Operational ─────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'op-mn01-capability-inventory',
    artifact: 'MN-01 Health endpoints capability — 75% readiness in inventory',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Named — GET /health exists; not productized as operator monitoring',
    honestyRequirement: 'MN-01 partial ≠ Monitoring Complete',
    futureW3O05Responsibility: 'W3-O05-e' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-mn02-mn03-sec-capabilities',
    artifact: 'MN-02/MN-03/SEC-13/SEC-15 capability inventory entries',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Named — low/zero product readiness; W3-O05 productization target',
    honestyRequirement: 'Capability labels ≠ Complete until O05 package Close',
    futureW3O05Responsibility: 'W3-O05-e' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-operational-state-matrix',
    artifact: 'Operational State Matrix — owner readiness documentation',
    kind: 'operational' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Documented — explicitly NOT monitoring/incidents product',
    honestyRequirement: 'State matrix ≠ Monitoring Complete; continuity reference only',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/operational-state-matrix.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-w3-o05-planning-package',
    artifact: 'W3-O05 Planning Package — APPROVED; slices b–e not opened',
    kind: 'operational' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Planning APPROVED — W3-O05-a inventory slice in progress',
    honestyRequirement: 'Planning Approval ≠ Monitoring Complete',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-planning-approval.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Operator-visible ────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ui-operational-continuity-page',
    artifact: 'OperationalContinuityPage — Platform readiness UI (/operational-continuity)',
    kind: 'operator-visible' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Routed in paper product — queue + Kill Switch sections visible',
    honestyRequirement: 'Readiness page ≠ Monitoring Complete; honest degraded/unavailable only',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'apps/web/src/operational-continuity/OperationalContinuityPage.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-web-runtime-health-client',
    artifact: 'Web getRuntimeHealth client — unversioned /health consumer',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Client exists — not surfaced as operator monitoring dashboard',
    honestyRequirement: 'Health client without dashboard ≠ MN-02 Complete',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/web/src/shared/api.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-security-health-dashboard',
    artifact: 'SEC-15 Security Health dashboard operator UI',
    kind: 'operator-visible' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no operator security health dashboard on paper',
    honestyRequirement: 'Missing UI must not be faked; honest non-delivery until W3-O05-c',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-security-incident-visibility',
    artifact: 'Operator recent incidents visibility UI (without SSH)',
    kind: 'operator-visible' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — audit timeline API exists; no operator web surface',
    honestyRequirement: 'API without UI ≠ incident visibility Complete',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-connection-health-dashboard',
    artifact: 'Unified connection health operator dashboard',
    kind: 'operator-visible' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — health embedded in connections API only',
    honestyRequirement: 'Connections API health field ≠ monitoring dashboard Complete',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/connections/connections.service.ts',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Persistence candidates ──────────────────────────────────────────────
  Object.freeze({
    artifactId: 'persist-monitoring-health-state',
    artifact: 'Durable monitoring / security health state on existing owners',
    kind: 'persistence-candidate' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus:
      'Implemented — WorkspaceMonitoringHealthState (W3-O05-b) with restart hydrate (W3-O05-c) and operational continuity (W3-O05-d)',
    honestyRequirement:
      'Persistence + recovery + continuity substrate only; no second store; monitoring evaluation is post-O05',
    futureW3O05Responsibility: 'W3-O05-e' as const,
    evidencePath:
      'apps/api/src/security-platform/monitoring-health/persistence/prisma-monitoring-health-state.repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'persist-security-audit-store',
    artifact: 'security_audit_records — existing durable audit persistence',
    kind: 'persistence-candidate' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — authoritative audit SoT; consumed not duplicated',
    honestyRequirement: 'Existing audit store ≠ second incident system',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/security-audit/security-audit-persist.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Ephemeral artifacts ─────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'eph-health-status-derivation',
    artifact: 'deriveOverallHealthStatus — in-memory health status aggregation',
    kind: 'ephemeral-artifact' as const,
    owner: 'runtime-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Pure function — no persistence; recomputed per probe',
    honestyRequirement: 'Derived status must not be cached as durable monitoring truth',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/health/health-status.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'eph-platform-readiness-bootstrap-cache',
    artifact: 'In-memory PlatformOperationalProjection after bootstrap',
    kind: 'ephemeral-artifact' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Held in service memory — rebuilt each API restart from durable inputs',
    honestyRequirement: 'Bootstrap cache ≠ ongoing monitoring; restart rebuild required',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Dependencies ────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'dep-consumes-authentication',
    artifact: 'Authentication — signed-in operator for health/incident surfaces',
    kind: 'dependency' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — fail closed when missing',
    honestyRequirement: 'Reuse Wave 1 Authentication; no new security owner',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authorization',
    artifact: 'Authorization — RoleAdmin for audit timeline; workspace-scoped health',
    kind: 'dependency' as const,
    owner: 'authorization' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — audit timeline RoleAdmin; readiness workspace-scoped',
    honestyRequirement: 'Health/incident access requires authorization; no bypass',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-workspace-isolation',
    artifact: 'Workspace Isolation — health/incidents scoped per workspace',
    kind: 'dependency' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — cross-workspace deny required at Close',
    honestyRequirement: 'Foreign workspace must not read health or incidents',
    futureW3O05Responsibility: 'W3-O05-e' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-health-projections',
    artifact: 'Connection/queue/Kill Switch health projections for monitoring consume',
    kind: 'dependency' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'produces' as const,
    currentStatus: 'Produced at bootstrap — monitoring product must consume not duplicate',
    honestyRequirement: 'Produced projections are inputs; not second monitoring platform',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-security-audit-events',
    artifact: 'Security audit events — produced to durable audit store',
    kind: 'dependency' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'produces' as const,
    currentStatus: 'Produced — continuity, auth, and platform events persisted',
    honestyRequirement: 'Audit events are incident visibility inputs; not SOC product',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity-audit.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-w3-o01-o04-continuity',
    artifact: 'W3-O01-d / O02-d / O04-d operational continuity substrates',
    kind: 'dependency' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'CLOSED predecessors — consumed as Platform Readiness inputs',
    honestyRequirement: 'Continuity substrates ≠ Monitoring Complete alone',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'docs/project/version-3/wave-3/operational-state-matrix.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-observed-by-platform-readiness-ui',
    artifact: 'Platform Readiness UI observes queue + Kill Switch continuity projections',
    kind: 'dependency' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'observed-by' as const,
    currentStatus: 'OperationalContinuityPage renders continuity — not full monitoring',
    honestyRequirement: 'Readiness observer ≠ Monitoring Complete claim',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/web/src/operational-continuity/OperationalContinuityView.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-missing-security-dashboard',
    artifact: 'Missing SEC-15 security health dashboard blocks Monitoring Complete',
    kind: 'dependency' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active blocker — 0% SEC-15 readiness',
    honestyRequirement: 'Must not claim Security Health Complete without dashboard',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-missing-incident-ui',
    artifact: 'Missing operator incident UI blocks incident visibility Complete',
    kind: 'dependency' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active blocker — timeline API only; no web surface',
    honestyRequirement: 'Internal API ≠ operator incident visibility without SSH',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Ownership surfaces ──────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'own-security-platform-substrate',
    artifact: 'Security Platform — config, bootstrap, abuse protection substrate',
    kind: 'ownership' as const,
    owner: 'security-platform' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — SEC-13 extends; no ownership movement',
    honestyRequirement: 'Security Health extends Security Platform; does not replace owner',
    futureW3O05Responsibility: 'W3-O05-b' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-security-audit-incident',
    artifact: 'Security Audit / Incident — authoritative audit and incident store',
    kind: 'ownership' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — consume only; no second incident system',
    honestyRequirement: 'Incident visibility consumes audit/incident; no duplicate persistence',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-operational-continuity',
    artifact: 'Operational Continuity — Platform Readiness evaluation owner',
    kind: 'ownership' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — readiness ≠ monitoring platform',
    honestyRequirement: 'Continuity owner projects health inputs; not second monitoring owner',
    futureW3O05Responsibility: 'W3-O05-d' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-connection-management-health',
    artifact: 'Connection Management — exchange session health projection owner',
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — Wave 2 CM-04 substrate',
    honestyRequirement: 'Connection health owned by Connection Management; monitoring consumes',
    futureW3O05Responsibility: 'W3-O05-c' as const,
    evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-session.health.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Honesty boundaries ──────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'honesty-monitoring-not-platform',
    artifact: 'Monitoring ≠ Monitoring Platform',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding honesty boundary — frozen in inventory',
    honestyRequirement: 'No second monitoring platform or incident system authorized',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/monitoring-security-health-overview.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-observability-platform',
    artifact: 'Monitoring ≠ Observability Platform',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — Prometheus scrape ≠ MN-02 product Complete',
    honestyRequirement: 'Metrics endpoint alone does not Close observability product',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-siem-soc',
    artifact: 'Monitoring ≠ SIEM; Monitoring ≠ SOC',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — audit store ≠ SOC/SIEM product claims',
    honestyRequirement: 'Security audit consumption ≠ security operations center',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-incident-management',
    artifact: 'Monitoring ≠ Incident Management',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — incident visibility ≠ full incident management product',
    honestyRequirement: 'Recent incidents view ≠ workflow/triage/escalation platform',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-bc-ha-dr',
    artifact: 'Monitoring ≠ Business Continuity / HA / Disaster Recovery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — health visibility ≠ continuity products',
    honestyRequirement: 'Operational health ≠ BC/HA/DR drills or failover orchestration',
    futureW3O05Responsibility: 'out-of-scope-bc-ha-dr' as const,
    evidencePath: 'docs/project/version-3/wave-3/monitoring-security-health-overview.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-live-trading',
    artifact: 'Monitoring ≠ Live Trading (Wave 6)',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — paper monitoring ≠ live capital path enablement',
    honestyRequirement: 'O05 Close does not enable Live Trading',
    futureW3O05Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-monitoring-not-wave3-complete',
    artifact: 'Monitoring ≠ Wave 3 COMPLETE',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — O05 alone does not close Wave 3',
    honestyRequirement: 'Wave 3 requires O01–O05 Closed + PO declaration',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/wave-3-progress.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-security-health-not-security-platform',
    artifact: 'Security Health ≠ Security Platform (owner replacement)',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — SEC-15 extends Security Platform substrate',
    honestyRequirement: 'Security Health dashboard extends; does not replace platform owner',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-security-health-not-secops',
    artifact: 'Security Health ≠ Security Operations',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — posture dashboard ≠ SecOps runbook platform',
    honestyRequirement: 'Operator posture view ≠ 24/7 security operations product',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-readiness-not-monitoring',
    artifact: 'Platform Readiness (O01-d/O02-d/O04-d) ≠ Monitoring Complete',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — post-restart continuity ≠ ongoing monitoring product',
    honestyRequirement: 'Readiness page is input substrate; not O05 Close alone',
    futureW3O05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/operational-state-matrix.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),

  // ── Explicit OUT ────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'out-second-monitoring-platform',
    artifact: 'Second monitoring platform / observability stack',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — architecture invariant',
    honestyRequirement: 'W3-O05 extends existing owners only',
    futureW3O05Responsibility: 'out-of-scope-second-monitoring-platform' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-second-incident-system',
    artifact: 'Second incident system / duplicate audit persistence owner',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — consume Security Audit only',
    honestyRequirement: 'No parallel Lake/Outbox for incidents',
    futureW3O05Responsibility: 'out-of-scope-second-incident-system' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading / Wave 6 live capital enablement',
    kind: 'explicit-out' as const,
    owner: 'wave-6-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W3-O05 paper scope — live health catalogued as deferred',
    honestyRequirement: 'O05 paper monitoring ≠ Live Trading enabled',
    futureW3O05Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: false,
    isPaperProduct: false,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-bc-ha-dr-products',
    artifact: 'Business Continuity / High Availability / Disaster Recovery products',
    kind: 'explicit-out' as const,
    owner: 'continuity-products-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W3-O05',
    honestyRequirement: 'Health visibility ≠ BC/HA/DR product claims',
    futureW3O05Responsibility: 'out-of-scope-bc-ha-dr' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-domain-market-health',
    artifact: 'Market / qualification domain health (not operational monitoring)',
    kind: 'explicit-out' as const,
    owner: 'market-data-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Adjacent — GET /v1/market/health is domain health not O05 product',
    honestyRequirement: 'Domain provider health ≠ operator monitoring dashboard',
    futureW3O05Responsibility: 'out-of-scope-domain-health' as const,
    evidencePath: 'apps/api/src/modules/market-data-domain/market-data-domain.controller.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
  Object.freeze({
    artifactId: 'adjacent-w3-o04-kill-switch-foundation',
    artifact: 'W3-O04 Kill Switch foundation (CLOSED predecessor — continuity input only)',
    kind: 'explicit-out' as const,
    owner: 'kill-switch-deferred' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'CLOSED — Kill Switch continuity consumed; not redesigned',
    honestyRequirement: 'O04 foundation ≠ Monitoring Complete; admission block not claimed',
    futureW3O05Responsibility: 'out-of-scope-w3-o04' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-package-summary.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesMonitoringComplete: false,
  }),
]);

export const W3_O05_A_BINDING_FINDINGS = Object.freeze({
  monitoringCompleteAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  monitoringSurvivesRestartAfterSliceA: false,
  securityHealthDashboardExists: false,
  operatorIncidentUiExists: false,
  unifiedConnectionHealthDashboardExists: false,
  platformReadinessUiExists: true,
  runtimeHealthEndpointExists: true,
  prometheusMetricsExists: true,
  securityAuditStoreSurvivesRestart: true,
  inactiveMonitoringPersistence: false,
  platformReadinessNotMonitoringComplete: true,
} as const);

export const W3_O05_A_EXPLICIT_OUT = Object.freeze([
  'second-monitoring-platform',
  'second-incident-system',
  'new-persistence-owner',
  'new-bounded-context',
  'new-source-of-truth',
  'live-trading-enablement',
  'business-continuity',
  'high-availability',
  'disaster-recovery-product',
  'w3-o05-b',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'monitoring-implementation',
  'alerting-implementation',
  'dashboard-implementation',
] as const);

export const W3_O05_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  newMonitoringPlatform: false,
  newIncidentSystem: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  w3O01Redesigned: false,
  w3O02Redesigned: false,
  w3O03Redesigned: false,
  w3O04Redesigned: false,
  monitoringCompleteClaimed: false,
  securityHealthCompleteClaimed: false,
  liveTradingClaimed: false,
  wave3CompleteClaimed: false,
  businessContinuityClaimed: false,
  highAvailabilityClaimed: false,
  disasterRecoveryClaimed: false,
  customerVisibleFeature: false,
  monitoringSurvivesRestart: false,
} as const);

export function artifactIds(): readonly string[] {
  return W3_O05_A_MONITORING_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W3O05AArtifactKind): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsDependencies(
  direction: W3O05ADependencyDirection,
): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter(
    (row) => row.kind === 'dependency' && row.dependencyDirection === direction,
  );
}

export function rowsPaperProduct(): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.isPaperProduct);
}

export function rowsExplicitOut(): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsHonestyBoundaries(): readonly W3O05AInventoryRow[] {
  return W3_O05_A_MONITORING_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsMonitoringSurvive(): readonly W3O05AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    [
      'runtime-platform',
      'connection-management',
      'notification-delivery',
      'operational-continuity',
      'trading-session',
      'command-center',
    ].includes(row.owner),
  );
}

export function rowsMonitoringEphemeral(): readonly W3O05AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    [
      'runtime-platform',
      'connection-management',
      'notification-delivery',
      'operational-continuity',
      'trading-session',
      'command-center',
      'live-trading-deferred',
    ].includes(row.owner),
  );
}

export function rowsSecurityHealthSurvive(): readonly W3O05AInventoryRow[] {
  return rowsSurvive().filter(
    (row) => row.owner === 'security-platform' || row.owner === 'security-audit',
  );
}

export function rowsSecurityHealthEphemeral(): readonly W3O05AInventoryRow[] {
  return rowsEphemeral().filter(
    (row) => row.owner === 'security-platform' || row.owner === 'security-audit',
  );
}
