/**
 * W3-O04-a — Kill Switch Inventory & Honest Control Baseline.
 *
 * Discovery and classification only.
 * Not persistence. Not restart recovery. Not operational continuity.
 * Not runtime behaviour changes. Not Kill Switch product Close.
 *
 * Residual vocabulary LT-03 / TD-047 is debt / capability label only —
 * not a new Source of Truth and not authorization to invent a second Kill Switch.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate target on existing Session / Command Center ownership.
 * - EPHEMERAL: artifact is transient, stub, UI-only, or process-local and
 *   must not be treated as durable Kill Switch truth on paper.
 */

export const W3_O04_A_SLICE_ID = 'W3-O04-a' as const;

export const W3_O04_A_ALLOWED_OWNERS = Object.freeze([
  'trading-session',
  'command-center',
  'live-trading-engine',
  'bot-facade',
  'notification-delivery',
  'release-governance',
  'wave-3-documentation',
  'authentication',
  'authorization',
  'workspace-isolation',
  'order-engine',
  'position-engine',
  'risk-engine',
  'analytical-stores',
  'notification-queue',
  'recovery-residual',
  'monitoring-deferred',
  'live-trading-deferred',
  'continuity-products-deferred',
] as const);

export type W3O04AOwner = (typeof W3_O04_A_ALLOWED_OWNERS)[number];

/** Existing Kill Switch substrate owners — no new owner. */
export const W3_O04_A_SUBSTRATE_OWNERS = Object.freeze([
  'trading-session',
  'command-center',
  'live-trading-engine',
] as const);

export const W3_O04_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W3O04AArtifactKind = (typeof W3_O04_A_ARTIFACT_KINDS)[number];

export const W3_O04_A_REQUIRED_ARTIFACT_KINDS = W3_O04_A_ARTIFACT_KINDS;

export const W3_O04_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W3O04ADurabilityClass = (typeof W3_O04_A_DURABILITY_CLASSES)[number];

export const W3_O04_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'blocked-by',
] as const);

export type W3O04ADependencyDirection = (typeof W3_O04_A_DEPENDENCY_DIRECTIONS)[number];

export const W3_O04_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W3-O04-b',
  'W3-O04-c',
  'W3-O04-d',
  'W3-O04-e',
  'honesty-baseline',
  'out-of-scope-w3-o01',
  'out-of-scope-w3-o02',
  'out-of-scope-w3-o03',
  'out-of-scope-w3-o05',
  'out-of-scope-live-trading',
  'out-of-scope-bc-ha-dr',
  'out-of-scope-monitoring',
  'out-of-scope-second-engine',
] as const);

export type W3O04AFutureResponsibility = (typeof W3_O04_A_FUTURE_RESPONSIBILITIES)[number];

export type W3O04AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W3O04AArtifactKind;
  owner: W3O04AOwner;
  durabilityClass: W3O04ADurabilityClass;
  dependencyDirection?: W3O04ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW3O04Responsibility: W3O04AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  isPaperProduct: boolean;
  authorizesKillSwitchComplete: boolean;
}>;

/**
 * Frozen inventory of Kill Switch commands, state, projections, runtime,
 * operational, operator-visible, persistence-candidate, ephemeral, dependency,
 * ownership, honesty-boundary, and explicit OUT surfaces.
 */
export const W3_O04_A_KILL_SWITCH_INVENTORY: readonly W3O04AInventoryRow[] = Object.freeze([
  // ── Commands ───────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'cmd-activate-kill-switch-live',
    artifact: 'POST /v1/live/kill-switch — activate Kill Switch (live session)',
    kind: 'command' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Implemented — live-only; hidden from paper product (TD-047)',
    honestyRequirement:
      'Live REST alone does not mean Kill Switch Complete on paper; requires visible product arm (W3-O04-c)',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading.controller.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-clear-kill-switch-live',
    artifact: 'POST /v1/live/kill-switch/clear — clear Kill Switch (live session)',
    kind: 'command' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus:
      'Implemented — live-only; PermissionClass.LiveCommand (C7) denied for all roles today',
    honestyRequirement: 'Clear requires authorization; live-only path is not paper product Close',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading.controller.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-emergency-stop-paper',
    artifact: 'Command Center emergency-stop action (paper product surface)',
    kind: 'command' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'UI model only — availability unavailable; no backend port wired',
    honestyRequirement: 'UI-only kill is forbidden; must not emulate arm without durable port',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/command-center/emergency-controls.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-clear-kill-switch-paper',
    artifact: 'Command Center clear-kill-switch action (paper product surface)',
    kind: 'command' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'UI model only — availability unavailable; auto-clear forbidden',
    honestyRequirement: 'Clear must be explicit authorized action; no UI-only clear',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/command-center/emergency-controls.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── State ──────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'state-live-trading-frozen',
    artifact: 'LiveSession.tradingFrozen / live_trading_sessions.trading_frozen',
    kind: 'state' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted per live session — survives API restart for live sessions only',
    honestyRequirement:
      'Live SURVIVE ≠ paper Kill Switch Complete; paper has no equivalent field today',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'apps/api/prisma/schema.prisma',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-paper-kill-switch-armed',
    artifact: 'Paper workspace Kill Switch armed state on Session / Command Center owner',
    kind: 'state' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted — workspace_kill_switch_states (W3-O04-b); restart hydrate deferred',
    honestyRequirement:
      'Durable storage ≠ restart recovery or Kill Switch Complete; W3-O04-c/d required',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/persistence/prisma-kill-switch-state.repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-kill-switch-result-dto',
    artifact: 'KillSwitchResult response DTO (activate command result)',
    kind: 'state' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Transient command response — not durable SoT',
    honestyRequirement:
      'Response DTO is not armed-state truth; tradingFrozen column is SoT for live',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-inactive-recovery-policy',
    artifact: 'InactiveRecoveryEventAdmissionPolicy — always returns inactive',
    kind: 'state' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Production binding stub — isKillSwitchActive() always false',
    honestyRequirement:
      'Admission hooks exist but policy stub means paper never blocks on Kill Switch today',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/ports/recovery-event-admission-policy.port.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-recovery-risk-snapshot-kill-switch',
    artifact: 'RecoveryRiskSnapshot.killSwitchActive (read-only risk port input)',
    kind: 'state' as const,
    owner: 'risk-engine' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus:
      'Optional Stage 3 field — null means unavailable; Risk Engine does not own Kill Switch',
    honestyRequirement: 'Risk read-only context only; not Kill Switch SoT; null ≠ cleared',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'apps/api/src/modules/trading-session/ports/recovery-reconciliation.ports.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Projections ────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'proj-live-session-view-trading-frozen',
    artifact: 'LiveSessionView.tradingFrozen — live REST projection',
    kind: 'projection' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exposed via live trading REST — not paper Command Center',
    honestyRequirement: 'Live projection visibility ≠ paper operator Kill Switch product',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading.service.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-live-health-kill-switch-alert',
    artifact: 'LiveHealthReport alert type kill_switch_active',
    kind: 'projection' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus:
      'Live health endpoint alert when session.tradingFrozen — not Monitoring product (O05)',
    honestyRequirement: 'Health alert ≠ Monitoring Complete; ≠ paper Kill Switch visibility',
    futureW3O04Responsibility: 'out-of-scope-monitoring' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/health-monitor.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-live-sync-log-kill-switch',
    artifact: 'SynchronizationLog kind KILL_SWITCH — live operational audit projection',
    kind: 'projection' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted in live_trading_synchronization_logs',
    honestyRequirement: 'Operational audit for live; not paper Kill Switch Close evidence alone',
    futureW3O04Responsibility: 'W3-O04-e' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-live-events-kill-switch',
    artifact: 'KillSwitchActivated / TradingFrozen / KillSwitchCleared live events',
    kind: 'projection' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Persisted via LiveEventPublisher → live_trading_events',
    honestyRequirement: 'Immutable live event log; paper product has no equivalent today',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading-events.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-command-center-no-kill-switch',
    artifact: 'CommandCenterSessionView — explicitly excludes killSwitch property',
    kind: 'projection' as const,
    owner: 'bot-facade' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Facade contract excludes Kill Switch field — paper gap by design today',
    honestyRequirement:
      'Absence of killSwitch on facade ≠ Kill Switch cleared; means not productized',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/bot-facade/command-center-session.view.spec.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'proj-operator-dashboard-no-kill-switch',
    artifact: 'OperatorDashboardView — explicitly excludes killSwitch property',
    kind: 'projection' as const,
    owner: 'bot-facade' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Facade contract excludes Kill Switch — no operator dashboard halt state',
    honestyRequirement: 'Dashboard absence is honest non-claim; not silent armed state',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/product-flow/operator-dashboard.view.spec.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Runtime ────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'runtime-emergency-manager',
    artifact: 'EmergencyManager — exchange-independent Kill Switch orchestration (US210)',
    kind: 'runtime' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus:
      'Live runtime owner — freeze, cancel orders, close positions, persist, publish events',
    honestyRequirement:
      'Not a second Kill Switch engine; paper product must reuse substrate not duplicate',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-live-execution-coordinator-freeze',
    artifact: 'LiveExecutionCoordinator.submitOrder — blocks when session.tradingFrozen',
    kind: 'runtime' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Live order submission blocked while tradingFrozen — execution gate',
    honestyRequirement: 'Live execution block ≠ paper admission block; paper hooks separate',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-execution-coordinator.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-recovery-event-admission',
    artifact: 'decideRecoveryEventAdmission — blocks on killSwitchActive → kill_switch_active',
    kind: 'runtime' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Pure domain gate exists; policy stub never reports active',
    honestyRequirement:
      'Hook exists but inactive policy means no honest paper admission block today',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'apps/api/src/modules/trading-session/domain/recovery-event-admission.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-recovery-runtime-arming',
    artifact: 'decideRecoveryRuntimeArming — blocks on killSwitchActive → kill_switch_active',
    kind: 'runtime' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Pure domain gate exists; policy stub never reports active',
    honestyRequirement: 'Arming gate wired; durable policy integration deferred to W3-O04-d',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'apps/api/src/modules/trading-session/domain/recovery-runtime-arming.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-recovery-admission-service',
    artifact: 'RecoveryEventAdmissionService.enable — calls policy.isKillSwitchActive()',
    kind: 'runtime' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Service wired to InactiveRecoveryEventAdmissionPolicy',
    honestyRequirement:
      'Service path honest only when real policy bound; stub is safe default not product Close',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/recovery/recovery-event-admission.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-recovery-arming-service',
    artifact: 'RecoveryRuntimeArmingService.arm — calls policy.isKillSwitchActive()',
    kind: 'runtime' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Service wired to InactiveRecoveryEventAdmissionPolicy',
    honestyRequirement:
      'Arming blocked only when real policy reports active; stub returns inactive',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/recovery/recovery-runtime-arming.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Operational ────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'op-td047-debt-register',
    artifact: 'TD-047 Durable paper Kill Switch — live-only REST; paper hidden',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'OPEN — residual tracked; W3-O04 productization authorized',
    honestyRequirement: 'Debt vocabulary is not a new SoT; documents gap not Close',
    futureW3O04Responsibility: 'W3-O04-e' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-lt03-capability-inventory',
    artifact: 'LT-03 Durable Kill Switch capability (Master Plan / v3-capability-inventory)',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Named — product outcomes not Closed',
    honestyRequirement: 'Capability name ≠ Kill Switch Complete; requires W3-O04 package Close',
    futureW3O04Responsibility: 'W3-O04-e' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-adr-018-kill-switch-invariants',
    artifact: 'ADR-018 invariants 44–47 — durable halt, blocks execution, auth for deactivate',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Architecture invariant — live tradingFrozen satisfies live scope only',
    honestyRequirement: 'Invariant applies to productized halt; paper gap remains until O04 Close',
    futureW3O04Responsibility: 'W3-O04-e' as const,
    evidencePath: 'docs/adr/ADR-018-architectural-invariants.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'op-us210-architecture-doc',
    artifact: 'Architecture 048 — US210 Kill Switch sequence and API table',
    kind: 'operational' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Documented live Kill Switch sequence — reference for substrate reuse',
    honestyRequirement: 'Architecture doc describes live substrate; not paper product Close claim',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/Architecture/048-Trading-Platform-V1.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),

  // ── Operator-visible ───────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ui-live-trading-page',
    artifact:
      'LiveTradingPage — Kill Switch UI with typed phrase KILL (not routed in paper product)',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Page exists but absent from app routes — hidden from paper operators',
    honestyRequirement: 'Unrouted live UI ≠ paper Kill Switch product; TD-047 hidden control',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/pages/LiveTradingPage.tsx',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-emergency-controls-panel',
    artifact: 'EmergencyControlsPanel — Command Center emergency region',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Renders panel; all emergency actions unavailable',
    honestyRequirement: 'Panel visible but honest unavailable — no fake arm/clear',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/command-center/panels/EmergencyControlsPanel.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-web-api-kill-switch-client',
    artifact: 'Web API client activateKillSwitch / clearKillSwitch',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Client methods exist — used by unrouted LiveTradingPage only',
    honestyRequirement: 'Client without visible paper surface does not Close Kill Switch product',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/shared/api.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'notif-kill-switch-activated-type',
    artifact: 'Notification types emergency-stop / kill-switch-activated (critical)',
    kind: 'operator-visible' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Ingest-ready types; Notification Delivery does not own Kill Switch control',
    honestyRequirement:
      'Notification type ≠ Kill Switch owner; kill-switch-control forbidden in boundary',
    futureW3O04Responsibility: 'out-of-scope-w3-o05' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-type.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Persistence candidates ─────────────────────────────────────────────
  Object.freeze({
    artifactId: 'persist-paper-session-kill-switch',
    artifact: 'Paper workspace armed Kill Switch state on existing Session / CC aggregate',
    kind: 'persistence-candidate' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Implemented — WorkspaceKillSwitchState on trading-session owner (W3-O04-b)',
    honestyRequirement: 'Persistence substrate only; no second store; restart recovery is W3-O04-c',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/prisma/migrations/20260827210000_w3_o04_b_kill_switch/migration.sql',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'persist-live-trading-frozen-column',
    artifact: 'live_trading_sessions.trading_frozen — existing live durable column',
    kind: 'persistence-candidate' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — Prisma migration US210; survives restart for live',
    honestyRequirement: 'Live persistence substrate; paper must not claim via live column alone',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/prisma/migrations/20260720190000_us210_kill_switch/migration.sql',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),

  // ── Ephemeral artifacts ────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'eph-recovery-admitted-armed-sets',
    artifact: 'In-memory admittedSessions / armedSessions Sets in recovery services',
    kind: 'ephemeral-artifact' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Process-local — lost on API restart',
    honestyRequirement: 'In-memory recovery state ≠ durable Kill Switch armed state',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/recovery/recovery-event-admission.service.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'eph-emergency-ui-dialog-state',
    artifact: 'Emergency controls dialog / typed-phrase UI state',
    kind: 'ephemeral-artifact' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Browser session UI state only — no backend mutation today',
    honestyRequirement: 'UI dialog state must never be treated as armed Kill Switch truth',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/command-center/emergency-controls.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Dependencies ───────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'dep-consumes-authentication',
    artifact: 'Authentication — signed-in operator context for arm/clear',
    kind: 'dependency' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — fail closed when missing',
    honestyRequirement: 'Reuse Wave 1 Authentication; no new security owner',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authorization',
    artifact: 'Authorization — PermissionClass.LiveCommand (C7) for live arm/clear',
    kind: 'dependency' as const,
    owner: 'authorization' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — all roles denied LiveCommand today; paper authz TBD in W3-O04-c',
    honestyRequirement: 'Arm/clear require authorization; no bypass',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-workspace-isolation',
    artifact: 'Workspace Isolation — scoped Kill Switch state per workspace',
    kind: 'dependency' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — cross-workspace deny required at Close',
    honestyRequirement: 'Foreign workspace must not read or drive Kill Switch',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-security-review.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-order-engine',
    artifact: 'Order Engine — cancel open orders on Kill Switch activate (live)',
    kind: 'dependency' as const,
    owner: 'order-engine' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed by EmergencyManager — best-effort cancel',
    honestyRequirement: 'Order cancel is side effect; not Kill Switch SoT',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-position-engine',
    artifact: 'Position Engine — close positions on activate when configured (live)',
    kind: 'dependency' as const,
    owner: 'position-engine' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed by EmergencyManager — configurable closePositions',
    honestyRequirement: 'Position close is side effect; not Kill Switch owner',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-trading-frozen-state',
    artifact: 'tradingFrozen armed state — produced on activate, cleared on clear',
    kind: 'dependency' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'produces' as const,
    currentStatus: 'Produced for live sessions — consumed by execution coordinator and health',
    honestyRequirement: 'Produced state must survive restart when durable; paper production TBD',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/domain/live-session.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-kill-switch-events',
    artifact: 'KillSwitchActivated / TradingFrozen / KillSwitchCleared events',
    kind: 'dependency' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'produces' as const,
    currentStatus: 'Produced to live_trading_events — audit / projection consumers',
    honestyRequirement: 'Events are operational evidence; not paper product Close alone',
    futureW3O04Responsibility: 'W3-O04-e' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/live-trading-events.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-admission-block-reason',
    artifact: 'kill_switch_active admission / arming block reason',
    kind: 'dependency' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'produces' as const,
    currentStatus:
      'Produced by domain gates when killSwitchActive true — never today via stub policy',
    honestyRequirement: 'Block reason honest only when real armed state wired',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath: 'apps/api/src/modules/trading-session/domain/recovery-event-admission.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-session-command-center-ownership',
    artifact: 'Session / Command Center / Trading Session existing ownership substrate',
    kind: 'dependency' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Binding — W3-O04 extends existing owners; no new SoT',
    honestyRequirement: 'Product outcomes on existing ownership only',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-td047-paper-hidden',
    artifact: 'TD-047 — paper product hides Kill Switch control',
    kind: 'dependency' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active blocker for paper Kill Switch product Close',
    honestyRequirement: 'Must document gap until W3-O04-b/c/d Close',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-inactive-policy',
    artifact: 'InactiveRecoveryEventAdmissionPolicy — admission never sees active Kill Switch',
    kind: 'dependency' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active blocker for honest paper admission block',
    honestyRequirement: 'Stub is safe default; replacement required in W3-O04-d',
    futureW3O04Responsibility: 'W3-O04-d' as const,
    evidencePath:
      'apps/api/src/modules/trading-session/ports/recovery-event-admission-policy.port.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-emergency-controls-unavailable',
    artifact: 'Emergency controls all unavailable — no paper arm/clear command surface',
    kind: 'dependency' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active blocker for visible paper operator arm/clear',
    honestyRequirement: 'Unavailable is honest; fake available would be dishonest',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/web/src/command-center/emergency-controls.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Ownership surfaces ─────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'own-trading-session-substrate',
    artifact: 'Trading Session — paper halt semantics, recovery admission, session stop',
    kind: 'ownership' as const,
    owner: 'trading-session' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — no ownership movement',
    honestyRequirement: 'Trading Session owns halt/admission substrate; not Risk Engine redesign',
    futureW3O04Responsibility: 'W3-O04-b' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-command-center-facade',
    artifact: 'Session / Command Center — product facade for operator arm/clear visibility',
    kind: 'ownership' as const,
    owner: 'command-center' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing owner — facade extension only in W3-O04-c',
    honestyRequirement: 'No second Command Center domain; extend facade only',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-live-trading-engine-runtime',
    artifact: 'Live Trading Engine — US210 live Kill Switch runtime (not paper product owner)',
    kind: 'ownership' as const,
    owner: 'live-trading-engine' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified existing runtime owner for live — Wave 6 reuses later',
    honestyRequirement: 'Live engine ≠ paper product Close; substrate reuse not duplication',
    futureW3O04Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'apps/api/src/modules/live-trading-engine/emergency-manager.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-bot-facade-views',
    artifact: 'Bot Facade — CommandCenter / OperatorDashboard views (no killSwitch today)',
    kind: 'ownership' as const,
    owner: 'bot-facade' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Verified facade owner — Kill Switch field absent by contract',
    honestyRequirement: 'Facade owner does not own Kill Switch SoT; projects from Session/CC',
    futureW3O04Responsibility: 'W3-O04-c' as const,
    evidencePath: 'apps/api/src/modules/bot-facade/command-center-session.view.spec.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Honesty boundaries ─────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-live-trading',
    artifact: 'Kill Switch ≠ Live Trading enabled (Wave 6)',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding honesty boundary — frozen in inventory',
    honestyRequirement: 'Kill Switch productization does not enable live capital path',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/durable-kill-switch-overview.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-monitoring',
    artifact: 'Kill Switch ≠ Monitoring Complete (O05)',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding honesty boundary — health alert is not Monitoring product',
    honestyRequirement: 'O04 Close does not open or complete O05 Monitoring',
    futureW3O04Responsibility: 'out-of-scope-w3-o05' as const,
    evidencePath: 'docs/project/version-3/wave-3/durable-kill-switch-overview.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-risk-engine',
    artifact: 'Kill Switch ≠ Risk Engine redesign',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — Risk Engine provides read-only context only',
    honestyRequirement: 'No Gate/Risk/Kill Switch chain bypass; Risk not Kill Switch owner',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-bc-ha-dr',
    artifact: 'Kill Switch ≠ Business Continuity / HA / Disaster Recovery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — halt product ≠ continuity products',
    honestyRequirement: 'Durable halt ≠ BC/HA/DR drills or infrastructure shutdown',
    futureW3O04Responsibility: 'out-of-scope-bc-ha-dr' as const,
    evidencePath: 'docs/project/version-3/wave-3/durable-kill-switch-overview.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-pause-stop-not-kill-switch',
    artifact: 'Pause / resume / stop ≠ Kill Switch Complete',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — session lifecycle controls are distinct',
    honestyRequirement: 'Session stop alone does not mean durable armed Kill Switch',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-wave3-complete',
    artifact: 'Kill Switch ≠ Wave 3 COMPLETE',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — O04 alone does not close Wave 3',
    honestyRequirement: 'Wave 3 requires O01…O05 + PO declaration; O04 is one package',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/wave-3-progress.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-session-termination',
    artifact: 'Kill Switch ≠ Session Termination product',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — halt blocks admission; distinct from terminate-all UX',
    honestyRequirement: 'close-all-sessions emergency action is separate unavailable control',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/web/src/command-center/emergency-controls.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-kill-switch-not-infrastructure-shutdown',
    artifact: 'Kill Switch ≠ Infrastructure Shutdown',
    kind: 'honesty-boundary' as const,
    owner: 'wave-3-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Binding — trading halt ≠ infra orchestration',
    honestyRequirement: 'No SSH / process kill / deployment shutdown implied',
    futureW3O04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),

  // ── Explicit OUT ───────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'out-w3-o05-monitoring',
    artifact: 'W3-O05 Monitoring & Security Health product',
    kind: 'explicit-out' as const,
    owner: 'monitoring-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W3-O04 — not opened from this package',
    honestyRequirement: 'Health alert on live ≠ Monitoring Complete',
    futureW3O04Responsibility: 'out-of-scope-w3-o05' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading / Wave 6 live capital enablement',
    kind: 'explicit-out' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W3-O04 — reuses Kill Switch control later',
    honestyRequirement: 'O04 paper productization ≠ Live Trading enabled',
    futureW3O04Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: false,
    isPaperProduct: false,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-bc-ha-dr-products',
    artifact: 'Business Continuity / High Availability / Disaster Recovery products',
    kind: 'explicit-out' as const,
    owner: 'continuity-products-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W3-O04',
    honestyRequirement: 'Durable halt ≠ BC/HA/DR product claims',
    futureW3O04Responsibility: 'out-of-scope-bc-ha-dr' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-second-kill-switch-engine',
    artifact: 'Second Kill Switch engine / runtime controller / persistence owner',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — architecture invariant',
    honestyRequirement: 'W3-O04 extends existing substrate only',
    futureW3O04Responsibility: 'out-of-scope-second-engine' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o04-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'adjacent-w3-o01-analytical-stores',
    artifact: 'W3-O01 Durable Analytical Stores (CLOSED predecessor)',
    kind: 'explicit-out' as const,
    owner: 'analytical-stores' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'CLOSED — store survival alone does not Close Kill Switch',
    honestyRequirement: 'W3-O01 SURVIVE ≠ Kill Switch Complete',
    futureW3O04Responsibility: 'out-of-scope-w3-o01' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o01-package-summary.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'adjacent-w3-o02-notification-queue',
    artifact: 'W3-O02 Notification Durable Queue (CLOSED predecessor)',
    kind: 'explicit-out' as const,
    owner: 'notification-queue' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'CLOSED — queue durability alone does not Close Kill Switch',
    honestyRequirement: 'W3-O02 queue SURVIVE ≠ Kill Switch Complete',
    futureW3O04Responsibility: 'out-of-scope-w3-o02' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o02-package-summary.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
  Object.freeze({
    artifactId: 'adjacent-w3-o03-recovery-stance',
    artifact: 'W3-O03 Recovery Residual claim stance (CLOSED predecessor)',
    kind: 'explicit-out' as const,
    owner: 'recovery-residual' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'CLOSED — ADL-008 stance alone does not Close Kill Switch',
    honestyRequirement: 'W3-O03 honesty ≠ Kill Switch product Complete',
    futureW3O04Responsibility: 'out-of-scope-w3-o03' as const,
    evidencePath: 'docs/project/version-3/wave-3/w3-o03-package-summary.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesKillSwitchComplete: false,
  }),
]);

export const W3_O04_A_BINDING_FINDINGS = Object.freeze({
  td047Open: true,
  paperKillSwitchStateMissing: false,
  paperKillSwitchPersistenceExists: true,
  paperKillSwitchRestartRecoveryExists: true,
  inactivePolicyStub: true,
  emergencyControlsUnavailable: true,
  liveTradingFrozenSurvivesRestart: true,
  paperKillSwitchSurvivesRestart: true,
  paperKillSwitchOperationalContinuityExists: true,
  paperAdmissionBlocksWhileArmed: false,
  killSwitchCompleteAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  platformSurvivesRestartAfterSliceA: false,
} as const);

export const W3_O04_A_EXPLICIT_OUT = Object.freeze([
  'second-kill-switch-engine',
  'second-runtime-controller',
  'new-persistence-owner',
  'new-bounded-context',
  'new-source-of-truth',
  'monitoring-product',
  'live-trading-enablement',
  'business-continuity',
  'high-availability',
  'disaster-recovery-product',
  'infrastructure-shutdown',
  'w3-o04-b',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
] as const);

export const W3_O04_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  newKillSwitchEngine: false,
  newRuntimeController: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  w3O01Redesigned: false,
  w3O02Redesigned: false,
  w3O03Redesigned: false,
  killSwitchCompleteClaimed: false,
  monitoringCompleteClaimed: false,
  liveTradingClaimed: false,
  wave3CompleteClaimed: false,
  businessContinuityClaimed: false,
  highAvailabilityClaimed: false,
  disasterRecoveryClaimed: false,
  customerVisibleFeature: false,
  platformSurvivesRestart: false,
} as const);

export function artifactIds(): readonly string[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W3O04AArtifactKind): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsDependencies(
  direction: W3O04ADependencyDirection,
): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter(
    (row) => row.kind === 'dependency' && row.dependencyDirection === direction,
  );
}

export function rowsPaperProduct(): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.isPaperProduct);
}

export function rowsExplicitOut(): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsHonestyBoundaries(): readonly W3O04AInventoryRow[] {
  return W3_O04_A_KILL_SWITCH_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}
