/**
 * W4-E04-a — Inventory & Exchange Connectivity Baseline (Kraken / CM-10).
 *
 * Discovery and classification only.
 * Not exchange connectivity implementation. Not REST implementation.
 * Not WebSocket implementation. Not persistence. Not restart recovery.
 * Not operational continuity. Not Exchange Connectivity Complete. Not W4-E04 CLOSED.
 *
 * Capability label CM-10 is inventory vocabulary only —
 * not authorization to invent an engine clone or second order path.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Vault / Connection / Exchange Adapter / Scope owners.
 * - EPHEMERAL: artifact is transient, stub, simulated, planned-not-implemented,
 *   UI-only, process-local, or missing — must not be treated as durable truth.
 */

export const W4_E04_A_SLICE_ID = 'W4-E04-a' as const;

export const W4_E04_A_ALLOWED_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
  'market-data-foundation',
  'live-market-data',
  'security-platform',
  'security-audit',
  'authentication',
  'authorization',
  'workspace-isolation',
  'operational-continuity',
  'command-center',
  'release-governance',
  'wave-4-documentation',
  'w4-e01-foundation',
  'w4-e02-foundation',
  'w4-e03-foundation',
  'live-trading-deferred',
  'live-trading-engine',
  'wave-5-deferred',
  'wave-6-deferred',
  'okx-closed-deferred',
  'venue-permission-deferred',
] as const);

export type W4E04AOwner = (typeof W4_E04_A_ALLOWED_OWNERS)[number];

/** Existing exchange connectivity substrate owners — no new owner. */
export const W4_E04_A_SUBSTRATE_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
] as const);

export const W4_E04_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W4E04AArtifactKind = (typeof W4_E04_A_ARTIFACT_KINDS)[number];

export const W4_E04_A_REQUIRED_ARTIFACT_KINDS = W4_E04_A_ARTIFACT_KINDS;

export const W4_E04_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W4E04ADurabilityClass = (typeof W4_E04_A_DURABILITY_CLASSES)[number];

export const W4_E04_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W4E04ADependencyDirection = (typeof W4_E04_A_DEPENDENCY_DIRECTIONS)[number];

export const W4_E04_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W4-E04-b',
  'W4-E04-c',
  'W4-E04-d',
  'W4-E04-e',
  'honesty-baseline',
  'w4-e01-foundation-consumed',
  'w4-e02-foundation-consumed',
  'w4-e03-foundation-consumed',
  'out-of-scope-w4-e01-reopen',
  'out-of-scope-w4-e02-reopen',
  'out-of-scope-w4-e03-reopen',
  'out-of-scope-w4-e05',
  'out-of-scope-live-trading',
  'out-of-scope-rest-implementation',
  'out-of-scope-websocket-implementation',
  'out-of-scope-engine-clone',
  'out-of-scope-market-data-only',
] as const);

export type W4E04AFutureResponsibility = (typeof W4_E04_A_FUTURE_RESPONSIBILITIES)[number];

export type W4E04AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W4E04AArtifactKind;
  owner: W4E04AOwner;
  durabilityClass: W4E04ADurabilityClass;
  dependencyDirection?: W4E04ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW4E04Responsibility: W4E04AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  isPaperProduct: boolean;
  authorizesExchangeConnectivityComplete: boolean;
}>;

/**
 * Frozen inventory of Kraken exchange REST/WS surfaces, authentication artifacts,
 * connection lifecycle, runtime/durable/ephemeral state, operator-visible
 * artifacts, security/platform dependencies, ownership, and honesty boundaries.
 */
export const W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY: readonly W4E04AInventoryRow[] =
  Object.freeze([
    // ── Exchange REST endpoints (commands) ───────────────────────────────────
    Object.freeze({
      artifactId: 'rest-kraken-planned-handshake',
      artifact: 'PlannedExchangeHandshakeAdapter(KRAKEN) — Connection Management validate path',
      kind: 'command' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Missing — KRAKEN not in EXCHANGE_PROVIDER_CATALOG; no planned adapter registered',
      honestyRequirement: 'Catalog gap ≠ Kraken Connected; real signed REST is W4-E04-b+ target',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-connectivity.module.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-kraken-planned-capability',
      artifact: 'PlannedExchangeCapabilityAdapter(KRAKEN) — capability probe',
      kind: 'command' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — KRAKEN not in EXCHANGE_PROVIDER_CATALOG',
      honestyRequirement: 'Capability probe ≠ venue permission verification product (E05)',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-provider-catalog.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-kraken-api-handshake-target',
      artifact: 'Kraken REST — account/permission or equivalent handshake (target)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no kraken-handshake.adapter.ts; not implemented',
      honestyRequirement: 'Missing vendor REST must not be faked as Connected',
      futureW4E04Responsibility: 'out-of-scope-rest-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connections-validate-kraken',
      artifact: 'POST /v1/connections/:id/validate — operator test (KRAKEN provider)',
      kind: 'command' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Endpoint exists — provider-agnostic; KRAKEN rejected at create (lookupExchangeProvider null)',
      honestyRequirement:
        'Validate endpoint exists; Kraken cannot reach Connected without catalog + real I/O',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/connections/connections.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connections-disconnect-kraken',
      artifact: 'POST /v1/connections/:id/disconnect — operator disconnect (KRAKEN)',
      kind: 'command' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Endpoint exists — provider-agnostic; no Kraken connection creatable via catalog today',
      honestyRequirement: 'Disconnect updates product state; vendor teardown is W4-E04-b',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connections.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-exchanges-connect-kraken',
      artifact: 'POST /v1/exchanges/connect — Exchange Adapter factory connect (KRAKEN)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing path — KRAKEN not in EXCHANGE_IDS; factory rejects unsupported id',
      honestyRequirement: 'No factory registration ≠ Connected; W4-E04-b target',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-adapter.controller.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-exchanges-disconnect-kraken',
      artifact: 'POST /v1/exchanges/disconnect — Exchange Adapter factory disconnect (KRAKEN)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing path — KRAKEN not in EXCHANGE_IDS',
      honestyRequirement: 'Factory disconnect requires factory registration first',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/domain/exchange-id.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-market-data-public-kraken',
      artifact: 'Market Data Foundation — public Kraken REST (planned symbol discovery)',
      kind: 'command' as const,
      owner: 'market-data-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — KRAKEN not in market-data provider catalog; resolve returns null',
      honestyRequirement: 'Public market data ≠ credentialed connect/test/disconnect Complete',
      futureW4E04Responsibility: 'out-of-scope-market-data-only' as const,
      evidencePath:
        'apps/api/src/modules/market-data-foundation/market-data-adapter.factory.spec.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Exchange WebSocket streams ───────────────────────────────────────────
    Object.freeze({
      artifactId: 'ws-kraken-public-stream',
      artifact: 'Kraken public WebSocket market streams',
      kind: 'command' as const,
      owner: 'live-market-data' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no Kraken public WS connector in live-market-data',
      honestyRequirement: 'Public WS ≠ authenticated user-data stream; ≠ W4-E04 credentialed I/O',
      futureW4E04Responsibility: 'out-of-scope-market-data-only' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ws-kraken-adapter-subscribe-stubs',
      artifact: 'KrakenExchangeAdapter subscribeTicker/OrderUpdates/ExecutionUpdates — noop stubs',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no KrakenExchangeAdapter class in venue.adapters.ts',
      honestyRequirement: 'No adapter class must not imply WebSocket Complete or Connected',
      futureW4E04Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ws-kraken-authenticated-user-data',
      artifact: 'Kraken authenticated private WebSocket (orders/account)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — not implemented',
      honestyRequirement: 'Missing authenticated WS must not be faked; out of W4-E04-a scope',
      futureW4E04Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Exchange authentication artifacts ────────────────────────────────────
    Object.freeze({
      artifactId: 'auth-vault-kraken-secret-type',
      artifact: 'HoldableSecretType.Kraken — vault credential classification',
      kind: 'state' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Gap — vault substrate exists; no Kraken holdable secret type registered today',
      honestyRequirement:
        'Vault remains sole credential owner; adapter retrieves only; type gap documented',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-connection-vault-mapping-kraken',
      artifact: 'Connection vault mapping KRAKEN → HoldableSecretType.Kraken',
      kind: 'runtime' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Gap — exchange-handshake.vault.ts maps BINANCE/BYBIT/OKX only; KRAKEN returns null',
      honestyRequirement: 'Credentials never echoed plaintext; fail closed on missing vault type',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-handshake.vault.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-handshake-vault-retrieve-kraken',
      artifact: 'ExchangeHandshakeService vault retrieve before Kraken signed REST',
      kind: 'runtime' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Not reachable — KRAKEN not in provider catalog; no handshake adapter',
      honestyRequirement: 'When implemented, signing inside handshake/adapter boundary only',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-handshake.service.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-kraken-request-signing',
      artifact: 'Kraken REST request signing with apiKey and secret',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no Kraken signing client in exchange-adapter or handshake',
      honestyRequirement: 'Real signing required for honest Connected at Close',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Connection lifecycle ─────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'lifecycle-connection-record-kraken',
      artifact: 'ConnectionRecord — operator Kraken connection metadata and status',
      kind: 'state' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Substrate exists — Prisma connection_records provider-agnostic; KRAKEN not creatable via catalog',
      honestyRequirement:
        'Durable status must reflect real vendor round-trip at Close; stub forbidden',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/prisma/schema.prisma',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-connection-transitions-kraken',
      artifact: 'connection-lifecycle.ts — legal status transitions for Kraken connections',
      kind: 'runtime' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — fail closed transition rules (provider-agnostic)',
      honestyRequirement: 'CONNECTED transition requires validation evidence; no fake Connected',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-connection-model-kraken',
      artifact: 'ExchangeConnection — adapter-layer Kraken connection persistence',
      kind: 'state' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Substrate exists — exchange_connections table provider-agnostic; no Kraken factory path',
      honestyRequirement: 'Two connection models must not drift; factory extension only',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/prisma-exchange-adapter.repository.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-manager-kraken',
      artifact: 'ExchangeManager — Kraken adapter connect/disconnect orchestration',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no KrakenExchangeAdapter; factory cannot create KRAKEN',
      honestyRequirement:
        'Manager must not mark Connected without vendor round-trip after W4-E04-b',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-session-projection-kraken',
      artifact: 'ExchangeSessionView — session health after Kraken handshake attempt',
      kind: 'projection' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Not reachable — KRAKEN not in provider catalog; no handshake path',
      honestyRequirement: 'Session projection ≠ adapter factory Connected; consume both honestly',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-session.health.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Runtime state ────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'runtime-kraken-adapter-stub-connected-flag',
      artifact: 'KrakenExchangeAdapter in-memory connected flag (simulated connect)',
      kind: 'ephemeral-artifact' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no KrakenExchangeAdapter class; unlike OKX no stub exists today',
      honestyRequirement: 'No adapter class ≠ Connected; factory gap documented honestly',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-exchange-registry-kraken',
      artifact: 'ExchangeRegistry — in-memory Kraken adapter instances per workspace',
      kind: 'ephemeral-artifact' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Registry exists — no Kraken adapter to register; rebuilt on API restart',
      honestyRequirement: 'Registry loss on restart; continuity is W4-E04-d not this slice',
      futureW4E04Responsibility: 'W4-E04-d' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-registry.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-exchange-factory-kraken',
      artifact: 'ExchangeFactory.create(KRAKEN) → KrakenExchangeAdapter',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — EXCHANGE_IDS is BINANCE/BYBIT/OKX/MOCK only; no Kraken case',
      honestyRequirement:
        'Factory must register Kraken with vault-backed real I/O; no engine clone',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-factory.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-kraken-exchange-id',
      artifact: "ExchangeId 'KRAKEN' — catalog and factory registration",
      kind: 'state' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — EXCHANGE_IDS does not include KRAKEN',
      honestyRequirement: 'Catalog absence ≠ Connected; first Wave 4 venue with no factory id',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/domain/exchange-id.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Durable state candidates ─────────────────────────────────────────────
    Object.freeze({
      artifactId: 'persist-vault-ciphertext-kraken',
      artifact: 'Vault ciphertext store — authoritative Kraken credential persistence substrate',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Substrate exists — Wave 1 closed; no Kraken holdable type yet',
      honestyRequirement: 'Vault is credential SoT; W4-E04 must not duplicate; type gap documented',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/secret-vault.service.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-connection-records-kraken',
      artifact: 'connection_records — Connection Management durable Kraken metadata substrate',
      kind: 'persistence-candidate' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Substrate exists — provider-agnostic; KRAKEN not in CONNECTION_PROVIDERS',
      honestyRequirement: 'Status column must stay honest post W4-E04-b real round-trip',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/prisma/schema.prisma',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-exchange-connections-kraken',
      artifact: 'exchange_connections — Exchange Adapter layer Kraken persistence substrate',
      kind: 'persistence-candidate' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Substrate exists — provider-agnostic table; no Kraken factory path today',
      honestyRequirement: 'No new persistence owner; extend existing tables only',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/prisma-exchange-adapter.repository.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-kraken-connection-continuity',
      artifact: 'Kraken connection continuity / restart recovery durable anchors',
      kind: 'persistence-candidate' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Missing — no prisma-kraken-exchange-connectivity-state.repository.ts or equivalent',
      honestyRequirement:
        'No Kraken continuity persistence; restart recovery is W4-E04-c not this slice',
      futureW4E04Responsibility: 'W4-E04-c' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Operator-visible artifacts ───────────────────────────────────────────
    Object.freeze({
      artifactId: 'ui-connections-page-kraken',
      artifact: 'ConnectionsPage — Kraken provider validate/disconnect UX',
      kind: 'operator-visible' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Gap — KRAKEN not in CONNECTION_PROVIDERS; operator cannot select Kraken in Connections UI',
      honestyRequirement: 'Catalog gap must not imply Connected; honest not-offered until W4-E04-b',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-catalog.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-web-validate-connection-client-kraken',
      artifact: 'Web validateConnection API client (KRAKEN provider)',
      kind: 'operator-visible' as const,
      owner: 'command-center' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Client exists — provider-agnostic; no Kraken provider to invoke',
      honestyRequirement: 'Client alone ≠ Kraken Connected Complete',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/web/src/shared/api.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-honest-connected-label-kraken',
      artifact: 'Honest Connected / Error / Expired / permission labels for Kraken',
      kind: 'operator-visible' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no Kraken in catalog; honest not-offered labels W4-E04-b+',
      honestyRequirement: 'Never Connected without vendor evidence; paper default preserved',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-overview.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-exchange-scope-kraken-catalog',
      artifact: 'Exchange Scope PC-12 — Kraken venue catalog (liveAdapter: false)',
      kind: 'operator-visible' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — offered: true; liveAdapter: false; venueApiUsed: false',
      honestyRequirement: 'Scope catalog honesty — no live adapter claim for Kraken',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope-product/exchange-scope.view.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Platform Readiness dependencies ──────────────────────────────────────
    Object.freeze({
      artifactId: 'dep-platform-readiness-exchange-connectivity',
      artifact: 'Platform Readiness exchangeConnectivity view — aggregate continuity',
      kind: 'dependency' as const,
      owner: 'operational-continuity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — W4-E01-d aggregate projection; no Kraken-specific continuity row',
      honestyRequirement: 'Continuity ≠ Connected; Kraken-scoped projection is W4-E04-d',
      futureW4E04Responsibility: 'W4-E04-d' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-security-platform-kraken',
      artifact: 'Security Platform — rate limits and hardening defaults for connect surfaces',
      kind: 'dependency' as const,
      owner: 'security-platform' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed defaults; no Kraken-specific fork',
      honestyRequirement: 'Reuse platform controls; no second security product',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Security dependencies ────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'dep-consumes-authentication-kraken',
      artifact: 'Authentication — signed-in operator for Kraken connect/test/disconnect',
      kind: 'dependency' as const,
      owner: 'authentication' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed when missing',
      honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authorization-kraken',
      artifact: 'Authorization — permitted roles for Kraken connection surfaces',
      kind: 'dependency' as const,
      owner: 'authorization' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — connect/test requires permitted role',
      honestyRequirement: 'Unauthorized deny; no new IAM',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-workspace-isolation-kraken',
      artifact: 'Workspace Isolation — A↛B Kraken credentials and connection state',
      kind: 'dependency' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — cross-workspace deny required at Close',
      honestyRequirement: 'Foreign workspace must not connect/test with B credentials',
      futureW4E04Responsibility: 'W4-E04-e' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-security-audit-kraken',
      artifact: 'Security Audit — Kraken connect/test/disconnect attribution events',
      kind: 'dependency' as const,
      owner: 'security-audit' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — lifecycle audit on connections (provider-agnostic)',
      honestyRequirement: 'Emit required outcomes; do not own audit store',
      futureW4E04Responsibility: 'W4-E04-e' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle-audit.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-produces-connection-audit-events-kraken',
      artifact: 'Connection lifecycle audit — produces Kraken connect/test/disconnect audit events',
      kind: 'dependency' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'produces' as const,
      currentStatus: 'Substrate exists — provider-agnostic; no Kraken connection creatable today',
      honestyRequirement:
        'Audit events are attribution inputs; Connection Management does not own audit store',
      futureW4E04Responsibility: 'W4-E04-e' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle-audit.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-not-in-exchange-provider-catalog',
      artifact:
        'KRAKEN absent from EXCHANGE_PROVIDER_CATALOG blocks handshake and capability paths',
      kind: 'dependency' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — lookupExchangeProvider(KRAKEN) returns null',
      honestyRequirement: 'W4-E04-b must add catalog entry before honest validate path',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-provider-registry.spec.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-not-in-connection-providers',
      artifact: 'KRAKEN absent from CONNECTION_PROVIDERS blocks operator connection creation',
      kind: 'dependency' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — Connections UI and create reject unknown provider',
      honestyRequirement: 'W4-E04-b must add CONNECTION_PROVIDERS entry or honest not-offered UX',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-catalog.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-no-adapter-kraken',
      artifact: 'Missing KrakenExchangeAdapter blocks honest factory Connected',
      kind: 'dependency' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — no adapter class; unlike OKX no stub exists',
      honestyRequirement: 'W4-E04-b must register factory adapter with real round-trip',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-no-vault-type-kraken',
      artifact: 'Missing HoldableSecretType.Kraken blocks vault-backed handshake',
      kind: 'dependency' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — vaultSecretTypeForExchangeProvider(KRAKEN) returns null',
      honestyRequirement: 'W4-E04-b must add Kraken holdable type before credential retrieve',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-handshake.vault.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Platform / W4-E01/E02/E03 foundation dependencies ────────────────────
    Object.freeze({
      artifactId: 'dep-depends-on-w2-connection-management-kraken',
      artifact: 'W2 Connection Management — CLOSED predecessor facade (Kraken not in catalog)',
      kind: 'dependency' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — consumed; Kraken not yet in CONNECTION_PROVIDERS',
      honestyRequirement:
        'Connection Management owns operator surface; W4-E04 extends catalog + adapter',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-2/connection-management-overview.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-w4-e01-foundation',
      artifact: 'W4-E01 CLOSED foundation — durable/recovery/continuity patterns consumed',
      kind: 'dependency' as const,
      owner: 'w4-e01-foundation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — extend for Kraken venue scope; do not reopen or redesign',
      honestyRequirement: 'W4-E01-b/c/d artifacts consumed; Kraken extension in W4-E04-b/c/d',
      futureW4E04Responsibility: 'w4-e01-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-w4-e02-foundation',
      artifact: 'W4-E02 CLOSED foundation — Bybit patterns consumed for Kraken extension',
      kind: 'dependency' as const,
      owner: 'w4-e02-foundation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — extend W4-E02-b/c/d patterns for Kraken venue scope; do not reopen',
      honestyRequirement: 'W4-E02 foundation consumed; Kraken extension in W4-E04-b/c/d',
      futureW4E04Responsibility: 'w4-e02-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-w4-e03-foundation',
      artifact: 'W4-E03 CLOSED foundation — OKX patterns consumed for Kraken extension',
      kind: 'dependency' as const,
      owner: 'w4-e03-foundation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — extend W4-E03-b/c/d patterns for Kraken venue scope; do not reopen',
      honestyRequirement: 'W4-E03 foundation consumed; Kraken extension in W4-E04-b/c/d',
      futureW4E04Responsibility: 'w4-e03-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-exchange-scope-kraken',
      artifact: 'Exchange Scope RC-27 — kraken venue code isolation boundary',
      kind: 'dependency' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: "Exists — venue code 'kraken' registrable; liveAdapter: false",
      honestyRequirement: 'Exchange Scope remains isolation SoT; adapter must not redefine cluster',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope/domain/exchange-scope-domain-shared.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-observed-by-live-trading-engine-kraken',
      artifact: 'Live Trading Engine consumes ExchangeAdapterService.connect (no Kraken path)',
      kind: 'dependency' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'No Kraken factory registration — live path cannot connect Kraken today',
      honestyRequirement: 'Live path ≠ paper Connected honesty; Wave 6 gate unchanged',
      futureW4E04Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'apps/api/src/modules/live-trading-engine/connection-supervisor.ts',
      existsToday: true,
      isPaperProduct: false,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Operational ──────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'op-cm10-capability-inventory',
      artifact: 'CM-10 Kraken connectivity capability — inventory entry',
      kind: 'operational' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Named — 0% real I/O; W4-E04 productization target',
      honestyRequirement: 'CM-10 label ≠ Kraken Real I/O Complete until package Close',
      futureW4E04Responsibility: 'W4-E04-e' as const,
      evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'op-w4-e04-planning-approved',
      artifact: 'W4-E04 Planning Package — APPROVED; W4-E04-a inventory in progress',
      kind: 'operational' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Planning APPROVED — slice a inventory only',
      honestyRequirement: 'Planning Approval ≠ Exchange Connectivity Complete',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-planning-approval.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Ownership surfaces ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'own-exchange-adapter-factory-kraken',
      artifact: 'Exchange Adapter factory — Kraken venue protocol I/O owner (extend only)',
      kind: 'ownership' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — no Kraken adapter today; W4-E04 registers factory',
      honestyRequirement: 'Factory extension only; no second order path',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-connection-management-facade-kraken',
      artifact: 'Connection Management — operator Kraken connect/test/disconnect facade',
      kind: 'ownership' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — Wave 2 COMPLETE; Kraken catalog entry pending',
      honestyRequirement: 'Facade owns operator product surface; adapter owns protocol I/O',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-secret-vault-credentials-kraken',
      artifact: 'Vault — Kraken customer secret ciphertext owner',
      kind: 'ownership' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — retrieve-only for adapter I/O; type gap documented',
      honestyRequirement: 'No local secret store; no plaintext echo',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-exchange-scope-isolation-kraken',
      artifact: 'Exchange Scope / Cluster — Kraken isolation boundary owner (RC-27)',
      kind: 'ownership' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — not transport or credentials',
      honestyRequirement: 'Exchange Scope remains isolation SoT; adapter consumes scope id',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope/README.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Honesty boundaries ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'honesty-connected-not-live-trading-kraken',
      artifact: 'Connected ≠ Live Trading; Connected ≠ live order submission (Kraken)',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — frozen in inventory',
      honestyRequirement: 'Paper remains default; Wave 6 gate unchanged',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-overview.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-connected-requires-round-trip-kraken',
      artifact: 'Connected requires real Kraken vendor round-trip with vault credentials',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — no adapter, catalog, or vault type today; W4-E04-b fixes',
      honestyRequirement: 'Simulated CONNECTED without keys forbidden',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-scope-catalog-not-connected',
      artifact: 'Exchange Scope kraken label with liveAdapter:false ≠ Kraken Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — catalog label exists; no factory adapter registered',
      honestyRequirement: 'Scope catalog presence ≠ credentialed connectivity Complete',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-overview.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-planned-handshake-not-connected-kraken',
      artifact: 'PlannedExchangeHandshakeAdapter(KRAKEN) not_implemented ≠ Kraken Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Binding — KRAKEN absent from provider catalog; validate path unreachable today',
      honestyRequirement: 'Credential collection alone ≠ Connected; W4-E04-b registers handshake',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-factory-stub-not-connected-kraken',
      artifact: 'KrakenExchangeAdapter stub/simulated connect ≠ Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Binding — no adapter class today; when offered W4-E04-b starts stub then real I/O',
      honestyRequirement: 'Factory extension must replace stub with real round-trip at Close',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-not-in-connection-catalog-not-connected',
      artifact: 'KRAKEN absent from CONNECTION_PROVIDERS ≠ Kraken Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — operator cannot create Kraken connection today',
      honestyRequirement: 'Catalog gap must be honest not-offered until W4-E04-b',
      futureW4E04Responsibility: 'W4-E04-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w4-e01-foundation-consumed',
      artifact: 'W4-E01 CLOSED foundation consumed — not reopened for Kraken',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — extend W4-E01-b/c/d patterns for Kraken scope only',
      honestyRequirement: 'No W4-E01 redesign; no duplicate persistence owner',
      futureW4E04Responsibility: 'w4-e01-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w4-e02-foundation-consumed',
      artifact: 'W4-E02 CLOSED foundation consumed — not reopened for Kraken',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — extend W4-E02-b/c/d patterns for Kraken scope only',
      honestyRequirement: 'No W4-E02 redesign; no duplicate persistence owner',
      futureW4E04Responsibility: 'w4-e02-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w4-e03-foundation-consumed',
      artifact: 'W4-E03 CLOSED foundation consumed — not reopened for Kraken',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — extend W4-E03-b/c/d patterns for Kraken scope only',
      honestyRequirement: 'No W4-E03 redesign; no duplicate persistence owner',
      futureW4E04Responsibility: 'w4-e03-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-e04-not-wave4-complete',
      artifact: 'W4-E04 ≠ Wave 4 COMPLETE; E04 ≠ venue permission product',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — E04–E05 sequenced separately',
      honestyRequirement: 'Kraken-only scope; no catalog venue Complete claims',
      futureW4E04Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/wave-4-progress.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-no-engine-clone-kraken',
      artifact: 'No engine clone per venue; Kraken factory extension only',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding architecture invariant',
      honestyRequirement: 'Single Exchange Adapter factory; Exchange Scope isolation boundary',
      futureW4E04Responsibility: 'out-of-scope-engine-clone' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Explicit OUT ─────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'out-rest-implementation-slice-a',
      artifact: 'REST implementation in W4-E04-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — inventory only; W4-E04-b+ implements real adapter REST',
      honestyRequirement: 'Slice a catalogues endpoints; does not implement them',
      futureW4E04Responsibility: 'out-of-scope-rest-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-websocket-implementation-slice-a',
      artifact: 'WebSocket implementation in W4-E04-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — inventory only',
      honestyRequirement: 'Authenticated WS deferred beyond slice a',
      futureW4E04Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-w4-e01-reopen',
      artifact: 'W4-E01 reopen / redesign for Kraken',
      kind: 'explicit-out' as const,
      owner: 'w4-e01-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — W4-E01 CLOSED; consume foundation only',
      honestyRequirement: 'Extend W4-E01-b/c/d patterns; do not duplicate owner',
      futureW4E04Responsibility: 'out-of-scope-w4-e01-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-w4-e02-reopen',
      artifact: 'W4-E02 reopen / redesign for Kraken',
      kind: 'explicit-out' as const,
      owner: 'w4-e02-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — W4-E02 CLOSED; consume foundation only',
      honestyRequirement: 'Extend W4-E02-b/c/d patterns; do not duplicate owner',
      futureW4E04Responsibility: 'out-of-scope-w4-e02-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-w4-e03-reopen',
      artifact: 'W4-E03 reopen / redesign for Kraken',
      kind: 'explicit-out' as const,
      owner: 'w4-e03-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — W4-E03 CLOSED; consume foundation only',
      honestyRequirement: 'Extend W4-E03-b/c/d patterns; do not duplicate owner',
      futureW4E04Responsibility: 'out-of-scope-w4-e03-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-engine-clone-per-venue',
      artifact: 'Engine clone per venue / second Canonical Order Path',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — architecture invariant',
      honestyRequirement: 'Factory extension only',
      futureW4E04Responsibility: 'out-of-scope-engine-clone' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-live-trading-wave6',
      artifact: 'Live Trading / live order submission (Wave 6)',
      kind: 'explicit-out' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Out of W4-E04 paper scope',
      honestyRequirement: 'Connect/test ≠ live capital orders',
      futureW4E04Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: false,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-venue-permission-product-e05',
      artifact: 'Venue permission verification product (V3-E05)',
      kind: 'explicit-out' as const,
      owner: 'venue-permission-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Out of W4-E04 — E05 sequenced later',
      honestyRequirement: 'Capability probe ≠ E05 Complete',
      futureW4E04Responsibility: 'out-of-scope-w4-e05' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
  ]);

export const W4_E04_A_BINDING_FINDINGS = Object.freeze({
  exchangeConnectivityCompleteAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  exchangeConnectivitySurvivesRestartAfterSliceA: false,
  krakenAdapterRealIoExists: false,
  krakenAdapterStubOrSimulatedExists: false,
  krakenHandshakeRealIoExists: false,
  plannedHandshakeNotImplementedForKraken: true,
  durableContinuityPersistenceDoesNotExist: true,
  restartRecoveryDoesNotExist: true,
  operationalContinuityDoesNotExist: true,
  noCustomerVisibleExchangeConnectivity: true,
  w4E01FoundationConsumedNotRedesigned: true,
  w4E02FoundationConsumedNotRedesigned: true,
  w4E03FoundationConsumedNotRedesigned: true,
  honestConnectedProductRulesFrozen: true,
} as const);

export const W4_E04_A_EXPLICIT_OUT = Object.freeze([
  'rest-implementation',
  'websocket-implementation',
  'persistence-implementation',
  'restart-recovery',
  'operational-continuity',
  'new-persistence-owner',
  'new-bounded-context',
  'new-source-of-truth',
  'engine-clone',
  'live-trading-enablement',
  'w4-e01-reopen',
  'w4-e02-reopen',
  'w4-e03-reopen',
  'w4-e04-b',
  'w4-e04-c',
  'w4-e04-d',
  'w4-e04-e',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'exchange-connectivity-complete',
  'kraken-connected',
] as const);

export const W4_E04_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateExchangeSubsystem: false,
  engineClonePerVenue: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  w4E01Reopened: false,
  w4E02Reopened: false,
  w4E03Reopened: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  exchangeConnectivityCompleteClaimed: false,
  krakenRealIoCompleteClaimed: false,
  liveTradingClaimed: false,
  wave4CompleteClaimed: false,
  customerVisibleFeature: false,
  exchangeConnectivitySurvivesRestart: false,
} as const);

export function artifactIds(): readonly string[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W4E04AArtifactKind): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.durabilityClass === 'SURVIVE',
  );
}

export function rowsEphemeral(): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.durabilityClass === 'EPHEMERAL',
  );
}

export function rowsDependencies(
  direction: W4E04ADependencyDirection,
): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.kind === 'dependency' && row.dependencyDirection === direction,
  );
}

export function rowsPaperProduct(): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.isPaperProduct);
}

export function rowsExplicitOut(): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsHonestyBoundaries(): readonly W4E04AInventoryRow[] {
  return W4_E04_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExchangeConnectivitySurvive(): readonly W4E04AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'w4-e01-foundation',
      'w4-e02-foundation',
      'w4-e03-foundation',
    ].includes(row.owner),
  );
}

export function rowsExchangeConnectivityEphemeral(): readonly W4E04AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'live-trading-deferred',
      'live-trading-engine',
      'operational-continuity',
    ].includes(row.owner),
  );
}
