/**
 * W4-E05-a — Venue Permission Inventory & Honesty Baseline (V3-E05).
 *
 * Discovery and classification only.
 * Not permission probe implementation. Not persistence. Not restart recovery.
 * Not operational continuity. Not Venue Permission Verification Complete. Not W4-E05 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Vault / Connection / Exchange Adapter / Scope owners.
 * - EPHEMERAL: artifact is transient, stub, hardcoded default, simulated,
 *   UI-only, process-local, or missing — must not be treated as vendor-verified truth.
 */

export const W4_E05_A_SLICE_ID = 'W4-E05-a' as const;

export const W4_E05_A_ALLOWED_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
  'security-platform',
  'security-audit',
  'authentication',
  'authorization',
  'workspace-isolation',
  'operational-continuity',
  'command-center',
  'release-governance',
  'wave-4-documentation',
  'w4-e01-foundation',
  'w4-e02-foundation',
  'w4-e03-foundation',
  'w4-e04-foundation',
  'live-trading-deferred',
  'wave-5-deferred',
  'wave-6-deferred',
] as const);

export type W4E05AOwner = (typeof W4_E05_A_ALLOWED_OWNERS)[number];

/** Existing venue permission substrate owners — no new owner. */
export const W4_E05_A_SUBSTRATE_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
] as const);

export const W4_E05_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W4E05AArtifactKind = (typeof W4_E05_A_ARTIFACT_KINDS)[number];

export const W4_E05_A_REQUIRED_ARTIFACT_KINDS = W4_E05_A_ARTIFACT_KINDS;

export const W4_E05_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W4E05ADurabilityClass = (typeof W4_E05_A_DURABILITY_CLASSES)[number];

export const W4_E05_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W4E05ADependencyDirection = (typeof W4_E05_A_DEPENDENCY_DIRECTIONS)[number];

export const W4_E05_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W4-E05-b',
  'W4-E05-c',
  'W4-E05-d',
  'W4-E05-e',
  'honesty-baseline',
  'w4-e01-foundation-consumed',
  'w4-e02-foundation-consumed',
  'w4-e03-foundation-consumed',
  'w4-e04-foundation-consumed',
  'out-of-scope-w4-e01-reopen',
  'out-of-scope-w4-e02-reopen',
  'out-of-scope-w4-e03-reopen',
  'out-of-scope-w4-e04-reopen',
  'out-of-scope-live-trading',
  'out-of-scope-persistence-implementation',
  'out-of-scope-restart-recovery',
  'out-of-scope-operational-continuity',
  'out-of-scope-engine-clone',
  'out-of-scope-permission-probe-io',
] as const);

export type W4E05AFutureResponsibility = (typeof W4_E05_A_FUTURE_RESPONSIBILITIES)[number];

export type W4E05AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W4E05AArtifactKind;
  owner: W4E05AOwner;
  durabilityClass: W4E05ADurabilityClass;
  dependencyDirection?: W4E05ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW4E05Responsibility: W4E05AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  isPaperProduct: boolean;
  authorizesVenuePermissionVerificationComplete: boolean;
}>;

/**
 * Frozen inventory of vendor-reported permissions, exchange-reported capabilities,
 * permission verification state, integrity anchors, adapter/factory ownership,
 * Connection Management and Vault dependencies, catalog dependencies, runtime caches,
 * in-memory permission state, placeholder/default values, and honesty boundaries.
 */
export const W4_E05_A_VENUE_PERMISSION_INVENTORY: readonly W4E05AInventoryRow[] = Object.freeze([
  // ── Permission probe commands (targets) ────────────────────────────────────
  Object.freeze({
    artifactId: 'cmd-vendor-permission-probe-binance',
    artifact: 'Vendor permission probe — BINANCE (target)',
    kind: 'command' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — connect uses hardcoded VenueExchangeAdapter.apiPermissions()',
    honestyRequirement: 'Vendor-reported permissions are authoritative when implemented',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-vendor-permission-probe-bybit',
    artifact: 'Vendor permission probe — BYBIT (target)',
    kind: 'command' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — same hardcoded default path as BINANCE',
    honestyRequirement: 'Vendor-reported permissions are authoritative when implemented',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-vendor-permission-probe-okx',
    artifact: 'Vendor permission probe — OKX (target)',
    kind: 'command' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — same hardcoded default path as BINANCE',
    honestyRequirement: 'Vendor-reported permissions are authoritative when implemented',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-vendor-permission-probe-kraken',
    artifact: 'Vendor permission probe — KRAKEN (target)',
    kind: 'command' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no KrakenExchangeAdapter; catalog label only',
    honestyRequirement: 'Vendor-reported permissions are authoritative when implemented',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e04-a-exchange-connectivity-inventory.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-exchange-connectivity-capability-probe',
    artifact: 'PlannedExchangeCapabilityAdapter — exchange capability probe',
    kind: 'command' as const,
    owner: 'exchange-connectivity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Partial — per-venue capability probe during connect/test',
    honestyRequirement: 'Capability probe ≠ venue permission verification product (E05)',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-provider-catalog.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'cmd-exchange-manager-connect-permission-snapshot',
    artifact: 'ExchangeManager.connect — apiPermissions snapshot on connect',
    kind: 'command' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — reads adapter.apiPermissions() or hardcoded fallback',
    honestyRequirement: 'Connect snapshot from non-authoritative defaults ≠ permission verified',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── State ──────────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'state-exchange-connection-api-permissions',
    artifact: 'ExchangeConnection.apiPermissions — domain field',
    kind: 'state' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — persisted on exchange_connections; source often non-authoritative',
    honestyRequirement: 'Stored permissions must trace to vendor probe when E05 product ships',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/domain/exchange-connection.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-exchange-reported-capabilities',
    artifact: 'ExchangeCapabilities — adapter.declaredCapabilities (not permissions)',
    kind: 'state' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — static capability flags per venue adapter class',
    honestyRequirement: 'Capabilities ≠ vendor-reported API key permissions',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/domain/exchange-capabilities.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'state-permission-verification-status',
    artifact: 'Permission verification state — verified / unverified / expired / problem',
    kind: 'state' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no cross-venue permission verification product state',
    honestyRequirement: 'Must not fabricate verified state without vendor probe',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Projection ─────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'projection-exchanges-api-permissions-ui',
    artifact: 'ExchangesPage — API permissions panel from connection.apiPermissions',
    kind: 'projection' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — displays stored permissions; may reflect hardcoded defaults',
    honestyRequirement: 'UI must not present hardcoded defaults as vendor-verified',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/web/src/pages/ExchangesPage.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Runtime ────────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'runtime-read-api-permissions-fallback',
    artifact: 'ExchangeManager.readApiPermissions — hardcoded fallback',
    kind: 'runtime' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — returns [spot.read, spot.trade] when adapter lacks apiPermissions()',
    honestyRequirement: 'Hardcoded default permissions are NOT authoritative',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-venue-adapter-default-api-permissions',
    artifact: 'VenueExchangeAdapter.apiPermissions — default [spot.read, spot.trade]',
    kind: 'runtime' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — hardcoded default on BINANCE/BYBIT/OKX stub adapters',
    honestyRequirement: 'Hardcoded default permissions are NOT authoritative',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-adapter-in-memory-connected',
    artifact: 'VenueExchangeAdapter private connected flag — in-memory lifecycle',
    kind: 'runtime' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — process-local; lost on restart',
    honestyRequirement: 'Runtime permission cache is EPHEMERAL',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-exchange-registry',
    artifact: 'ExchangeRegistry — in-process adapter instances',
    kind: 'runtime' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — in-memory registry; no permission probe cache yet',
    honestyRequirement: 'Runtime permission cache is EPHEMERAL',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-registry.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-exchange-factory',
    artifact: 'ExchangeFactory — adapter registration and creation',
    kind: 'runtime' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — factory extension point for permission probe I/O',
    honestyRequirement: 'Factory extension only — no engine clone',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-factory.ts',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Operational ────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'operational-w4-e05-slice-a-inventory',
    artifact: 'W4-E05-a venue permission inventory baseline',
    kind: 'operational' as const,
    owner: 'wave-4-documentation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'This slice — inventory and honesty baseline only',
    honestyRequirement: 'Inventory ≠ permission verification product Complete',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-a-venue-permission-inventory.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'operational-cm04-health-permission-api-dependency',
    artifact: 'CM-04 Health Monitoring — venue permission API dependency',
    kind: 'operational' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Blocked — CM-04 depends on Wave 4 E05 permission APIs',
    honestyRequirement: 'Health product blocked until E05 product ships',
    futureW4E05Responsibility: 'W4-E05-d' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Operator-visible ───────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ui-exchanges-page-permissions-panel',
    artifact: 'Connections / Exchanges — API permissions list',
    kind: 'operator-visible' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — shows connection.apiPermissions; source may be hardcoded',
    honestyRequirement: 'Must not label hardcoded defaults as vendor-verified',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/web/src/pages/ExchangesPage.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-honest-permission-verified-label',
    artifact: 'Honest Permission verified label — cross-venue',
    kind: 'operator-visible' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no vendor-verified permission product label',
    honestyRequirement: 'Permission verified requires vendor probe evidence',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'ui-permission-problem-label',
    artifact: 'Honest Permission problem label — insufficient vendor permissions',
    kind: 'operator-visible' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — no cross-venue permission problem product label',
    honestyRequirement: 'Insufficient permissions visible when vendor reports',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Persistence candidates ─────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'persist-exchange-connections-api-permissions',
    artifact: 'Prisma exchange_connections.api_permissions JSON column',
    kind: 'persistence-candidate' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — stores permissions; populated from non-authoritative source today',
    honestyRequirement: 'Column survives restart; content must become vendor-sourced in E05-b',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/prisma/schema.prisma',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'persist-vendor-permission-verification',
    artifact: 'Durable venue permission verification anchors on Exchange Adapter owner',
    kind: 'persistence-candidate' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus:
      'Implemented — WorkspaceVenuePermissionVerificationState (W4-E05-b); restart recovery (W4-E05-c)',
    honestyRequirement:
      'Persistence only; canonical verification anchors; no runtime permission cache; operational continuity is W4-E05-d',
    futureW4E05Responsibility: 'W4-E05-c' as const,
    evidencePath:
      'apps/api/src/modules/exchange-adapter/persistence/prisma-venue-permission-verification-state.repository.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'persist-permission-integrity-anchors',
    artifact: 'Permission integrity anchors — verification checksum / probe metadata (target)',
    kind: 'persistence-candidate' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Missing — planned W4-E05-b',
    honestyRequirement: 'Integrity anchors must not fabricate verified without probe',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'persist-vault-credentials-for-permission-probe',
    artifact: 'Vault ciphertext — credentials for permission probe signing',
    kind: 'persistence-candidate' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Exists — Wave 1 vault; retrieve-only for adapter/probe I/O',
    honestyRequirement: 'Vault owns secrets; adapter retrieves for probe only',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-security-review.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Ephemeral artifacts ────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ephemeral-hardcoded-spot-read-spot-trade',
    artifact: 'Placeholder default permissions [spot.read, spot.trade]',
    kind: 'ephemeral-artifact' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — VenueExchangeAdapter + readApiPermissions fallback',
    honestyRequirement: 'Hardcoded default permissions are NOT authoritative',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'ephemeral-in-memory-permission-on-connect',
    artifact: 'In-memory permission snapshot at connect time — not re-probed',
    kind: 'ephemeral-artifact' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Exists — written once on connect; no ongoing verification',
    honestyRequirement: 'Runtime permission cache is EPHEMERAL',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Dependencies ───────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'dep-consumes-authentication',
    artifact: 'Authentication — signed-in operators only',
    kind: 'dependency' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Wave 1 CLOSED — consumed',
    honestyRequirement: 'Fail closed on missing auth',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authorization',
    artifact: 'Authorization — role-gated permission probe surfaces',
    kind: 'dependency' as const,
    owner: 'authorization' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Wave 1 CLOSED — consumed',
    honestyRequirement: 'Unauthorized roles denied',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-workspace-isolation',
    artifact: 'Workspace Isolation — permission state scoped per workspace',
    kind: 'dependency' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Wave 1 CLOSED — consumed',
    honestyRequirement: 'Workspace A ↛ B permission state',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-secret-vault',
    artifact: 'Vault — credential retrieve for permission probe only',
    kind: 'dependency' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Wave 1 CLOSED — consumed',
    honestyRequirement: 'No local secret store; no plaintext echo',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-security-review.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-connection-management',
    artifact: 'Connection Management — operator permission visibility facade',
    kind: 'dependency' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Wave 2 COMPLETE — consumed not redesigned',
    honestyRequirement: 'Facade consumes permission labels; does not own probe I/O',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-exchange-scope-catalog',
    artifact: 'Exchange Scope / RC-27 — catalog venue labels (BINANCE/BYBIT/OKX/kraken)',
    kind: 'dependency' as const,
    owner: 'exchange-scope' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Exists — isolation boundary; kraken label-only',
    honestyRequirement: 'Catalog label ≠ permission verified',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-w4-e01-foundation',
    artifact: 'W4-E01 CLOSED — Binance exchange connectivity foundation',
    kind: 'dependency' as const,
    owner: 'w4-e01-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'CLOSED — consumed not reopened',
    honestyRequirement: 'Extend patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e01-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-w4-e02-foundation',
    artifact: 'W4-E02 CLOSED — Bybit exchange connectivity foundation',
    kind: 'dependency' as const,
    owner: 'w4-e02-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'CLOSED — consumed not reopened',
    honestyRequirement: 'Extend patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e02-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-w4-e03-foundation',
    artifact: 'W4-E03 CLOSED — OKX exchange connectivity foundation',
    kind: 'dependency' as const,
    owner: 'w4-e03-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'CLOSED — consumed not reopened',
    honestyRequirement: 'Extend patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e03-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-depends-on-w4-e04-foundation',
    artifact: 'W4-E04 CLOSED — Kraken exchange connectivity foundation',
    kind: 'dependency' as const,
    owner: 'w4-e04-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'CLOSED — consumed not reopened',
    honestyRequirement: 'Extend patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e04-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-no-vendor-permission-probe',
    artifact: 'Blocker — no real vendor permission probe I/O',
    kind: 'dependency' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active — hardcoded defaults only',
    honestyRequirement: 'Cannot claim permission verified without probe',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-hardcoded-defaults-presented',
    artifact: 'Blocker — hardcoded defaults may appear as operator-visible permissions',
    kind: 'dependency' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active — ExchangesPage shows stored apiPermissions',
    honestyRequirement: 'Hardcoded defaults are NOT authoritative',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'apps/web/src/pages/ExchangesPage.tsx',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-produces-vendor-permission-labels-target',
    artifact: 'Target — vendor-reported permission labels to Connection Management UI',
    kind: 'dependency' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'produces' as const,
    currentStatus: 'Not implemented — W4-E05-b target',
    honestyRequirement: 'Produce only after real vendor probe',
    futureW4E05Responsibility: 'W4-E05-b' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'dep-observed-by-cm04-health-monitoring',
    artifact: 'CM-04 Health Monitoring observes permission API (target)',
    kind: 'dependency' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    dependencyDirection: 'observed-by' as const,
    currentStatus: 'Waiting — CM-04 depends on E05 permission APIs',
    honestyRequirement: 'Health product blocked until E05-d',
    futureW4E05Responsibility: 'W4-E05-d' as const,
    evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Ownership ────────────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'own-exchange-adapter-factory',
    artifact: 'Exchange Adapter factory — venue protocol and permission probe I/O owner',
    kind: 'ownership' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified — factory extension only; no engine clone',
    honestyRequirement: 'Permission probe extends factory; no second engine',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-connection-management-facade',
    artifact: 'Connection Management — operator connect/permission visibility facade',
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified — consumes permission labels; does not own probe',
    honestyRequirement: 'No facade rewrite from E05-a',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-secret-vault',
    artifact: 'Vault — customer credential ciphertext owner',
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified — retrieve-only for probe signing',
    honestyRequirement: 'Vault owns secrets; adapter never stores plaintext',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-security-review.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'own-exchange-scope-isolation',
    artifact: 'Exchange Scope / Cluster — workspace isolation boundary',
    kind: 'ownership' as const,
    owner: 'exchange-scope' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Verified — RC-27 catalog; no cluster identity drift',
    honestyRequirement: 'Scope remains isolation boundary',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Honesty boundaries ─────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'honesty-vendor-reported-authoritative',
    artifact: 'Vendor-reported permissions are authoritative',
    kind: 'honesty-boundary' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding planning rule — target for W4-E05-b+',
    honestyRequirement: 'spot.trade from venue, not hardcoded apiPermissions',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/v3-security-vision.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-hardcoded-default-not-authoritative',
    artifact: 'Hardcoded default permissions are NOT authoritative',
    kind: 'honesty-boundary' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding — VenueExchangeAdapter + readApiPermissions fallback today',
    honestyRequirement: 'Never present [spot.read, spot.trade] defaults as vendor-verified',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-permission-verified-not-live-trading',
    artifact: 'Permission verified ≠ Live Trading',
    kind: 'honesty-boundary' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding — Wave 6 + ADR gate unchanged',
    honestyRequirement: 'Permission probe does not enable live orders',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-capability-probe-not-e05-complete',
    artifact: 'Per-venue capability probe during connect/test ≠ E05 Complete',
    kind: 'honesty-boundary' as const,
    owner: 'exchange-connectivity' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding — E01–E04 probes consumed; E05 is cross-venue product',
    honestyRequirement: 'Capability probe ≠ venue permission verification product',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-planning-summary.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w4-e01-foundation-consumed',
    artifact: 'W4-E01 CLOSED foundation consumed — not reopened',
    kind: 'honesty-boundary' as const,
    owner: 'w4-e01-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding',
    honestyRequirement: 'Extend E01-b/c/d patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e01-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w4-e02-foundation-consumed',
    artifact: 'W4-E02 CLOSED foundation consumed — not reopened',
    kind: 'honesty-boundary' as const,
    owner: 'w4-e02-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding',
    honestyRequirement: 'Extend E02-b/c/d patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e02-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w4-e03-foundation-consumed',
    artifact: 'W4-E03 CLOSED foundation consumed — not reopened',
    kind: 'honesty-boundary' as const,
    owner: 'w4-e03-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding',
    honestyRequirement: 'Extend E03-b/c/d patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e03-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w4-e04-foundation-consumed',
    artifact: 'W4-E04 CLOSED foundation consumed — not reopened',
    kind: 'honesty-boundary' as const,
    owner: 'w4-e04-foundation' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding',
    honestyRequirement: 'Extend E04-b/c/d patterns; do not duplicate owner',
    futureW4E05Responsibility: 'w4-e04-foundation-consumed' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e04-product-owner-close-record.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-e05-not-wave4-complete',
    artifact: 'W4-E05 ≠ Wave 4 COMPLETE; E05 ≠ Exchange Connectivity Complete',
    kind: 'honesty-boundary' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding',
    honestyRequirement: 'Package Close requires PO Completion Review after E05 Close',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-validation-plan.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-runtime-cache-ephemeral',
    artifact: 'Runtime permission cache is EPHEMERAL',
    kind: 'honesty-boundary' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding — in-memory adapter state; connect snapshot',
    honestyRequirement: 'Must not treat runtime cache as durable permission truth',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-a-venue-permission-inventory.md',
    existsToday: true,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-no-engine-clone-permission',
    artifact: 'No engine clone — permission probe extends factory only',
    kind: 'honesty-boundary' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'SURVIVE' as const,
    currentStatus: 'Binding — RC-27 factory extension',
    honestyRequirement: 'No second permission engine or order path',
    futureW4E05Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: true,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),

  // ── Explicit OUT ───────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'out-permission-probe-implementation-slice-a',
    artifact: 'Real vendor permission probe I/O implementation',
    kind: 'explicit-out' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W4-E05-a — inventory only',
    honestyRequirement: 'Probe I/O deferred to W4-E05-b',
    futureW4E05Responsibility: 'out-of-scope-permission-probe-io' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-persistence-implementation-slice-a',
    artifact: 'Durable permission verification persistence',
    kind: 'explicit-out' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W4-E05-a — planned W4-E05-b',
    honestyRequirement: 'Durable permission verification does not yet exist',
    futureW4E05Responsibility: 'out-of-scope-persistence-implementation' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-restart-recovery-slice-a',
    artifact: 'Permission restart recovery',
    kind: 'explicit-out' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W4-E05-a — planned W4-E05-c',
    honestyRequirement: 'Restart recovery does not yet exist',
    futureW4E05Responsibility: 'out-of-scope-restart-recovery' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-operational-continuity-slice-a',
    artifact: 'Permission operational continuity / CM-04 health projection',
    kind: 'explicit-out' as const,
    owner: 'operational-continuity' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W4-E05-a — planned W4-E05-d',
    honestyRequirement: 'Operational continuity does not yet exist',
    futureW4E05Responsibility: 'out-of-scope-operational-continuity' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-w4-e01-reopen',
    artifact: 'W4-E01 reopen / redesign',
    kind: 'explicit-out' as const,
    owner: 'w4-e01-foundation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — W4-E01 CLOSED; consume foundation only',
    honestyRequirement: 'Extend E01 patterns; do not duplicate owner',
    futureW4E05Responsibility: 'out-of-scope-w4-e01-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-w4-e02-reopen',
    artifact: 'W4-E02 reopen / redesign',
    kind: 'explicit-out' as const,
    owner: 'w4-e02-foundation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — W4-E02 CLOSED; consume foundation only',
    honestyRequirement: 'Extend E02 patterns; do not duplicate owner',
    futureW4E05Responsibility: 'out-of-scope-w4-e02-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-w4-e03-reopen',
    artifact: 'W4-E03 reopen / redesign',
    kind: 'explicit-out' as const,
    owner: 'w4-e03-foundation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — W4-E03 CLOSED; consume foundation only',
    honestyRequirement: 'Extend E03 patterns; do not duplicate owner',
    futureW4E05Responsibility: 'out-of-scope-w4-e03-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-w4-e04-reopen',
    artifact: 'W4-E04 reopen / redesign',
    kind: 'explicit-out' as const,
    owner: 'w4-e04-foundation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — W4-E04 CLOSED; consume foundation only',
    honestyRequirement: 'Extend E04 patterns; do not duplicate owner',
    futureW4E05Responsibility: 'out-of-scope-w4-e04-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-engine-clone-permission',
    artifact: 'Engine clone / second permission subsystem',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — architecture invariant',
    honestyRequirement: 'Factory extension only',
    futureW4E05Responsibility: 'out-of-scope-engine-clone' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-implementation-package.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading / live order submission (Wave 6)',
    kind: 'explicit-out' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Out of W4-E05 paper scope',
    honestyRequirement: 'Permission verified ≠ live capital orders',
    futureW4E05Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-product-scope.md',
    existsToday: false,
    isPaperProduct: false,
    authorizesVenuePermissionVerificationComplete: false,
  }),
  Object.freeze({
    artifactId: 'out-venue-permission-complete-from-slice-a',
    artifact: 'Venue Permission Verification Complete from inventory alone',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    currentStatus: 'Forbidden — inventory ≠ product Complete',
    honestyRequirement: 'Slice a is discovery only',
    futureW4E05Responsibility: 'W4-E05-e' as const,
    evidencePath: 'docs/project/version-3/wave-4/w4-e05-validation-plan.md',
    existsToday: false,
    isPaperProduct: true,
    authorizesVenuePermissionVerificationComplete: false,
  }),
]);

export const W4_E05_A_BINDING_FINDINGS = Object.freeze({
  venuePermissionVerificationCompleteAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  venuePermissionVerificationSurvivesRestartAfterSliceA: false,
  vendorReportedPermissionsAuthoritative: true,
  hardcodedDefaultPermissionsNotAuthoritative: true,
  runtimePermissionCacheEphemeral: true,
  durablePermissionVerificationDoesNotExist: true,
  restartRecoveryDoesNotExist: true,
  operationalContinuityDoesNotExist: true,
  noCustomerVisiblePermissionVerification: true,
  w4E01FoundationConsumedNotRedesigned: true,
  w4E02FoundationConsumedNotRedesigned: true,
  w4E03FoundationConsumedNotRedesigned: true,
  w4E04FoundationConsumedNotRedesigned: true,
  honestPermissionProductRulesFrozen: true,
} as const);

export const W4_E05_A_EXPLICIT_OUT = Object.freeze([
  'permission-probe-implementation',
  'persistence-implementation',
  'restart-recovery',
  'operational-continuity',
  'new-persistence-owner',
  'new-bounded-context',
  'new-source-of-truth',
  'engine-clone',
  'live-trading-enablement',
  'w4-e01-reopen',
  'w4-e02-reopen',
  'w4-e03-reopen',
  'w4-e04-reopen',
  'w4-e05-b',
  'w4-e05-c',
  'w4-e05-d',
  'w4-e05-e',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'venue-permission-verification-complete',
  'exchange-connectivity-complete',
  'wave-4-complete',
] as const);

export const W4_E05_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateExchangeSubsystem: false,
  duplicatePermissionSubsystem: false,
  engineClonePerVenue: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  w4E01Reopened: false,
  w4E02Reopened: false,
  w4E03Reopened: false,
  w4E04Reopened: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  venuePermissionVerificationCompleteClaimed: false,
  exchangeConnectivityCompleteClaimed: false,
  liveTradingClaimed: false,
  wave4CompleteClaimed: false,
  customerVisibleFeature: false,
  venuePermissionVerificationSurvivesRestart: false,
} as const);

export function artifactIds(): readonly string[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W4E05AArtifactKind): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsDependencies(
  direction: W4E05ADependencyDirection,
): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter(
    (row) => row.kind === 'dependency' && row.dependencyDirection === direction,
  );
}

export function rowsPaperProduct(): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.isPaperProduct);
}

export function rowsExplicitOut(): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsHonestyBoundaries(): readonly W4E05AInventoryRow[] {
  return W4_E05_A_VENUE_PERMISSION_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsVenuePermissionSurvive(): readonly W4E05AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'w4-e01-foundation',
      'w4-e02-foundation',
      'w4-e03-foundation',
      'w4-e04-foundation',
      'authentication',
      'authorization',
      'workspace-isolation',
      'release-governance',
      'wave-4-documentation',
    ].includes(row.owner),
  );
}

export function rowsVenuePermissionEphemeral(): readonly W4E05AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'operational-continuity',
      'live-trading-deferred',
    ].includes(row.owner),
  );
}
