/**
 * W4-E03-a — Inventory & Exchange Connectivity Baseline (OKX / CM-09).
 *
 * Discovery and classification only.
 * Not exchange connectivity implementation. Not REST implementation.
 * Not WebSocket implementation. Not persistence. Not restart recovery.
 * Not operational continuity. Not Exchange Connectivity Complete. Not W4-E03 CLOSED.
 *
 * Capability label CM-09 is inventory vocabulary only —
 * not authorization to invent an engine clone or second order path.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Vault / Connection / Exchange Adapter / Scope owners.
 * - EPHEMERAL: artifact is transient, stub, simulated, planned-not-implemented,
 *   UI-only, process-local, or missing — must not be treated as durable truth.
 */

export const W4_E03_A_SLICE_ID = 'W4-E03-a' as const;

export const W4_E03_A_ALLOWED_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
  'market-data-foundation',
  'live-market-data',
  'security-platform',
  'security-audit',
  'authentication',
  'authorization',
  'workspace-isolation',
  'operational-continuity',
  'command-center',
  'release-governance',
  'wave-4-documentation',
  'w4-e01-foundation',
  'live-trading-deferred',
  'live-trading-engine',
  'wave-5-deferred',
  'wave-6-deferred',
  'w4-e02-foundation',
  'kraken-deferred',
  'venue-permission-deferred',
] as const);

export type W4E03AOwner = (typeof W4_E03_A_ALLOWED_OWNERS)[number];

/** Existing exchange connectivity substrate owners — no new owner. */
export const W4_E03_A_SUBSTRATE_OWNERS = Object.freeze([
  'exchange-adapter',
  'exchange-connectivity',
  'connection-management',
  'secret-vault',
  'exchange-scope',
] as const);

export const W4_E03_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W4E03AArtifactKind = (typeof W4_E03_A_ARTIFACT_KINDS)[number];

export const W4_E03_A_REQUIRED_ARTIFACT_KINDS = W4_E03_A_ARTIFACT_KINDS;

export const W4_E03_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W4E03ADurabilityClass = (typeof W4_E03_A_DURABILITY_CLASSES)[number];

export const W4_E03_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W4E03ADependencyDirection = (typeof W4_E03_A_DEPENDENCY_DIRECTIONS)[number];

export const W4_E03_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W4-E03-b',
  'W4-E03-c',
  'W4-E03-d',
  'W4-E03-e',
  'honesty-baseline',
  'w4-e01-foundation-consumed',
  'w4-e02-foundation-consumed',
  'out-of-scope-w4-e01-reopen',
  'out-of-scope-w4-e02-reopen',
  'out-of-scope-w4-e04',
  'out-of-scope-w4-e05',
  'out-of-scope-live-trading',
  'out-of-scope-rest-implementation',
  'out-of-scope-websocket-implementation',
  'out-of-scope-engine-clone',
  'out-of-scope-market-data-only',
] as const);

export type W4E03AFutureResponsibility = (typeof W4_E03_A_FUTURE_RESPONSIBILITIES)[number];

export type W4E03AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W4E03AArtifactKind;
  owner: W4E03AOwner;
  durabilityClass: W4E03ADurabilityClass;
  dependencyDirection?: W4E03ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW4E03Responsibility: W4E03AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  isPaperProduct: boolean;
  authorizesExchangeConnectivityComplete: boolean;
}>;

/**
 * Frozen inventory of OKX exchange REST/WS surfaces, authentication artifacts,
 * connection lifecycle, runtime/durable/ephemeral state, operator-visible
 * artifacts, security/platform dependencies, ownership, and honesty boundaries.
 */
export const W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY: readonly W4E03AInventoryRow[] =
  Object.freeze([
    // ── Exchange REST endpoints (commands) ───────────────────────────────────
    Object.freeze({
      artifactId: 'rest-okx-planned-handshake',
      artifact: 'PlannedExchangeHandshakeAdapter(OKX) — Connection Management validate path',
      kind: 'command' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Implemented — returns not_implemented; validate fails before vault retrieve for OKX',
      honestyRequirement: 'Planned handshake ≠ OKX Connected; real signed REST is W4-E03-b+ target',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/planned-handshake.adapter.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-okx-planned-capability',
      artifact: 'PlannedExchangeCapabilityAdapter(OKX) — capability probe',
      kind: 'command' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Implemented — returns not_implemented',
      honestyRequirement: 'Capability probe ≠ venue permission verification product (E05)',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/planned-capability.adapter.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-okx-v5-api-handshake-target',
      artifact: 'OKX V5 REST — account/permission or equivalent handshake (target)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no okx-handshake.adapter.ts; not implemented',
      honestyRequirement: 'Missing vendor REST must not be faked as Connected',
      futureW4E03Responsibility: 'out-of-scope-rest-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connections-validate-okx',
      artifact: 'POST /v1/connections/:id/validate — operator test (OKX provider)',
      kind: 'command' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus:
        'Implemented — routes to ExchangeHandshakeService; OKX fails at planned adapter',
      honestyRequirement: 'Validate endpoint exists; OKX cannot reach Connected without real I/O',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/connections/connections.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connections-disconnect-okx',
      artifact: 'POST /v1/connections/:id/disconnect — operator disconnect (OKX)',
      kind: 'command' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — lifecycle status transition; no vendor disconnect call today',
      honestyRequirement: 'Disconnect updates product state; vendor teardown is W4-E03-b',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connections.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-exchanges-connect-okx',
      artifact: 'POST /v1/exchanges/connect — Exchange Adapter factory connect (OKX)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Implemented — uses stub OkxExchangeAdapter; simulated connect only',
      honestyRequirement: 'Simulated connect forbidden as honest Connected; W4-E03-b target',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-adapter.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-exchanges-disconnect-okx',
      artifact: 'POST /v1/exchanges/disconnect — Exchange Adapter factory disconnect (OKX)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Implemented — clears in-memory connected flag on stub adapter',
      honestyRequirement: 'Factory disconnect ≠ Connection Management disconnect product alone',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-adapter.controller.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'rest-market-data-public-okx',
      artifact: 'Market Data Foundation — public OKX REST (planned symbol discovery)',
      kind: 'command' as const,
      owner: 'market-data-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Planned — PlannedSymbolDiscoveryAdapter(OKX) returns not implemented',
      honestyRequirement: 'Public market data ≠ credentialed connect/test/disconnect Complete',
      futureW4E03Responsibility: 'out-of-scope-market-data-only' as const,
      evidencePath: 'apps/api/src/modules/market-data-foundation/planned-symbol.adapter.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Exchange WebSocket streams ───────────────────────────────────────────
    Object.freeze({
      artifactId: 'ws-okx-public-stream',
      artifact: 'OKX public WebSocket market streams',
      kind: 'command' as const,
      owner: 'live-market-data' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no OKX public WS connector in live-market-data',
      honestyRequirement: 'Public WS ≠ authenticated user-data stream; ≠ W4-E03 credentialed I/O',
      futureW4E03Responsibility: 'out-of-scope-market-data-only' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ws-okx-adapter-subscribe-stubs',
      artifact: 'OkxExchangeAdapter subscribeTicker/OrderUpdates/ExecutionUpdates — noop stubs',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Stub — inherits VenueExchangeAdapter noop subscriptions',
      honestyRequirement: 'Noop WS hooks must not imply WebSocket Complete or Connected',
      futureW4E03Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ws-okx-authenticated-user-data',
      artifact: 'OKX authenticated private WebSocket (orders/account)',
      kind: 'command' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — not implemented',
      honestyRequirement: 'Missing authenticated WS must not be faked; out of W4-E03-a scope',
      futureW4E03Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Exchange authentication artifacts ────────────────────────────────────
    Object.freeze({
      artifactId: 'auth-vault-okx-secret-type',
      artifact: 'HoldableSecretType.Okx — vault credential classification',
      kind: 'state' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — apiKey/apiSecret/passphrase schema; ciphertext in vault store',
      honestyRequirement: 'Vault remains sole credential owner; adapter retrieves only',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-connection-vault-mapping-okx',
      artifact: 'Connection vault mapping OKX → HoldableSecretType.Okx',
      kind: 'runtime' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — write-only credential store path',
      honestyRequirement: 'Credentials never echoed plaintext; fail closed on missing vault',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-vault.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-handshake-vault-retrieve-okx',
      artifact: 'ExchangeHandshakeService vault retrieve before OKX signed REST',
      kind: 'runtime' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Not reached for OKX — planned adapter fails before vault retrieve',
      honestyRequirement: 'When implemented, signing inside handshake/adapter boundary only',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-handshake.service.ts',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'auth-okx-request-signing',
      artifact: 'OKX REST request signing with apiKey, secret, and passphrase',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing — no OKX signing client in exchange-adapter or handshake',
      honestyRequirement: 'Real signing required for honest Connected at Close',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Connection lifecycle ─────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'lifecycle-connection-record-okx',
      artifact: 'ConnectionRecord — operator OKX connection metadata and status',
      kind: 'state' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Persisted — Prisma connection_records with provider OKX; survives restart',
      honestyRequirement:
        'Durable status must reflect real vendor round-trip at Close; stub forbidden',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/prisma/schema.prisma',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-connection-transitions-okx',
      artifact: 'connection-lifecycle.ts — legal status transitions for OKX connections',
      kind: 'runtime' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — fail closed transition rules (provider-agnostic)',
      honestyRequirement: 'CONNECTED transition requires validation evidence; no fake Connected',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-connection-model-okx',
      artifact: 'ExchangeConnection — adapter-layer OKX connection persistence',
      kind: 'state' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Persisted — exchange_connections table; may reflect stub connect today',
      honestyRequirement: 'Two connection models must not drift; factory extension only',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/prisma-exchange-adapter.repository.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-manager-okx',
      artifact: 'ExchangeManager — OKX adapter connect/disconnect orchestration',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Implemented — calls stub OkxExchangeAdapter.connect(); persists row',
      honestyRequirement:
        'Manager must not mark Connected without vendor round-trip after W4-E03-b',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-manager.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'lifecycle-exchange-session-projection-okx',
      artifact: 'ExchangeSessionView — session health after OKX handshake attempt',
      kind: 'projection' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Computed — OKX validate yields VALIDATION_FAILED from planned adapter',
      honestyRequirement: 'Session projection ≠ adapter factory Connected; consume both honestly',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-session.health.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Runtime state ────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'runtime-okx-adapter-stub-connected-flag',
      artifact: 'OkxExchangeAdapter in-memory connected flag (simulated connect)',
      kind: 'ephemeral-artifact' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Process-local boolean — set true without network I/O',
      honestyRequirement: 'Simulated connected flag is honesty violation if shown as Connected',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-exchange-registry-okx',
      artifact: 'ExchangeRegistry — in-memory OKX adapter instances per workspace',
      kind: 'ephemeral-artifact' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'In-process registry — rebuilt on API restart',
      honestyRequirement: 'Registry loss on restart; continuity is W4-E03-d not this slice',
      futureW4E03Responsibility: 'W4-E03-d' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-registry.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-exchange-factory-okx',
      artifact: 'ExchangeFactory.create(OKX) → OkxExchangeAdapter stub',
      kind: 'runtime' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Implemented — US209 stub; W4-E03 primary extension point',
      honestyRequirement: 'Factory must extend stub to vault-backed real I/O; no engine clone',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/exchange-factory.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-okx-exchange-id',
      artifact: "ExchangeId 'OKX' — catalog and factory registration",
      kind: 'state' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — EXCHANGE_IDS includes OKX',
      honestyRequirement: 'Catalog presence ≠ Connected; stub adapter registered',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/domain/exchange-id.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Durable state candidates ─────────────────────────────────────────────
    Object.freeze({
      artifactId: 'persist-vault-ciphertext-okx',
      artifact: 'Vault ciphertext store — authoritative OKX credential persistence',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Exists — Wave 1 closed; survives restart',
      honestyRequirement: 'Vault is credential SoT; W4-E03 must not duplicate',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/secret-vault.service.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-connection-records-okx',
      artifact: 'connection_records — Connection Management durable OKX metadata',
      kind: 'persistence-candidate' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Exists — operator connection product state',
      honestyRequirement: 'Status column must stay honest post W4-E03-b real round-trip',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/prisma/schema.prisma',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-exchange-connections-okx',
      artifact: 'exchange_connections — Exchange Adapter layer OKX persistence',
      kind: 'persistence-candidate' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Exists — adapter connection rows; may reflect stub connect today',
      honestyRequirement: 'No new persistence owner; extend existing tables only',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/prisma-exchange-adapter.repository.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'persist-okx-connection-continuity',
      artifact: 'OKX connection continuity / restart recovery durable anchors',
      kind: 'persistence-candidate' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus:
        'Missing — no prisma-okx-exchange-connectivity-state.repository.ts; W4-E03-b target',
      honestyRequirement:
        'No OKX continuity substrate today; extend W4-E01/E02 patterns in W4-E03-b; no synthetic Connected',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Operator-visible artifacts ───────────────────────────────────────────
    Object.freeze({
      artifactId: 'ui-connections-page-okx',
      artifact: 'ConnectionsPage — OKX provider validate/disconnect UX',
      kind: 'operator-visible' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Routed paper product — OKX in catalog; validate fails at planned adapter',
      honestyRequirement: 'Connected label must require real round-trip; no simulation in UI',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/web/src/connections/ConnectionsPage.tsx',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-web-validate-connection-client-okx',
      artifact: 'Web validateConnection API client (OKX provider)',
      kind: 'operator-visible' as const,
      owner: 'command-center' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Client exists — calls POST /v1/connections/:id/validate',
      honestyRequirement: 'Client alone ≠ OKX Connected Complete',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/web/src/shared/api.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-honest-connected-label-okx',
      artifact: 'Honest Connected / Error / Expired / permission labels for OKX',
      kind: 'operator-visible' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Missing/partial — planned adapter failure only; full honesty rules W4-E03-b+',
      honestyRequirement: 'Never Connected without vendor evidence; paper default preserved',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-overview.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'ui-exchange-scope-okx-catalog',
      artifact: 'Exchange Scope PC-12 — OKX venue catalog (liveAdapter: false)',
      kind: 'operator-visible' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Implemented — offered: true; liveAdapter: false; venueApiUsed: false',
      honestyRequirement: 'Scope catalog honesty — no live adapter claim for OKX',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope-product/exchange-scope.view.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Platform Readiness dependencies ──────────────────────────────────────
    Object.freeze({
      artifactId: 'dep-platform-readiness-exchange-connectivity',
      artifact: 'Platform Readiness exchangeConnectivity view — aggregate continuity',
      kind: 'dependency' as const,
      owner: 'operational-continuity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — W4-E01-d aggregate projection; no OKX-specific continuity row',
      honestyRequirement: 'Continuity ≠ Connected; OKX-scoped projection is W4-E03-d',
      futureW4E03Responsibility: 'W4-E03-d' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-security-platform-okx',
      artifact: 'Security Platform — rate limits and hardening defaults for connect surfaces',
      kind: 'dependency' as const,
      owner: 'security-platform' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed defaults; no OKX-specific fork',
      honestyRequirement: 'Reuse platform controls; no second security product',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Security dependencies ────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'dep-consumes-authentication-okx',
      artifact: 'Authentication — signed-in operator for OKX connect/test/disconnect',
      kind: 'dependency' as const,
      owner: 'authentication' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed when missing',
      honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authorization-okx',
      artifact: 'Authorization — permitted roles for OKX connection surfaces',
      kind: 'dependency' as const,
      owner: 'authorization' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — connect/test requires permitted role',
      honestyRequirement: 'Unauthorized deny; no new IAM',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-workspace-isolation-okx',
      artifact: 'Workspace Isolation — A↛B OKX credentials and connection state',
      kind: 'dependency' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — cross-workspace deny required at Close',
      honestyRequirement: 'Foreign workspace must not connect/test with B credentials',
      futureW4E03Responsibility: 'W4-E03-e' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-security-review.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-security-audit-okx',
      artifact: 'Security Audit — OKX connect/test/disconnect attribution events',
      kind: 'dependency' as const,
      owner: 'security-audit' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — lifecycle audit on connections (provider-agnostic)',
      honestyRequirement: 'Emit required outcomes; do not own audit store',
      futureW4E03Responsibility: 'W4-E03-e' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle-audit.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-produces-connection-audit-events-okx',
      artifact: 'Connection lifecycle audit — produces OKX connect/test/disconnect audit events',
      kind: 'dependency' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'produces' as const,
      currentStatus: 'Implemented — emits to Security Audit store on lifecycle transitions',
      honestyRequirement:
        'Audit events are attribution inputs; Connection Management does not own audit store',
      futureW4E03Responsibility: 'W4-E03-e' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-lifecycle-audit.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-planned-handshake',
      artifact: 'PlannedExchangeHandshakeAdapter blocks honest OKX Connected on validate',
      kind: 'dependency' as const,
      owner: 'exchange-connectivity' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — not_implemented before vault retrieve',
      honestyRequirement: 'W4-E03-b must replace planned adapter with real round-trip',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-connectivity/exchange-handshake.service.spec.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-stub-adapter-okx',
      artifact: 'Stub OkxExchangeAdapter blocks honest factory Connected',
      kind: 'dependency' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active blocker — simulated connect without vault/vendor I/O',
      honestyRequirement: 'W4-E03-b must replace stub connect with real round-trip',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Platform / W4-E01 foundation dependencies ────────────────────────────
    Object.freeze({
      artifactId: 'dep-depends-on-w2-connection-management-okx',
      artifact: 'W2 Connection Management — CLOSED predecessor facade (OKX in catalog)',
      kind: 'dependency' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — consumed; not redesigned',
      honestyRequirement:
        'Connection Management owns operator surface; W4-E03 extends adapter only',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-2/connection-management-overview.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-w4-e01-foundation',
      artifact: 'W4-E01 CLOSED foundation — durable/recovery/continuity patterns consumed',
      kind: 'dependency' as const,
      owner: 'w4-e01-foundation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — extend for OKX venue scope; do not reopen or redesign',
      honestyRequirement: 'W4-E01-b/c/d artifacts consumed; OKX extension in W4-E03-b/c/d',
      futureW4E03Responsibility: 'w4-e01-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-w4-e02-foundation',
      artifact: 'W4-E02 CLOSED foundation — Bybit patterns consumed for OKX extension',
      kind: 'dependency' as const,
      owner: 'w4-e02-foundation' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'CLOSED — extend W4-E02-b/c/d patterns for OKX venue scope; do not reopen',
      honestyRequirement: 'W4-E02 foundation consumed; OKX extension in W4-E03-b/c/d',
      futureW4E03Responsibility: 'w4-e02-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-depends-on-exchange-scope-okx',
      artifact: 'Exchange Scope RC-27 — okx venue code isolation boundary',
      kind: 'dependency' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: "Exists — venue code 'okx' registrable; liveAdapter: false",
      honestyRequirement: 'Exchange Scope remains isolation SoT; adapter must not redefine cluster',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope/domain/exchange-scope-domain-shared.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'dep-observed-by-live-trading-engine-okx',
      artifact: 'Live Trading Engine consumes ExchangeAdapterService.connect (OKX stub)',
      kind: 'dependency' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Live-only consumer of stub adapter — out of paper W4-E03 scope',
      honestyRequirement: 'Live path ≠ paper Connected honesty; Wave 6 gate unchanged',
      futureW4E03Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'apps/api/src/modules/live-trading-engine/connection-supervisor.ts',
      existsToday: true,
      isPaperProduct: false,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Operational ──────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'op-cm09-capability-inventory',
      artifact: 'CM-09 OKX connectivity capability — inventory entry',
      kind: 'operational' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Named — 25% readiness; W4-E03 productization target',
      honestyRequirement: 'CM-09 label ≠ OKX Real I/O Complete until package Close',
      futureW4E03Responsibility: 'W4-E03-e' as const,
      evidencePath: 'docs/project/version-3/v3-capability-inventory.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'op-w4-e03-planning-approved',
      artifact: 'W4-E03 Planning Package — APPROVED; W4-E03-a inventory in progress',
      kind: 'operational' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Planning APPROVED — slice a inventory only',
      honestyRequirement: 'Planning Approval ≠ Exchange Connectivity Complete',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-planning-approval.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Ownership surfaces ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'own-exchange-adapter-factory-okx',
      artifact: 'Exchange Adapter factory — OKX venue protocol I/O owner (extend only)',
      kind: 'ownership' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — W4-E03 extends stub; no engine clone',
      honestyRequirement: 'Factory extension only; no second order path',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-connection-management-facade-okx',
      artifact: 'Connection Management — operator OKX connect/test/disconnect facade',
      kind: 'ownership' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — Wave 2 COMPLETE; consume not redesign',
      honestyRequirement: 'Facade owns operator product surface; adapter owns protocol I/O',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-secret-vault-credentials-okx',
      artifact: 'Vault — OKX customer secret ciphertext owner',
      kind: 'ownership' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — retrieve-only for adapter I/O',
      honestyRequirement: 'No local secret store; no plaintext echo',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'own-exchange-scope-isolation-okx',
      artifact: 'Exchange Scope / Cluster — OKX isolation boundary owner (RC-27)',
      kind: 'ownership' as const,
      owner: 'exchange-scope' as const,
      durabilityClass: 'SURVIVE' as const,
      currentStatus: 'Verified existing owner — not transport or credentials',
      honestyRequirement: 'Exchange Scope remains isolation SoT; adapter consumes scope id',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/exchange-scope/README.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Honesty boundaries ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'honesty-connected-not-live-trading-okx',
      artifact: 'Connected ≠ Live Trading; Connected ≠ live order submission (OKX)',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — frozen in inventory',
      honestyRequirement: 'Paper remains default; Wave 6 gate unchanged',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-overview.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-connected-requires-round-trip-okx',
      artifact: 'Connected requires real OKX vendor round-trip with vault credentials',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — stub adapter and planned handshake violate today; W4-E03-b fixes',
      honestyRequirement: 'Simulated CONNECTED without keys forbidden',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-planned-handshake-not-connected',
      artifact: 'Planned handshake not_implemented ≠ OKX Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — validate fails for OKX today; must not show Connected',
      honestyRequirement: 'Credential collection alone ≠ Connected',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-factory-stub-not-connected',
      artifact: 'Stub OkxExchangeAdapter simulated connect ≠ Connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — factory path simulates connect without vendor I/O',
      honestyRequirement: 'Factory extension must replace stub with real round-trip',
      futureW4E03Responsibility: 'W4-E03-b' as const,
      evidencePath: 'apps/api/src/modules/exchange-adapter/adapters/venue.adapters.ts',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w4-e01-foundation-consumed',
      artifact: 'W4-E01 CLOSED foundation consumed — not reopened for OKX',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — extend W4-E01-b/c/d patterns for OKX scope only',
      honestyRequirement: 'No W4-E01 redesign; no duplicate persistence owner',
      futureW4E03Responsibility: 'w4-e01-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e01-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w4-e02-foundation-consumed',
      artifact: 'W4-E02 CLOSED foundation consumed — not reopened for OKX',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — extend W4-E02-b/c/d patterns for OKX scope only',
      honestyRequirement: 'No W4-E02 redesign; no duplicate persistence owner',
      futureW4E03Responsibility: 'w4-e02-foundation-consumed' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e02-product-owner-close-record.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-e03-not-wave4-complete',
      artifact: 'W4-E03 ≠ Wave 4 COMPLETE; E03 ≠ Kraken connected',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding — E03–E05 sequenced separately',
      honestyRequirement: 'OKX-only scope; no catalog venue Complete claims',
      futureW4E03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-4/wave-4-progress.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-no-engine-clone-okx',
      artifact: 'No engine clone per venue; OKX factory extension only',
      kind: 'honesty-boundary' as const,
      owner: 'wave-4-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Binding architecture invariant',
      honestyRequirement: 'Single Exchange Adapter factory; Exchange Scope isolation boundary',
      futureW4E03Responsibility: 'out-of-scope-engine-clone' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: true,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),

    // ── Explicit OUT ─────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'out-rest-implementation-slice-a',
      artifact: 'REST implementation in W4-E03-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — inventory only; W4-E03-b+ implements real adapter REST',
      honestyRequirement: 'Slice a catalogues endpoints; does not implement them',
      futureW4E03Responsibility: 'out-of-scope-rest-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-websocket-implementation-slice-a',
      artifact: 'WebSocket implementation in W4-E03-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — inventory only',
      honestyRequirement: 'Authenticated WS deferred beyond slice a',
      futureW4E03Responsibility: 'out-of-scope-websocket-implementation' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-w4-e01-reopen',
      artifact: 'W4-E01 reopen / redesign for OKX',
      kind: 'explicit-out' as const,
      owner: 'w4-e01-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — W4-E01 CLOSED; consume foundation only',
      honestyRequirement: 'Extend W4-E01-b/c/d patterns; do not duplicate owner',
      futureW4E03Responsibility: 'out-of-scope-w4-e01-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-w4-e02-reopen',
      artifact: 'W4-E02 reopen / redesign for OKX',
      kind: 'explicit-out' as const,
      owner: 'w4-e02-foundation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — W4-E02 CLOSED; consume foundation only',
      honestyRequirement: 'Extend W4-E02-b/c/d patterns; do not duplicate owner',
      futureW4E03Responsibility: 'out-of-scope-w4-e02-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-engine-clone-per-venue',
      artifact: 'Engine clone per venue / second Canonical Order Path',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Forbidden — architecture invariant',
      honestyRequirement: 'Factory extension only',
      futureW4E03Responsibility: 'out-of-scope-engine-clone' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-implementation-package.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-live-trading-wave6',
      artifact: 'Live Trading / live order submission (Wave 6)',
      kind: 'explicit-out' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Out of W4-E03 paper scope',
      honestyRequirement: 'Connect/test ≠ live capital orders',
      futureW4E03Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: false,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-kraken-e04',
      artifact: 'Kraken real I/O (V3-E04)',
      kind: 'explicit-out' as const,
      owner: 'kraken-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Out of W4-E03 — W4-E04 sequenced separately',
      honestyRequirement: 'OKX-only inventory baseline',
      futureW4E03Responsibility: 'out-of-scope-w4-e04' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
    Object.freeze({
      artifactId: 'out-venue-permission-product-e05',
      artifact: 'Venue permission verification product (V3-E05)',
      kind: 'explicit-out' as const,
      owner: 'venue-permission-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      currentStatus: 'Out of W4-E03 — E05 sequenced later',
      honestyRequirement: 'Capability probe ≠ E05 Complete',
      futureW4E03Responsibility: 'out-of-scope-w4-e05' as const,
      evidencePath: 'docs/project/version-3/wave-4/w4-e03-product-scope.md',
      existsToday: false,
      isPaperProduct: true,
      authorizesExchangeConnectivityComplete: false,
    }),
  ]);

export const W4_E03_A_BINDING_FINDINGS = Object.freeze({
  exchangeConnectivityCompleteAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  exchangeConnectivitySurvivesRestartAfterSliceA: false,
  okxAdapterRealIoExists: false,
  okxHandshakeRealIoExists: false,
  plannedHandshakeNotImplementedExists: true,
  stubAdapterSimulatedConnectExists: true,
  w4E01FoundationConsumedNotRedesigned: true,
  w4E02FoundationConsumedNotRedesigned: true,
  honestConnectedProductRulesFrozen: true,
  publicMarketDataSeparateFromCredentialedIo: true,
} as const);

export const W4_E03_A_EXPLICIT_OUT = Object.freeze([
  'rest-implementation',
  'websocket-implementation',
  'persistence-implementation',
  'restart-recovery',
  'operational-continuity',
  'new-persistence-owner',
  'new-bounded-context',
  'new-source-of-truth',
  'engine-clone',
  'live-trading-enablement',
  'w4-e01-reopen',
  'w4-e02-reopen',
  'w4-e03-b',
  'w4-e03-c',
  'w4-e03-d',
  'w4-e03-e',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'exchange-connectivity-complete',
  'okx-connected',
] as const);

export const W4_E03_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateExchangeSubsystem: false,
  engineClonePerVenue: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  w4E01Reopened: false,
  w4E02Reopened: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  exchangeConnectivityCompleteClaimed: false,
  okxRealIoCompleteClaimed: false,
  liveTradingClaimed: false,
  wave4CompleteClaimed: false,
  customerVisibleFeature: false,
  exchangeConnectivitySurvivesRestart: false,
} as const);

export function artifactIds(): readonly string[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W4E03AArtifactKind): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.durabilityClass === 'SURVIVE',
  );
}

export function rowsEphemeral(): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.durabilityClass === 'EPHEMERAL',
  );
}

export function rowsDependencies(
  direction: W4E03ADependencyDirection,
): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter(
    (row) => row.kind === 'dependency' && row.dependencyDirection === direction,
  );
}

export function rowsPaperProduct(): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.isPaperProduct);
}

export function rowsExplicitOut(): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsHonestyBoundaries(): readonly W4E03AInventoryRow[] {
  return W4_E03_A_EXCHANGE_CONNECTIVITY_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExchangeConnectivitySurvive(): readonly W4E03AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'w4-e01-foundation',
      'w4-e02-foundation',
    ].includes(row.owner),
  );
}

export function rowsExchangeConnectivityEphemeral(): readonly W4E03AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    [
      'exchange-adapter',
      'exchange-connectivity',
      'connection-management',
      'secret-vault',
      'exchange-scope',
      'live-trading-deferred',
      'live-trading-engine',
      'operational-continuity',
    ].includes(row.owner),
  );
}
