/**
 * W5-N01-a — Telegram Notification Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Bot API implementation. Not outbound production notifications.
 * Not runtime delivery to api.telegram.org. Not W5-N01 COMPLETE. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Notification Delivery / Vault / Connection / Queue owners.
 * - EPHEMERAL: artifact is transient, stub, in-memory transport, UI-only,
 *   process-local, or missing — must not be treated as production Telegram truth.
 */

export const W5_N01_A_SLICE_ID = 'W5-N01-a' as const;

export const W5_N01_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'telegram-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n02-deferred',
  'w5-n03-deferred',
  'w5-n04-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N01AOwner = (typeof W5_N01_A_ALLOWED_OWNERS)[number];

/** Existing notification / Telegram substrate owners — no new owner. */
export const W5_N01_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'telegram-product',
  'connection-management',
  'secret-vault',
] as const);

export const W5_N01_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N01AArtifactKind = (typeof W5_N01_A_ARTIFACT_KINDS)[number];

export const W5_N01_A_REQUIRED_ARTIFACT_KINDS = W5_N01_A_ARTIFACT_KINDS;

export const W5_N01_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N01ACapabilityCategory = (typeof W5_N01_A_CAPABILITY_CATEGORIES)[number];

export const W5_N01_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N01ADurabilityClass = (typeof W5_N01_A_DURABILITY_CLASSES)[number];

export const W5_N01_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N01ADependencyDirection = (typeof W5_N01_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N01_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N01-b',
  'W5-N01-c',
  'W5-N01-d',
  'W5-N01-e',
  'honesty-baseline',
  'out-of-scope-w5-n02',
  'out-of-scope-w5-n03',
  'out-of-scope-w5-n04',
  'out-of-scope-live-trading',
  'out-of-scope-bot-api-slice-a',
  'out-of-scope-telegram-control-plane',
  'out-of-scope-exchange-adapter',
  'out-of-scope-message-templates',
  'out-of-scope-w5-n01-complete',
  'out-of-scope-wave-5-complete',
] as const);

export type W5N01AFutureResponsibility = (typeof W5_N01_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N01AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N01AArtifactKind;
  owner: W5N01AOwner;
  durabilityClass: W5N01ADurabilityClass;
  capabilityCategory: W5N01ACapabilityCategory;
  dependencyDirection?: W5N01ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N01Responsibility: W5N01AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesTelegramRealDelivery: boolean;
  authorizesW5N01Complete: boolean;
}>;

/**
 * Frozen inventory of Telegram transport surfaces, notification delivery paths,
 * vault/connection substrates, operator-visible artifacts, platform dependencies,
 * ownership boundaries, and honesty rules for Wave 5 slice a.
 */
export const W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY: readonly W5N01AInventoryRow[] =
  Object.freeze([
    // ── Ownership surfaces (required minimum) ────────────────────────────────
    Object.freeze({
      artifactId: 'own-telegram-bot-transport',
      artifact: 'Telegram Bot transport — Notification Delivery adapter owner (extend only)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Verified existing owner — InMemoryTelegramAdapter today; W5-N01-b extends to Bot API',
      honestyRequirement:
        'Transport I/O owned by notification-delivery; telegram-product is product adapter only',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-delivery-domain',
      artifact: 'Notification Delivery — deliver / test / queue / connection domain owner',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Verified existing owner — sole delivery-domain SoT; consume not redesign',
      honestyRequirement: 'No second notification engine; Wave 5 extends adapters only',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-delivery-pipeline',
      artifact: 'Delivery pipeline — deliver() → routing → channel adapter → history/queue',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented sync pipeline — in-memory Telegram transport at terminal step',
      honestyRequirement: 'Pipeline exists; production Bot API round-trip is W5-N01-b',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-persistence',
      artifact: 'Notification persistence — DurableNotificationStore (history + queue snapshot)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — W3-O01 history + W3-O02-b queue on existing owner',
      honestyRequirement: 'Persistence ≠ production transport; no new persistence owner',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-secret-vault-telegram',
      artifact: 'Vault — HoldableSecretType.Telegram credential ciphertext owner',
      kind: 'ownership' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — Telegram secret type exists; not consumed by delivery today',
      honestyRequirement: 'Vault remains sole credential owner; adapter retrieve-only at W5-N01-b',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-workspace-isolation-notifications',
      artifact: 'Workspace Isolation — notification credentials and state per workspace',
      kind: 'ownership' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Consumed — workspace-bound delivery, prefs, and connections',
      honestyRequirement: 'Cross-workspace Telegram bind or send forbidden',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-security-review.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-user-notification-preferences',
      artifact: 'User notification preferences — routing inputs (PC-06)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — type routing, quiet hours, channel enablement',
      honestyRequirement: 'Preferences drive routing only; not transport or vault owner',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-message-template-catalog',
      artifact: 'Message template catalog — reusable notification body templates',
      kind: 'ownership' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — no template catalog; inline subject/body at deliver() today',
      honestyRequirement: 'Must not invent template SoT in slice a; deferred beyond W5-N01',
      futureW5N01Responsibility: 'out-of-scope-message-templates' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-durable-queue',
      artifact: 'Notification Durable Queue — W3-O02 work items (TD-045)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — queue domain + durable store; sync deliver() still terminal',
      honestyRequirement: 'Queue survival ≠ production Telegram send; distinct from Bot API',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-honest-product-boundaries',
      artifact: 'Honest Product boundaries — Wave 5 delivery-only invariants',
      kind: 'ownership' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in planning scope; inventory slice a catalogues only',
      honestyRequirement: 'Real delivery ≠ Live Trading; Telegram ≠ control plane',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Runtime / transport (in-memory today) ────────────────────────────────
    Object.freeze({
      artifactId: 'runtime-in-memory-telegram-adapter',
      artifact: 'InMemoryTelegramAdapter — stub channel port (no api.telegram.org)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — process-local sent[] log; active=true; not Bot API',
      honestyRequirement: 'In-memory send must not be labeled production Telegram delivery',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/in-memory-telegram.adapter.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-notification-delivery-deliver',
      artifact: 'NotificationDeliveryService.deliver() — sync terminal delivery',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — routes to InMemoryTelegramAdapter; records history + queue row',
      honestyRequirement: 'deliver() success ≠ message reached Telegram servers',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-notification-delivery-send-test',
      artifact: 'NotificationDeliveryService.sendTestNotification() — operator test path',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — fixed test body via deliver(); in-memory transport only',
      honestyRequirement: 'Test send is not production Bot API round-trip (TD-049 deferred)',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-resolve-delivery-routing-pc06',
      artifact: 'resolve-delivery-routing.ts — PC-06 routing + quiet-hours evaluation',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — type/channel routing SoT; consumed by deliver()',
      honestyRequirement: 'Routing owner remains PC-06; Wave 5 must not redesign routing',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-telegram-connection-domain',
      artifact: 'TelegramConnection — connect/bind domain (chat id never user-entered)',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — not-connected|pending|connected; in-memory bind path today',
      honestyRequirement: 'Connected status ≠ real Telegram chat bind until W5-N01-c',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/telegram-connection.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-telegram-product-in-memory-bind',
      artifact: 'TelegramProductService.inMemoryAdapterChatId — synthetic chat id bind',
      kind: 'runtime' as const,
      owner: 'telegram-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — in-memory:{workspaceId}:{userId}; not Bot API callback',
      honestyRequirement: 'Synthetic chat id must not imply real Telegram chat binding',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'apps/api/src/modules/telegram-product/telegram-product.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Commands / REST ──────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'rest-telegram-product-connect-test',
      artifact: 'PC-07 REST — /v1/telegram connect / complete / verify / test / disconnect',
      kind: 'command' as const,
      owner: 'telegram-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — delegates NotificationServicePort; no Bot API',
      honestyRequirement: 'HTTP product surface ≠ production transport Complete',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/telegram-product/telegram.controller.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'rest-notification-product-pc06',
      artifact: 'PC-06 REST — notification settings, routing, delivery history',
      kind: 'command' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — product adapter; does not deliver or connect Telegram',
      honestyRequirement: 'Product queries only; transport remains notification-delivery owner',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-product.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connections-telegram-catalog',
      artifact: 'Connection catalog TELEGRAM provider entry',
      kind: 'state' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — NOTIFICATION type; botToken credential field',
      honestyRequirement:
        'Catalog entry exists; parallel to PC-07 path — must converge at W5-N01-b',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-catalog.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'rest-connection-vault-telegram-mapping',
      artifact: 'Connection vault mapping TELEGRAM → HoldableSecretType.Telegram',
      kind: 'runtime' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — write-only vault store; not consumed by delivery adapter',
      honestyRequirement: 'Vault path exists but delivery does not retrieve bot token today',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/connections/connection-vault.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Producing paths ──────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'produce-report-notification-consumer',
      artifact: 'ReportNotificationConsumerService — requestAndDeliver / deliverCompletedRun',
      kind: 'runtime' as const,
      owner: 'product-flow' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Implemented — sync call into notification-delivery; best-effort only',
      honestyRequirement: 'Producer is not Live Trading; Telegram send remains in-memory',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/product-flow/report-notification-consumer.service.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Persistence candidates ───────────────────────────────────────────────
    Object.freeze({
      artifactId: 'persist-durable-notification-store',
      artifact: 'DurableNotificationStore — prefs + telegram connection + deliveries + queue',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Exists — analytical + queue snapshot; survives restart',
      honestyRequirement: 'Durable state ≠ production Bot API delivery truth',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'persist-delivery-queue-w3-o02',
      artifact: 'NotificationDeliveryQueueItem — W3-O02 durable queue work items',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Exists — pending|in-flight|retryable states; not Bot API execution',
      honestyRequirement: 'Queue durability ≠ Telegram message delivery Complete',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'persist-vault-telegram-ciphertext',
      artifact: 'Vault ciphertext for HoldableSecretType.Telegram bot tokens',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Exists — secret type + validation; delivery path does not retrieve',
      honestyRequirement: 'Vault stores token; adapter must retrieve at W5-N01-b only',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Operator-visible ─────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'ui-telegram-settings-view',
      artifact: 'TelegramSettingsView — connect/test/history UX (in-memory labels)',
      kind: 'operator-visible' as const,
      owner: 'telegram-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Routed — Connected/Pending labels; reflects in-memory transport state',
      honestyRequirement: 'UI Connected must require real Bot API evidence after W5-N01-b',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'apps/web/src/telegram/TelegramSettingsView.tsx',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'ui-telegram-status-labels',
      artifact: 'telegramStatusLabel / telegramVerificationLabel — operator status copy',
      kind: 'operator-visible' as const,
      owner: 'command-center' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — human labels for connection lifecycle states',
      honestyRequirement: 'Labels must not claim Verified without real bind after W5-N01-c',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'apps/web/src/telegram/telegram.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'ui-telegram-product-views',
      artifact: 'telegram.view.ts — TelegramConnectionProductView / TestProductView projections',
      kind: 'projection' as const,
      owner: 'telegram-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — maps delivery domain to PC-07 product views',
      honestyRequirement: 'Projections reflect in-memory truth; not vendor delivery proof',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/telegram-product/telegram.view.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Platform Readiness dependencies ──────────────────────────────────────
    Object.freeze({
      artifactId: 'dep-platform-readiness-notification-queue',
      artifact: 'Platform Readiness notificationQueue projection — aggregate continuity',
      kind: 'dependency' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — W3-O02-d derived view on operational readiness',
      honestyRequirement: 'Queue continuity ≠ Telegram transport Complete',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authentication',
      artifact: 'Authentication — signed-in operator for connect/test/delivery surfaces',
      kind: 'dependency' as const,
      owner: 'authentication' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed when missing',
      honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-security-review.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authorization',
      artifact: 'Authorization — PermissionClass.Projection for notification surfaces',
      kind: 'dependency' as const,
      owner: 'authorization' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — connect/test requires permitted role',
      honestyRequirement: 'Unauthorized deny; no new IAM',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-security-review.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-security-audit',
      artifact: 'Security Audit — connect/test/disconnect attribution events',
      kind: 'dependency' as const,
      owner: 'security-audit' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — lifecycle audit expected at Close',
      honestyRequirement: 'Emit required outcomes; do not own audit store',
      futureW5N01Responsibility: 'W5-N01-e' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-security-review.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-exchange-adapter-untouched',
      artifact: 'Exchange Adapter / Wave 4 Exchange Connectivity — not consumed; unchanged',
      kind: 'dependency' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference only — Wave 5 must not modify exchange I/O',
      honestyRequirement: 'Telegram notifications ≠ exchange connectivity; adapter untouched',
      futureW5N01Responsibility: 'out-of-scope-exchange-adapter' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-vault-not-in-delivery',
      artifact: 'Vault bot token not consumed by delivery adapter — transport blocker',
      kind: 'dependency' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Active gap — no vault retrieve in notification-delivery module',
      honestyRequirement: 'W5-N01-b must wire vault retrieve inside adapter boundary only',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Parallel disconnected paths ──────────────────────────────────────────
    Object.freeze({
      artifactId: 'gap-pc07-vs-connections-telegram-vault',
      artifact: 'Parallel paths — PC-07 telegram-product vs connections TELEGRAM vault',
      kind: 'ephemeral-artifact' as const,
      owner: 'telegram-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Disconnected — PC-07 in-memory bind; vault write-only on connections path',
      honestyRequirement: 'Must converge to single honest transport + credential path at W5-N01-b',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/pc-07-telegram-ux-audit.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Missing / not-implemented (catalogued honestly) ──────────────────────
    Object.freeze({
      artifactId: 'missing-api-telegram-org',
      artifact: 'Production Telegram Bot API — api.telegram.org HTTP round-trip',
      kind: 'command' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — TD-049 deferred; InMemoryTelegramAdapter is certified path',
      honestyRequirement: 'Must not fake vendor round-trip; W5-N01-b implements real I/O',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-real-chat-bind',
      artifact: 'Real Telegram chat binding via Bot API deep-link callback',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — synthetic inMemoryAdapterChatId only today',
      honestyRequirement: 'Chat id must come from Telegram callback; never user-entered field',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'apps/api/src/modules/telegram-product/telegram-product.service.ts',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-message-templates-catalog',
      artifact: 'Message templates catalog — reusable notification bodies',
      kind: 'state' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — inline subject/body at deliver() only',
      honestyRequirement: 'No template SoT invented in slice a',
      futureW5N01Responsibility: 'out-of-scope-message-templates' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-vault-in-delivery-path',
      artifact: 'Vault retrieve in notification-delivery delivery path',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — notification-delivery module has no secret-vault imports',
      honestyRequirement: 'Credentials retrieved adapter-side only at W5-N01-b; never echoed',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Operational / planning ───────────────────────────────────────────────
    Object.freeze({
      artifactId: 'op-wave5-planning-open',
      artifact: 'Wave 5 Planning Package — OPEN; W5-N01 slices named not opened',
      kind: 'operational' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Planning OPEN — slice a inventory only; not APPROVED for implementation',
      honestyRequirement: 'Planning ≠ production Telegram delivery Complete',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-planning-summary.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'op-td049-telegram-bot-api-debt',
      artifact: 'TD-049 — Telegram production Bot API technical debt label',
      kind: 'operational' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — InMemoryTelegramAdapter certified until Wave 5 W5-N01-b',
      honestyRequirement: 'Debt label ≠ closed; must not claim Bot API from inventory alone',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Honesty boundaries ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'honesty-real-delivery-not-live-trading',
      artifact: 'Real Telegram delivery ≠ Live Trading; delivery ≠ order submission',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in Wave 5 scope',
      honestyRequirement: 'Alerts outside process ≠ live capital trading enablement',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-telegram-delivery-only-not-control-plane',
      artifact: 'Telegram delivery-only — cannot start/stop/approve trades',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — no trading commands via Telegram transport',
      honestyRequirement: 'Notification channel only; control plane forbidden',
      futureW5N01Responsibility: 'out-of-scope-telegram-control-plane' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-in-memory-not-production-bot-api',
      artifact: 'InMemoryTelegramAdapter ≠ production Bot API delivery',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — in-memory sent[] is process-local simulation',
      honestyRequirement: 'deliver() ok:true must not imply message reached Telegram',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/in-memory-telegram.adapter.ts',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-connected-requires-vendor-round-trip',
      artifact: 'Connected / Verified labels require real Bot API round-trip evidence',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — synthetic bind violates today; W5-N01-b/c fixes',
      honestyRequirement: 'No fake Connected from in-memory adapter alone',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w5-n01-not-wave5-complete',
      artifact: 'W5-N01 ≠ Wave 5 COMPLETE; N01 ≠ Email/Slack/Push Complete',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — N02–N04 sequenced separately',
      honestyRequirement: 'Telegram-only first package; no wave-level Complete claims',
      futureW5N01Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-progress.md',
      existsToday: true,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),

    // ── Explicit OUT ─────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'out-bot-api-implementation-slice-a',
      artifact: 'Production Telegram Bot API implementation in W5-N01-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Forbidden — inventory only; W5-N01-b implements Bot API',
      honestyRequirement: 'Slice a catalogues surfaces; does not implement transport I/O',
      futureW5N01Responsibility: 'out-of-scope-bot-api-slice-a' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-implementation-package.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n01-b-bot-api',
      artifact: 'W5-N01-b — Production Telegram Bot API connect / test / disconnect',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — named slice; not opened from slice a',
      honestyRequirement: 'Vault-backed Bot API round-trip is post-inventory work',
      futureW5N01Responsibility: 'W5-N01-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-planning-summary.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n01-c-chat-binding',
      artifact: 'W5-N01-c — Chat binding & delivery verification',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — real chat bind post W5-N01-b',
      honestyRequirement: 'Real bind requires Bot API foundation first',
      futureW5N01Responsibility: 'W5-N01-c' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-planning-summary.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n01-d-operational-continuity',
      artifact: 'W5-N01-d — Operational continuity foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — transport continuity post Bot API',
      honestyRequirement: 'Continuity slice follows durable transport implementation',
      futureW5N01Responsibility: 'W5-N01-d' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-planning-summary.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n01-e-close-evidence',
      artifact: 'W5-N01-e — Security verification + package Close evidence',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — Close evidence assembly post implementation slices',
      honestyRequirement: 'Close requires FIV + PO act; not authorized from slice a',
      futureW5N01Responsibility: 'W5-N01-e' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-planning-summary.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n02-email-smtp',
      artifact: 'W5-N02 / V3-N02 — Email (SMTP) production transport',
      kind: 'explicit-out' as const,
      owner: 'w5-n02-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N01 — sequenced after N01 Close',
      honestyRequirement: 'Email transport is separate package; not Telegram inventory scope',
      futureW5N01Responsibility: 'out-of-scope-w5-n02' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n03-slack-discord-teams',
      artifact: 'W5-N03 / V3-N03 — Slack / Discord / Teams production transports',
      kind: 'explicit-out' as const,
      owner: 'w5-n03-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N01 — sequenced after N02',
      honestyRequirement: 'Webhook transports deferred; Telegram first',
      futureW5N01Responsibility: 'out-of-scope-w5-n03' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n04-push',
      artifact: 'W5-N04 / V3-N04 — Push notification production transport',
      kind: 'explicit-out' as const,
      owner: 'w5-n04-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N01 — final Wave 5 transport package',
      honestyRequirement: 'Push deferred beyond Telegram + email + webhooks',
      futureW5N01Responsibility: 'out-of-scope-w5-n04' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-live-trading-wave6',
      artifact: 'Live Trading / live order submission (Wave 6)',
      kind: 'explicit-out' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N01 paper notification scope',
      honestyRequirement: 'Telegram alerts ≠ live capital orders',
      futureW5N01Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-telegram-control-plane',
      artifact: 'Telegram as trading control plane — start/stop/approve via bot',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Forbidden — architecture invariant for all Wave 5',
      honestyRequirement: 'Delivery-only channel; no command bus via Telegram',
      futureW5N01Responsibility: 'out-of-scope-telegram-control-plane' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesTelegramRealDelivery: false,
      authorizesW5N01Complete: false,
    }),
  ]);

export const W5_N01_A_BINDING_FINDINGS = Object.freeze({
  telegramRealDeliveryAuthorized: false,
  customerVisibleFeatureFromSliceA: false,
  telegramNotificationsFunctionAfterSliceA: false,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
  inMemoryTelegramAdapterExists: true,
  vaultBotTokenNotConsumedByDelivery: true,
  productionBotApiMissing: true,
} as const);

export const W5_N01_A_EXPLICIT_OUT = Object.freeze([
  'bot-api-implementation',
  'outbound-production-notifications',
  'runtime-delivery-to-api-telegram-org',
  'real-chat-bind',
  'message-template-catalog',
  'vault-in-delivery-path',
  'telegram-control-plane',
  'live-trading-enablement',
  'w5-n01-b',
  'w5-n01-c',
  'w5-n01-d',
  'w5-n01-e',
  'w5-n02',
  'w5-n03',
  'w5-n04',
  'w5-n01-complete',
  'wave-5-complete',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N01_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRoutingEngine: false,
  telegramControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  w5N01CompleteClaimed: false,
  telegramRealDeliveryClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  customerVisibleFeature: false,
} as const);

export const W5_N01_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible production Telegram notification functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'InMemoryTelegramAdapter — in-process Telegram transport stub (TD-049 deferred)',
    'NotificationDeliveryService deliver() / sendTestNotification() sync pipeline',
    'PC-06 resolve-delivery-routing — type/channel routing + quiet hours',
    'PC-06 notification-product — settings, routing views, delivery history',
    'PC-07 telegram-product — connect/test REST + product views (in-memory bind)',
    'TelegramConnection domain — connect lifecycle state (synthetic bind today)',
    'User notification preferences — routing inputs per workspace/user',
    'DurableNotificationStore — W3-O01 history + W3-O02 queue snapshot',
    'HoldableSecretType.Telegram + connection-catalog TELEGRAM + connection-vault mapping',
    'Platform Readiness notificationQueue continuity projection (derived)',
    'ReportNotificationConsumer — product-flow producer into delivery',
    'Exchange Adapter / Wave 4 — reference only; untouched by Wave 5',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N01-b — Production Telegram Bot API connect / test / disconnect via vault-backed adapter',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'api.telegram.org HTTP round-trip (TD-049)',
    'Real Telegram chat binding via Bot API deep-link callback',
    'Vault bot token retrieve in notification-delivery delivery path',
    'Message templates catalog',
    'Honest Connected / Verified labels from vendor round-trip',
    'Converged PC-07 + connections TELEGRAM vault credential path',
    'W5-N01 Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'W5-N01-c — Chat binding & delivery verification',
    'W5-N01-d — Operational continuity foundation',
    'W5-N01-e — Security verification + package Close evidence',
    'W5-N02 — Email (SMTP) production transport (V3-N02 · CM-12)',
    'W5-N03 — Slack / Discord / Teams production transports (V3-N03 · CM-13–15)',
    'W5-N04 — Push notification production transport (V3-N04 · CM-16)',
    'Wave 6 — Live Trading (LT-02)',
  ] as const),
} as const);

export const W5_N01_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze(['Telegram Notification Inventory Foundation'] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N01-b — Production Telegram Bot API connect / test / disconnect',
    'W5-N01-c — Chat binding & delivery verification',
    'W5-N01-d — Operational continuity foundation',
    'W5-N01-e — Security verification + package Close evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N01AArtifactKind): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter(
    (row) => row.durabilityClass === 'SURVIVE',
  );
}

export function rowsEphemeral(): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter(
    (row) => row.durabilityClass === 'EPHEMERAL',
  );
}

export function rowsTelegramNotificationSurvive(): readonly W5N01AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N01_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsTelegramNotificationEphemeral(): readonly W5N01AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N01_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N01ACapabilityCategory,
): readonly W5N01AInventoryRow[] {
  return W5_N01_A_TELEGRAM_NOTIFICATION_INVENTORY.filter(
    (row) => row.capabilityCategory === category,
  );
}
