/**
 * W5-N03-a — Slack / Discord / Teams Notification Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not webhook implementation. Not outbound production notifications.
 * Not runtime delivery to Slack / Discord / Microsoft Teams APIs. Not W5-N03 COMPLETE. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Notification Delivery / Vault / Connection / Queue owners.
 * - EPHEMERAL: artifact is transient, stub, reserved-inactive transport, UI-only,
 *   process-local, or missing — must not be treated as production webhook truth.
 *
 * W5-N01 Telegram foundation and W5-N02 Email foundation consumed as reference patterns only.
 */

export const W5_N03_A_SLICE_ID = 'W5-N03-a' as const;

export const W5_N03_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n04-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N03AOwner = (typeof W5_N03_A_ALLOWED_OWNERS)[number];

/** Existing notification / webhook substrate owners — no new owner. */
export const W5_N03_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
] as const);

export const W5_N03_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N03AArtifactKind = (typeof W5_N03_A_ARTIFACT_KINDS)[number];

export const W5_N03_A_REQUIRED_ARTIFACT_KINDS = W5_N03_A_ARTIFACT_KINDS;

export const W5_N03_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N03ACapabilityCategory = (typeof W5_N03_A_CAPABILITY_CATEGORIES)[number];

export const W5_N03_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N03ADurabilityClass = (typeof W5_N03_A_DURABILITY_CLASSES)[number];

export const W5_N03_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N03ADependencyDirection = (typeof W5_N03_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N03_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N03-b',
  'W5-N03-c',
  'W5-N03-d',
  'W5-N03-e',
  'honesty-baseline',
  'out-of-scope-w5-n04',
  'out-of-scope-live-trading',
  'out-of-scope-webhook-slice-a',
  'out-of-scope-webhook-control-plane',
  'out-of-scope-exchange-adapter',
  'out-of-scope-message-templates',
  'out-of-scope-w5-n03-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-w5-n01-reopen',
  'out-of-scope-w5-n02-reopen',
  'w5-n01-reference',
  'w5-n02-reference',
] as const);

export type W5N03AFutureResponsibility = (typeof W5_N03_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N03AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N03AArtifactKind;
  owner: W5N03AOwner;
  durabilityClass: W5N03ADurabilityClass;
  capabilityCategory: W5N03ACapabilityCategory;
  dependencyDirection?: W5N03ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N03Responsibility: W5N03AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesWebhookRealDelivery: boolean;
  authorizesW5N03Complete: boolean;
}>;

/**
 * Frozen inventory of Slack / Discord / Teams webhook transport surfaces,
 * notification delivery paths, vault/connection substrates, operator-visible
 * artifacts, platform dependencies, ownership boundaries, and honesty rules
 * for Wave 5 slice W5-N03-a.
 */
export const W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY: readonly W5N03AInventoryRow[] =
  Object.freeze([
    // ── Ownership surfaces (required minimum) ────────────────────────────────
    Object.freeze({
      artifactId: 'own-slack-discord-teams-webhook-transport',
      artifact:
        'Slack / Discord / Teams webhook transport — Notification Delivery adapter owner (extend only)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Verified existing owner — ReservedInactiveChannelAdapter for slack/discord/teams today; W5-N03-b extends to webhook I/O',
      honestyRequirement:
        'Transport I/O owned by notification-delivery; connection-management is connect product only',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-delivery-domain',
      artifact: 'Notification Delivery — deliver / test / queue / connection domain owner',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Verified existing owner — sole delivery-domain SoT; consume not redesign',
      honestyRequirement: 'No second notification engine; Wave 5 extends adapters only',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-delivery-pipeline',
      artifact: 'Delivery pipeline — deliver() → routing → channel adapter → history/queue',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented sync pipeline — slack/discord/teams routes skip with channel-reserved',
      honestyRequirement: 'Pipeline exists; production webhook round-trip is W5-N03-b',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-persistence',
      artifact: 'Notification persistence — DurableNotificationStore (history + queue snapshot)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — W3-O01 history + W3-O02-b queue on existing owner',
      honestyRequirement: 'Persistence ≠ production transport; no new persistence owner',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-secret-vault-webhook',
      artifact: 'Vault — HoldableSecretType webhook credential owner (Slack/Discord/Teams absent)',
      kind: 'ownership' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented vault substrate — no Slack/Discord/Teams secret types in holdable catalog today',
      honestyRequirement:
        'Vault remains sole credential owner; adapter retrieve-only at W5-N03-b; no Slack/Discord/Teams types yet',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-connection-management-webhook',
      artifact: 'Connection Management — operator connect product facade for webhook channels',
      kind: 'ownership' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Wave 2 owner — no Slack/Discord/Teams connection catalog entries consumed by delivery today',
      honestyRequirement:
        'Connect product follows N01/N02 patterns at W5-N03-b; facade not redesigned',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-workspace-isolation-notifications',
      artifact: 'Workspace Isolation — notification credentials and state per workspace',
      kind: 'ownership' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Consumed — workspace-bound delivery, prefs, and connections',
      honestyRequirement: 'Cross-workspace webhook bind or send forbidden',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-security-review.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-user-notification-preferences',
      artifact:
        'User notification preferences — routing inputs including slack/discord/teams enablement',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — type routing, quiet hours, channel enablement (slack/discord/teams reserved)',
      honestyRequirement: 'Preferences drive routing only; not transport or vault owner',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-notification-durable-queue',
      artifact: 'Notification Durable Queue — W3-O02 work items (TD-045)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — queue domain + durable store; sync deliver() still terminal',
      honestyRequirement: 'Queue survival ≠ production webhook send; distinct from webhook I/O',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'own-honest-product-boundaries',
      artifact: 'Honest Product boundaries — Wave 5 Slack/Discord/Teams delivery-only invariants',
      kind: 'ownership' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N03 planning scope; inventory slice a catalogues only',
      honestyRequirement:
        'Real delivery ≠ Live Trading; webhooks ≠ control plane; team chat delivery-only',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Slack artifact surfaces ──────────────────────────────────────────────
    Object.freeze({
      artifactId: 'slack-workspace-binding-disclosure',
      artifact: 'Slack workspace binding — PC-07 disclosure field (Workspace; not collected)',
      kind: 'state' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Disclosure only — RESERVED_CHANNEL_REQUIRED_FIELDS lists Workspace; configurable=false',
      honestyRequirement:
        'Workspace binding must not be treated as connected Slack workspace today',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-channel.view.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'slack-bot-token-vault-absent',
      artifact: 'Slack bot token — vault-backed credential (no HoldableSecretType.Slack today)',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — holdable-secret-type has no Slack/Discord/Teams types',
      honestyRequirement: 'Bot token storage deferred to W5-N03-b; vault retrieve-only at adapter',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'slack-channel-mapping-routing',
      artifact: 'Slack channel mapping — prefs typeRouting channels[] includes slack when enabled',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented routing inputs — slack in NOTIFICATION_CHANNELS; reserved-inactive skips delivery',
      honestyRequirement: 'Routing mapping ≠ Slack channel webhook delivery',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'slack-webhook-endpoint-transport',
      artifact: 'Slack webhook endpoint — outbound provider HTTP transport (missing)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — ReservedInactiveChannelAdapter returns channel-reserved; no Slack API I/O',
      honestyRequirement:
        'Webhook endpoint I/O is W5-N03-b; SSRF allowlist required at implementation',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'slack-delivery-metadata-attempts',
      artifact: 'Slack delivery metadata — ChannelDeliveryAttempt with channel-reserved skipReason',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — slack attempts record channel-reserved skipReason when routed',
      honestyRequirement: 'Skip metadata must not be relabeled as delivered to Slack',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Discord artifact surfaces ────────────────────────────────────────────
    Object.freeze({
      artifactId: 'discord-guild-binding-disclosure',
      artifact: 'Discord guild binding — PC-07 disclosure (Webhook, Channel; guild implicit)',
      kind: 'state' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Disclosure only — RESERVED_CHANNEL_REQUIRED_FIELDS lists Webhook, Channel; not collected',
      honestyRequirement: 'Guild binding must not be treated as connected Discord server today',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-channel.view.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'discord-bot-token-vault-absent',
      artifact: 'Discord bot token — vault-backed credential (no HoldableSecretType.Discord today)',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — holdable-secret-type has no Discord secret type',
      honestyRequirement: 'Bot token storage deferred to W5-N03-b; vault retrieve-only at adapter',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'discord-channel-mapping-routing',
      artifact:
        'Discord channel mapping — prefs typeRouting channels[] includes discord when enabled',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented routing inputs — discord in NOTIFICATION_CHANNELS; reserved-inactive skips delivery',
      honestyRequirement: 'Routing mapping ≠ Discord channel webhook delivery',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'discord-webhook-endpoint-transport',
      artifact: 'Discord webhook endpoint — outbound provider HTTP transport (missing)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — ReservedInactiveChannelAdapter returns channel-reserved; no Discord API I/O',
      honestyRequirement:
        'Webhook endpoint I/O is W5-N03-b; SSRF allowlist required at implementation',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'discord-delivery-metadata-attempts',
      artifact:
        'Discord delivery metadata — ChannelDeliveryAttempt with channel-reserved skipReason',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — discord attempts record channel-reserved skipReason when routed',
      honestyRequirement: 'Skip metadata must not be relabeled as delivered to Discord',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Microsoft Teams artifact surfaces ────────────────────────────────────
    Object.freeze({
      artifactId: 'teams-tenant-binding-disclosure',
      artifact: 'Microsoft Teams tenant binding — PC-07 disclosure (Webhook, Team, Channel)',
      kind: 'state' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Disclosure only — RESERVED_CHANNEL_REQUIRED_FIELDS lists Webhook, Team, Channel; not collected',
      honestyRequirement: 'Tenant binding must not be treated as connected Teams tenant today',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-channel.view.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'teams-bot-credentials-vault-absent',
      artifact:
        'Microsoft Teams bot credentials — vault-backed (no HoldableSecretType.Teams today)',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — holdable-secret-type has no Teams secret type',
      honestyRequirement:
        'Bot credentials storage deferred to W5-N03-b; vault retrieve-only at adapter',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'teams-channel-mapping-routing',
      artifact: 'Microsoft Teams channel mapping — prefs typeRouting channels[] includes teams',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented routing inputs — teams in NOTIFICATION_CHANNELS; reserved-inactive skips delivery',
      honestyRequirement: 'Routing mapping ≠ Teams channel webhook delivery',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'teams-webhook-endpoint-transport',
      artifact: 'Microsoft Teams webhook endpoint — outbound provider HTTP transport (missing)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — ReservedInactiveChannelAdapter returns channel-reserved; no Teams API I/O',
      honestyRequirement:
        'Webhook endpoint I/O is W5-N03-b; SSRF allowlist required at implementation',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'teams-delivery-metadata-attempts',
      artifact:
        'Microsoft Teams delivery metadata — ChannelDeliveryAttempt with channel-reserved skipReason',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — teams attempts record channel-reserved skipReason when routed',
      honestyRequirement: 'Skip metadata must not be relabeled as delivered to Teams',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Shared substrate surfaces ────────────────────────────────────────────
    Object.freeze({
      artifactId: 'shared-notification-durable-queue',
      artifact: 'Shared notification queue — W3-O02 durable work items for all channels',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Exists — pending|in-flight|retryable states; not webhook execution',
      honestyRequirement: 'Queue durability ≠ Slack/Discord/Teams message delivery Complete',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'shared-delivery-result-metadata',
      artifact: 'Shared delivery metadata — DeliveryResult immutable record with channel attempts',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Exists — deliveryId, attempts[], outcome; webhook channel attempts show channel-reserved',
      honestyRequirement:
        'Delivery metadata records skip truth; not vendor delivery proof for webhooks',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'shared-user-notification-preferences',
      artifact: 'Shared user preferences — channel enablement for slack/discord/teams',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — channels.slack/discord/teams boolean enablement in prefs',
      honestyRequirement: 'Preference enablement ≠ webhook transport active',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'shared-workspace-bindings',
      artifact: 'Shared workspace bindings — workspaceId scoped prefs, deliveries, and connections',
      kind: 'state' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Consumed — all notification state keyed by workspaceId',
      honestyRequirement: 'Cross-workspace webhook credential bind or send forbidden',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-security-review.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'shared-integrity-delivery-result-immutable',
      artifact: 'Shared integrity metadata — DeliveryResult deep-freeze immutable delivery record',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — createDeliveryResult deep-freezes attempts and outcome',
      honestyRequirement:
        'Immutable record preserves honest skip/deliver truth for webhook channels',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'shared-integrity-queue-correlation',
      artifact:
        'Shared integrity metadata — queue item deliveryId correlation queue ↔ DeliveryResult',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — queueItem.deliveryId set on deliver() completion',
      honestyRequirement: 'Correlation supports audit; not webhook delivery proof',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Runtime / transport (reserved-inactive today) ────────────────────────
    Object.freeze({
      artifactId: 'runtime-reserved-inactive-slack-adapter',
      artifact: 'ReservedInactiveChannelAdapter — slack channel port (no webhook I/O)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — active=false; send() returns channel-reserved skip',
      honestyRequirement: 'Reserved-inactive must not be labeled production Slack delivery',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-reserved-inactive-discord-adapter',
      artifact: 'ReservedInactiveChannelAdapter — discord channel port (no webhook I/O)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — active=false; send() returns channel-reserved skip',
      honestyRequirement: 'Reserved-inactive must not be labeled production Discord delivery',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-reserved-inactive-teams-adapter',
      artifact: 'ReservedInactiveChannelAdapter — teams channel port (no webhook I/O)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Implemented — active=false; send() returns channel-reserved skip',
      honestyRequirement: 'Reserved-inactive must not be labeled production Teams delivery',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-notification-delivery-deliver',
      artifact:
        'NotificationDeliveryService.deliver() — sync terminal delivery (webhook skip path)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus:
        'Implemented — slack/discord/teams routes get channel-reserved skip; records history + queue row',
      honestyRequirement: 'deliver() skip ≠ message reached Slack/Discord/Teams',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-resolve-delivery-routing-pc06',
      artifact: 'resolve-delivery-routing.ts — PC-06 routing + quiet-hours evaluation',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — type/channel routing SoT; slack/discord/teams in routes when enabled in prefs',
      honestyRequirement: 'Routing owner remains PC-06; Wave 5 must not redesign routing',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-webhook-channels-boundary-inactive',
      artifact:
        'NOTIFICATION_DELIVERY_BOUNDARY — slackChannel/discordChannel/teamsChannel active port false',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — slackChannel/discordChannel/teamsChannel: false in boundary flags',
      honestyRequirement: 'Boundary flags must remain false until W5-N03-b activates transport',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-boundary.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-notification-channel-catalog-webhooks',
      artifact: 'NOTIFICATION_CHANNEL_CATALOG — slack/discord/teams reserved-inactive descriptors',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — slack/discord/teams status reserved-inactive; only telegram active',
      honestyRequirement: 'Catalog reserved status must not imply webhook transport exists',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'runtime-notification-ports-active-webhooks-false',
      artifact: 'NOTIFICATION_PORTS_ACTIVE — slackChannel/discordChannel/teamsChannel false',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — port active flags false for all webhook channels',
      honestyRequirement: 'Port flags must remain false until W5-N03-b webhook adapters registered',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/ports/notification.port.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Commands / REST / catalog ──────────────────────────────────────────
    Object.freeze({
      artifactId: 'rest-notification-product-pc07',
      artifact: 'PC-07 REST — notification channel settings, routing, delivery history',
      kind: 'command' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — product adapter; does not deliver or connect Slack/Discord/Teams webhooks',
      honestyRequirement: 'Product queries only; transport remains notification-delivery owner',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-product.service.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'rest-pc07-channel-matrix',
      artifact: 'PC-07 Channel Matrix — Slack/Discord/Teams reserved-inactive catalog truth',
      kind: 'state' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Binding — Slack/Discord/Teams offered=No; disclosure only; Send Test hidden; transport None',
      honestyRequirement: 'Matrix must not claim webhook transport offered before W5-N03-b',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/pc-07-channel-matrix.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Producing paths ──────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'produce-report-notification-consumer',
      artifact: 'ReportNotificationConsumerService — requestAndDeliver / deliverCompletedRun',
      kind: 'runtime' as const,
      owner: 'product-flow' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus:
        'Implemented — sync call into notification-delivery; webhook channels skipped when routed',
      honestyRequirement: 'Producer is not Live Trading; webhook send remains reserved-inactive',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/product-flow/report-notification-consumer.service.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'meta-channel-delivery-view-webhook-projection',
      artifact: 'ChannelDeliveryView — reservedChannels projection including webhook skip',
      kind: 'projection' as const,
      owner: 'product-flow' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus:
        'Implemented — reservedChannels[] with skipReason for slack/discord/teams when attempted',
      honestyRequirement: 'Projection reflects reserved-inactive truth; not webhook delivery proof',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/product-flow/channel-delivery.view.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Persistence candidates ───────────────────────────────────────────────
    Object.freeze({
      artifactId: 'persist-durable-notification-store',
      artifact: 'DurableNotificationStore — prefs + deliveries + queue (no webhook anchor today)',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Exists — analytical + queue snapshot; survives restart',
      honestyRequirement: 'Durable state ≠ production webhook delivery truth',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'persist-webhook-notification-anchor',
      artifact:
        'WorkspaceWebhookNotificationAnchor — canonical Slack/Discord/Teams delivery anchors (W5-N03-b)',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no slack/discord/teams anchor repository; N01/N02 anchor patterns exist as reference',
      honestyRequirement: 'Anchor persistence ≠ webhook delivery Complete; hydrate is W5-N03-c',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'persist-vault-no-webhook-types',
      artifact: 'Vault ciphertext — no Slack/Discord/Teams HoldableSecretType entries today',
      kind: 'persistence-candidate' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Exists vault substrate — Binance/Bybit/Okx/Telegram/Smtp/OpenRouter only; no webhook types',
      honestyRequirement: 'Vault stores credentials; webhook types added at W5-N03-b only',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Operator-visible ─────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'ui-notification-channels-view-webhooks',
      artifact: 'NotificationChannelsView — Slack/Discord/Teams listed as reserved channels',
      kind: 'operator-visible' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Routed — Slack/Discord/Teams stay reserved; Telegram active',
      honestyRequirement: 'UI must not claim Connected without webhook round-trip after W5-N03-b',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/web/src/notifications/NotificationChannelsView.tsx',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'ui-notification-channel-detail-webhooks',
      artifact: 'NotificationChannelDetailView — reserved channel detail (no webhook form today)',
      kind: 'operator-visible' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus: 'Routed — webhook fields not collected; reserved-inactive copy',
      honestyRequirement:
        'Detail view must not collect webhook credentials until W5-N03-b product slice',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/web/src/notifications/NotificationChannelDetailPage.tsx',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'ui-notifications-webhook-labels',
      artifact: 'notifications.ts — slack/discord/teams channel label mapping',
      kind: 'operator-visible' as const,
      owner: 'command-center' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus:
        'Implemented — human labels Slack/Discord/Microsoft Teams for reserved channel ids',
      honestyRequirement: 'Label must not imply active transport',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/web/src/notifications/notifications.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Platform Readiness / foundation references ───────────────────────────
    Object.freeze({
      artifactId: 'dep-platform-readiness-notification-queue',
      artifact: 'Platform Readiness notificationQueue projection — aggregate continuity',
      kind: 'dependency' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — W3-O02-d derived view on operational readiness',
      honestyRequirement: 'Queue continuity ≠ webhook transport Complete',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-w5-n01-telegram-foundation-reference',
      artifact: 'W5-N01 Telegram foundation — anchor/recovery/continuity pattern reference',
      kind: 'dependency' as const,
      owner: 'w5-n01-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference only — W5-N01 Closed; webhooks follow same owner patterns',
      honestyRequirement: 'Consume N01 patterns; do not redesign Telegram artifacts',
      futureW5N03Responsibility: 'w5-n01-reference' as const,
      evidencePath: 'apps/api/src/platform-conformance/w5-n01-a-telegram-notification-inventory.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-w5-n02-email-foundation-reference',
      artifact: 'W5-N02 Email foundation — anchor/recovery/continuity pattern reference',
      kind: 'dependency' as const,
      owner: 'w5-n02-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference only — W5-N02 Closed; webhooks follow same owner patterns',
      honestyRequirement: 'Consume N02 patterns; do not redesign Email artifacts',
      futureW5N03Responsibility: 'w5-n02-reference' as const,
      evidencePath: 'apps/api/src/platform-conformance/w5-n02-a-email-notification-inventory.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authentication',
      artifact: 'Authentication — signed-in operator for connect/test/delivery surfaces',
      kind: 'dependency' as const,
      owner: 'authentication' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed when missing',
      honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-security-review.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-consumes-authorization',
      artifact: 'Authorization — PermissionClass.Projection for notification surfaces',
      kind: 'dependency' as const,
      owner: 'authorization' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — connect/test requires permitted role',
      honestyRequirement: 'Unauthorized deny; no new IAM',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-security-review.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-blocked-by-vault-no-webhook-types',
      artifact: 'Vault webhook credentials not in holdable catalog — transport blocker',
      kind: 'dependency' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus:
        'Active gap — no Slack/Discord/Teams HoldableSecretType; no vault retrieve for webhooks',
      honestyRequirement:
        'W5-N03-b must add vault types and wire retrieve inside adapter boundary only',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'dep-exchange-adapter-untouched',
      artifact: 'Exchange Adapter / Wave 4 Exchange Connectivity — not consumed; unchanged',
      kind: 'dependency' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference only — Wave 5 must not modify exchange I/O',
      honestyRequirement: 'Webhook notifications ≠ exchange connectivity; adapter untouched',
      futureW5N03Responsibility: 'out-of-scope-exchange-adapter' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Missing / honesty blockers (catalogued honestly) ─────────────────────
    Object.freeze({
      artifactId: 'missing-production-webhook-transports',
      artifact: 'Production webhook transports — Slack/Discord/Teams provider round-trip',
      kind: 'command' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — TD-050 deferred; ReservedInactiveChannelAdapter is certified path for all three',
      honestyRequirement: 'Must not fake vendor round-trip; W5-N03-b implements real I/O',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-runtime-webhook-delivery',
      artifact: 'Runtime webhook delivery — HTTP POST to Slack/Discord/Teams endpoints',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — notification-delivery module has no webhook adapter imports or HTTP I/O',
      honestyRequirement: 'Runtime delivery requires W5-N03-b adapter; no outbound HTTP today',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-webhook-restart-recovery',
      artifact: 'Slack/Discord/Teams restart recovery — hydrate canonical anchors after restart',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no WebhookNotificationRestartRecoveryService; N01/N02 recovery exists as reference',
      honestyRequirement: 'Recovery requires durable anchors first (W5-N03-b); hydrate is W5-N03-c',
      futureW5N03Responsibility: 'W5-N03-c' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-webhook-operational-continuity',
      artifact: 'Slack/Discord/Teams operational continuity — Platform Readiness projection',
      kind: 'operational' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no webhook channel continuity projection; queue continuity exists only',
      honestyRequirement: 'Continuity slice follows durable transport implementation (W5-N03-d)',
      futureW5N03Responsibility: 'W5-N03-d' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-durable-webhook-anchors',
      artifact: 'Durable Slack/Discord/Teams notification anchors — workspace-scoped persistence',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no prisma-webhook-notification-anchor.repository; N01/N02 anchor repos exist',
      honestyRequirement: 'Anchor persistence is W5-N03-b; must not invent SoT in slice a',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-webhook-delivery-execution',
      artifact: 'Webhook delivery execution — queue retry / async outbound send',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — deliver() is sync terminal; queue persists work items without webhook retry execution',
      honestyRequirement: 'Delivery execution deferred; webhook transport retry is post W5-N03-b',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/README.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'missing-webhook-connect-product',
      artifact: 'Webhook connect / test / disconnect product surface (PC-07 webhook channels)',
      kind: 'command' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no slack/discord/teams-specific connect REST; reserved-inactive only',
      honestyRequirement: 'Connect product follows N01/N02 patterns at W5-N03-b',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'gap-vault-webhook-types-absent',
      artifact:
        'Parallel gap — Vault holdable catalog vs Slack/Discord/Teams webhook credentials required',
      kind: 'ephemeral-artifact' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Disconnected — Telegram/Smtp/OpenRouter types exist; Slack/Discord/Teams webhook types absent',
      honestyRequirement:
        'Must converge only under Notification Delivery adapter at W5-N03-b; no local secret store',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Operational / planning ───────────────────────────────────────────────
    Object.freeze({
      artifactId: 'op-w5-n03-planning-open',
      artifact: 'W5-N03 Planning Package — OPEN; slices named not opened for implementation',
      kind: 'operational' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus:
        'Planning OPEN — slice a inventory only; not APPROVED for webhook implementation',
      honestyRequirement: 'Planning ≠ production webhook delivery Complete',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'op-td050-reserved-channels-debt',
      artifact: 'TD-050 — Reserved notification channels (SMTP / Slack / Discord / Teams / Push)',
      kind: 'operational' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — slack/discord/teams reserved-inactive until Wave 5 W5-N03-b',
      honestyRequirement: 'Debt label ≠ closed; must not claim webhooks from inventory alone',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Honesty boundaries ───────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'honesty-real-delivery-not-live-trading',
      artifact: 'Real webhook delivery ≠ Live Trading; delivery ≠ order submission',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N03 scope',
      honestyRequirement: 'Team chat alerts outside process ≠ live capital trading enablement',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-webhook-delivery-only-not-control-plane',
      artifact: 'Webhook delivery-only — cannot start/stop/approve trades via team chat',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — no trading commands via Slack/Discord/Teams transport',
      honestyRequirement: 'Notification channel only; control plane forbidden',
      futureW5N03Responsibility: 'out-of-scope-webhook-control-plane' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-reserved-inactive-not-production-webhook',
      artifact: 'ReservedInactiveChannelAdapter ≠ production Slack/Discord/Teams delivery',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — channel-reserved skip is not webhook send',
      honestyRequirement: 'deliver() skip must not imply message reached team chat',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-connected-requires-webhook-round-trip',
      artifact: 'Connected / Verified labels require real webhook round-trip evidence',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — reserved-inactive violates today; W5-N03-b fixes',
      honestyRequirement: 'No fake Connected from reserved-inactive adapter alone',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-validation-plan.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-w5-n03-not-wave5-complete',
      artifact: 'W5-N03 ≠ Wave 5 COMPLETE; N03 ≠ Push Complete',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — N04 sequenced separately',
      honestyRequirement: 'Webhook-only package; no wave-level Complete claims',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-overview.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'honesty-no-plaintext-secret-echo',
      artifact: 'No plaintext webhook secret echo — vault retrieve adapter-side only',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — security review intent; fail closed on missing vault context',
      honestyRequirement: 'Webhook credentials never echoed in API responses or logs',
      futureW5N03Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-security-review.md',
      existsToday: true,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),

    // ── Explicit OUT ─────────────────────────────────────────────────────────
    Object.freeze({
      artifactId: 'out-webhook-implementation-slice-a',
      artifact: 'Production webhook implementation in W5-N03-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Forbidden — inventory only; W5-N03-b implements webhook I/O',
      honestyRequirement: 'Slice a catalogues surfaces; does not implement transport I/O',
      futureW5N03Responsibility: 'out-of-scope-webhook-slice-a' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-implementation-package.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n03-b-durable-anchors',
      artifact: 'W5-N03-b — Durable Slack/Discord/Teams notification anchors',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — named slice; not opened from slice a',
      honestyRequirement: 'Anchor persistence is post-inventory work',
      futureW5N03Responsibility: 'W5-N03-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n03-c-restart-recovery',
      artifact: 'W5-N03-c — Slack/Discord/Teams notification restart recovery',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — restart hydrate post W5-N03-b',
      honestyRequirement: 'Recovery requires durable anchors first',
      futureW5N03Responsibility: 'W5-N03-c' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n03-d-operational-continuity',
      artifact: 'W5-N03-d — Slack/Discord/Teams operational continuity foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — transport continuity post webhook implementation',
      honestyRequirement: 'Continuity slice follows durable transport implementation',
      futureW5N03Responsibility: 'W5-N03-d' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n03-e-close-evidence',
      artifact: 'W5-N03-e — Security verification + package Close evidence',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred — Close evidence assembly post implementation slices',
      honestyRequirement: 'Close requires FIV + PO act; not authorized from slice a',
      futureW5N03Responsibility: 'W5-N03-e' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n04-push',
      artifact: 'W5-N04 / V3-N04 — Push notification production transport',
      kind: 'explicit-out' as const,
      owner: 'w5-n04-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N03 — final Wave 5 transport package',
      honestyRequirement: 'Push deferred beyond webhooks',
      futureW5N03Responsibility: 'out-of-scope-w5-n04' as const,
      evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-live-trading-wave6',
      artifact: 'Live Trading / live order submission (Wave 6)',
      kind: 'explicit-out' as const,
      owner: 'live-trading-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Out of W5-N03 team chat notification scope',
      honestyRequirement: 'Webhook alerts ≠ live capital orders',
      futureW5N03Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-webhook-control-plane',
      artifact: 'Team chat as trading control plane — start/stop/approve via Slack/Discord/Teams',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Forbidden — architecture invariant for all Wave 5',
      honestyRequirement: 'Delivery-only channel; no command bus via webhooks',
      futureW5N03Responsibility: 'out-of-scope-webhook-control-plane' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-scope.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n01-reopen',
      artifact: 'Reopen W5-N01 Telegram Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'w5-n01-reference' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Forbidden — W5-N01 Closed; consume patterns only',
      honestyRequirement: 'Telegram artifacts remain frozen; webhooks extend adapters only',
      futureW5N03Responsibility: 'out-of-scope-w5-n01-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
    Object.freeze({
      artifactId: 'out-w5-n02-reopen',
      artifact: 'Reopen W5-N02 Email Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'w5-n02-reference' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Forbidden — W5-N02 Closed; consume patterns only',
      honestyRequirement: 'Email artifacts remain frozen; webhooks extend adapters only',
      futureW5N03Responsibility: 'out-of-scope-w5-n02-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-planning-summary.md',
      existsToday: false,
      authorizesWebhookRealDelivery: false,
      authorizesW5N03Complete: false,
    }),
  ]);

export const W5_N03_A_BINDING_FINDINGS = Object.freeze({
  webhookRealDeliveryAuthorized: false,
  slackDiscordTeamsNotificationsFunctionAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  reservedInactiveWebhookAdaptersExist: true,
  vaultWebhookTypesAbsent: true,
  productionWebhookTransportsMissing: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N03_A_EXPLICIT_OUT = Object.freeze([
  'webhook-implementation',
  'outbound-production-notifications',
  'runtime-delivery-to-slack-discord-teams',
  'real-webhook-round-trip',
  'webhook-control-plane',
  'live-trading-enablement',
  'w5-n03-b',
  'w5-n03-c',
  'w5-n03-d',
  'w5-n03-e',
  'w5-n04',
  'w5-n03-complete',
  'wave-5-complete',
  'w5-n01-reopen',
  'w5-n02-reopen',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N03_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRoutingEngine: false,
  webhookControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  w5N03CompleteClaimed: false,
  webhookRealDeliveryClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  customerVisibleFeature: false,
  w5N01Reopened: false,
  w5N02Reopened: false,
} as const);

export const W5_N03_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible production Slack / Discord / Teams notification functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'ReservedInactiveChannelAdapter — slack/discord/teams channels reserved-inactive (TD-050 deferred)',
    'NotificationDeliveryService deliver() / sendTestNotification() sync pipeline (webhook skip path)',
    'PC-06 resolve-delivery-routing — type/channel routing + quiet hours',
    'PC-07 notification-product — channel settings, routing views, delivery history',
    'NOTIFICATION_CHANNEL_CATALOG — slack/discord/teams reserved-inactive descriptors',
    'NOTIFICATION_DELIVERY_BOUNDARY — slackChannel/discordChannel/teamsChannel active=false',
    'User notification preferences — routing inputs including slack/discord/teams channel enablement',
    'DurableNotificationStore — W3-O01 history + W3-O02 queue snapshot',
    'DeliveryResult + ChannelDeliveryAttempt metadata — honest skip/deliver records',
    'PC-07 Channel Matrix — Slack/Discord/Teams disclosure-only; not offered',
    'Platform Readiness notificationQueue continuity projection (derived)',
    'ReportNotificationConsumer — product-flow producer into delivery',
    'W5-N01 Telegram foundation — anchor/recovery pattern reference',
    'W5-N02 Email foundation — anchor/recovery pattern reference',
    'Exchange Adapter / Wave 4 — reference only; untouched by Wave 5',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N03-b — Production webhook connect / test / disconnect via vault-backed adapters',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Slack / Discord / Teams provider webhook round-trip (TD-050)',
    'Durable webhook notification anchors (W5-N03-b)',
    'Vault Slack/Discord/Teams secret types and retrieve in delivery path',
    'Webhook connect / test product surface',
    'Honest Connected / Verified labels from webhook round-trip',
    'W5-N03 Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'W5-N03-c — Slack/Discord/Teams notification restart recovery',
    'W5-N03-d — Slack/Discord/Teams operational continuity foundation',
    'W5-N03-e — Security verification + package Close evidence',
    'W5-N04 — Push notification production transport (V3-N04 · CM-16)',
    'Wave 6 — Live Trading (LT-02)',
  ] as const),
} as const);

export const W5_N03_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze(['Slack / Discord / Teams Notification Inventory Foundation'] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N03-b — Durable webhook notification anchors + production webhook transport',
    'W5-N03-c — Slack/Discord/Teams notification restart recovery',
    'W5-N03-d — Slack/Discord/Teams operational continuity foundation',
    'W5-N03-e — Security verification + package Close evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N03AArtifactKind): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter(
    (row) => row.durabilityClass === 'SURVIVE',
  );
}

export function rowsEphemeral(): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter(
    (row) => row.durabilityClass === 'EPHEMERAL',
  );
}

export function rowsSlackDiscordTeamsNotificationSurvive(): readonly W5N03AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N03_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsSlackDiscordTeamsNotificationEphemeral(): readonly W5N03AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N03_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter(
    (row) => row.kind === 'honesty-boundary',
  );
}

export function rowsExplicitOut(): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter(
    (row) => row.kind === 'explicit-out',
  );
}

export function rowsByCapabilityCategory(
  category: W5N03ACapabilityCategory,
): readonly W5N03AInventoryRow[] {
  return W5_N03_A_SLACK_DISCORD_TEAMS_NOTIFICATION_INVENTORY.filter(
    (row) => row.capabilityCategory === category,
  );
}
