/**
 * w5-n19-a — Notification Retry Scheduling Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Notification Retry Scheduling implementation. Not production transport I/O.
 * Not retry scheduling runtime / retry execution / Scheduler Platform / Workflow Engine / Event Bus.
 * Not W5-N19 COMPLETE. Not Notification Platform Complete. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - FOUNDATION: retry scheduling foundation layer artifact on notification-delivery owner (planned or reference).
 * - DURABLE: artifact persists across API restart today on existing owner.
 * - RECOVERABLE: artifact has defined restart recovery on existing owner or consumed foundation.
 * - EPHEMERAL: transient, missing retry scheduling layer, UI-only, process-local, or absent.
 * - OUT OF SCOPE: explicit deferral — must not authorize retry scheduling functional.
 *
 * W5-N01…N18 per-channel and platform foundations consumed as reference patterns only — not reopened.
 */

export const W5_N19_A_SLICE_ID = 'W5-N19-a' as const;

export const W5_N19_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'w5-n18-reference',
  'ai-gateway-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N19AOwner = (typeof W5_N19_A_ALLOWED_OWNERS)[number];

/** Existing notification / platform retry scheduling substrate owners — no new owner. */
export const W5_N19_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'platform-readiness',
] as const);

export const W5_N19_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N19AArtifactKind = (typeof W5_N19_A_ARTIFACT_KINDS)[number];

export const W5_N19_A_REQUIRED_ARTIFACT_KINDS = W5_N19_A_ARTIFACT_KINDS;

export const W5_N19_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N19ACapabilityCategory = (typeof W5_N19_A_CAPABILITY_CATEGORIES)[number];

export const W5_N19_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N19ADurabilityClass = (typeof W5_N19_A_DURABILITY_CLASSES)[number];

export const W5_N19_A_RETRY_SCHEDULING_CLASSIFICATIONS = Object.freeze([
  'FOUNDATION',
  'DURABLE',
  'RECOVERABLE',
  'EPHEMERAL',
  'OUT OF SCOPE',
] as const);

export type W5N19ARetrySchedulingClassification =
  (typeof W5_N19_A_RETRY_SCHEDULING_CLASSIFICATIONS)[number];

export const W5_N19_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N19ADependencyDirection = (typeof W5_N19_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N19_A_PERSISTENCE_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n17-reference',
  'w5-n18-reference',
  'w5-n19-b',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N19APersistenceResponsibility =
  (typeof W5_N19_A_PERSISTENCE_RESPONSIBILITIES)[number];

export const W5_N19_A_RECOVERY_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n17-reference',
  'w5-n18-reference',
  'w5-n19-c',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N19ARecoveryResponsibility = (typeof W5_N19_A_RECOVERY_RESPONSIBILITIES)[number];

export const W5_N19_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES = Object.freeze([
  'platform-readiness',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n17-reference',
  'w5-n18-reference',
  'w5-n19-d',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N19AOperationalContinuityResponsibility =
  (typeof W5_N19_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES)[number];

export const W5_N19_A_HONEST_PRODUCT_STATES = Object.freeze([
  'not-implemented',
  'infrastructure-only',
  'implemented-today',
  'reserved-inactive',
  'planned',
  'deferred',
  'binding-honesty',
  'explicit-out',
  'not-applicable',
] as const);

export type W5N19AHonestProductState = (typeof W5_N19_A_HONEST_PRODUCT_STATES)[number];

export const W5_N19_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N19-b',
  'W5-N19-c',
  'W5-N19-d',
  'W5-N19-e',
  'honesty-baseline',
  'out-of-scope-live-trading',
  'out-of-scope-platform-retry-scheduling-slice-a',
  'out-of-scope-production-transport-i/o',
  'out-of-scope-exchange-adapter',
  'out-of-scope-w5-n19-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-notification-platform-complete',
  'out-of-scope-w5-n12-reopen',
  'out-of-scope-w5-n18-reopen',
  'out-of-scope-ai-gateway',
  'out-of-scope-scheduler-platform',
  'out-of-scope-retry-orchestration',
  'out-of-scope-retry-execution-runtime',
  'out-of-scope-retry-policies',
  'out-of-scope-cron-scheduling',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n17-reference',
  'w5-n18-reference',
] as const);

export type W5N19AFutureResponsibility = (typeof W5_N19_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N19AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N19AArtifactKind;
  owner: W5N19AOwner;
  durabilityClass: W5N19ADurabilityClass;
  capabilityCategory: W5N19ACapabilityCategory;
  dependencyDirection?: W5N19ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N19Responsibility: W5N19AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesRetrySchedulingFunctional: boolean;
  authorizesW5N19Complete: boolean;
  persistenceResponsibility: W5N19APersistenceResponsibility;
  recoveryResponsibility: W5N19ARecoveryResponsibility;
  operationalContinuityResponsibility: W5N19AOperationalContinuityResponsibility;
  honestProductState: W5N19AHonestProductState;
  retrySchedulingClassification: W5N19ARetrySchedulingClassification;
  operationalVisibility: string;
  customerVisibility: string;
}>;

export const W5_N19_A_RETRY_SCHEDULING_INVENTORY: readonly W5N19AInventoryRow[] = Object.freeze([
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-platform-retry-scheduling-layer',
    artifact: 'Cross-channel Notification Retry Scheduling — notification-delivery owner',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — durable retry scheduling eligibility-timing anchors on notification-delivery; unified scheduling runtime still absent',
    honestyRequirement:
      'Retry scheduling extends notification-delivery only; no Scheduler Platform, Workflow Engine, or Event Bus',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-scheduling-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-notification-delivery-domain',
    artifact:
      'Notification Delivery bounded context — sole owner for retry scheduling foundation artifacts',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — notification-delivery owns channels, foundations, retry execution, and scheduling substrate path',
    honestyRequirement:
      'Retry scheduling remains a capability of notification-delivery; no new bounded context',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-pc06-routing-delivery',
    artifact: 'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    kind: 'ownership' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — PC-06 routing SoT; retry scheduling consumes routing, does not own it',
    honestyRequirement: 'No duplicate routing engine; PC-06 unchanged',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-w5-n18-retry-execution-consume',
    artifact: 'W5-N18 CLOSED retry execution foundation — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N18 CLOSED — retry execution inventory/persistence/recovery/continuity; scheduling builds on top',
    honestyRequirement: 'Retry execution ≠ retry scheduling; N18 not reopened',
    futureW5N19Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-w5-n12-scheduler-foundation-consume',
    artifact: 'W5-N12 CLOSED scheduler foundation — consumed; no Scheduler Platform',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N12 CLOSED — scheduler foundation consumed; N19 does not introduce Scheduler Platform',
    honestyRequirement: 'No Scheduler Platform; W5-N12 consumed only',
    futureW5N19Responsibility: 'w5-n12-reference' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n12-product-owner-close-record.md',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n12-reference' as const,
    recoveryResponsibility: 'w5-n12-reference' as const,
    operationalContinuityResponsibility: 'w5-n12-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-w5-n13-retry-foundation-consume',
    artifact: 'W5-N13 CLOSED retry foundation — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'W5-N13 CLOSED — retry anchors/recovery/continuity on notification-delivery',
    honestyRequirement: 'Retry foundation ≠ retry scheduling; N13 not reopened',
    futureW5N19Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-w5-n17-delivery-reliability-consume',
    artifact: 'W5-N17 CLOSED delivery reliability foundation — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'W5-N17 CLOSED — reliability anchors/recovery/continuity consumed',
    honestyRequirement: 'Delivery reliability ≠ retry scheduling; N17 not reopened',
    futureW5N19Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-reliability-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-secret-vault-consume',
    artifact: 'Secret Vault — credential owner consumed only',
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — Vault owns credentials; retry scheduling does not store secrets',
    honestyRequirement: 'No local secret store; no plaintext echo',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-security-review.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-connection-management-consume',
    artifact: 'Connection Management facade — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — operator connect surfaces consumed; ownership unchanged',
    honestyRequirement: 'Connection Management not redesigned',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-workspace-isolation-notifications',
    artifact: 'Workspace Isolation — retry scheduling state workspace-scoped',
    kind: 'ownership' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — Isolation boundary unchanged; fail closed on missing workspace',
    honestyRequirement: 'No cross-workspace retry scheduling state',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-security-review.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-notification-durable-queue',
    artifact: 'W3-O02 durable notification queue — substrate consumed',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — durable queue on notification-delivery; scheduling may mark eligibility after N19-b+',
    honestyRequirement: 'Queue substrate owner unchanged; not scheduler runtime',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'own-honest-product-boundaries',
    artifact: 'Honest Product boundaries for Retry Scheduling Foundation',
    kind: 'ownership' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus:
      'Documented — Retry Scheduling ≠ runtime / successful delivery / acceptance / receipt / guarantee',
    honestyRequirement: 'Binding Honest Product rules frozen at planning and inventory',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'documentation-only',
    customerVisibility: 'not customer-visible — documentation honesty',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-anchor',
    artifact:
      'W5-N18 retry execution anchors — workspace_notification_platform_retry_execution_anchors',
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-restart-recovery',
    artifact: 'W5-N18 retry execution restart recovery service',
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-restart-recovery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-continuity',
    artifact: 'W5-N18 retry execution operational continuity projection',
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-operational-continuity.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n12-scheduler-foundation',
    artifact: 'W5-N12 scheduler foundation — consumed not redesigned',
    kind: 'dependency' as const,
    owner: 'w5-n12-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n12-reference' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n12-product-owner-close-record.md',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n12-reference' as const,
    recoveryResponsibility: 'w5-n12-reference' as const,
    operationalContinuityResponsibility: 'w5-n12-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n13-retry-anchor',
    artifact: 'W5-N13 retry anchors consumed',
    kind: 'dependency' as const,
    owner: 'w5-n13-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'consume-w5-n17-reliability-anchor',
    artifact: 'W5-N17 reliability anchors consumed',
    kind: 'dependency' as const,
    owner: 'w5-n17-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry scheduling functional',
    futureW5N19Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-reliability-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'channel-w5-n01-telegram-anchor',
    artifact: 'W5-N01 Telegram notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry scheduling inventory',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-telegram-notification-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'channel-w5-n02-email-anchor',
    artifact: 'W5-N02 Email notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry scheduling inventory',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-email-notification-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'channel-w5-n03-webhook-anchor',
    artifact: 'W5-N03 Slack/Discord/Teams anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry scheduling inventory',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'channel-w5-n04-push-anchor',
    artifact: 'W5-N04 Push notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry scheduling inventory',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'missing-unified-platform-retry-scheduling-view',
    artifact: 'Unified cross-channel retry scheduling view — Platform Readiness projection',
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Not implemented — inventory only; deferred to W5-N19-d',
    honestyRequirement: 'Do not fabricate Platform Ready for retry scheduling from inventory',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-implementation-package.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n19-d' as const,
    honestProductState: 'not-implemented' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — not implemented',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'missing-retry-scheduling-persistence',
    artifact: 'Missing durable retry scheduling eligibility-timing anchors',
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved by W5-N19-b — see persist-notification-platform-retry-scheduling-anchor; gap row retained for inventory honesty',
    honestyRequirement: 'Does not authorize retry scheduling functional from slice a',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-scheduling-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — gap resolved by W5-N19-b',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'missing-retry-scheduling-recovery',
    artifact: 'Missing restart-safe retry scheduling recovery',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved by W5-N19-c — integrity-gated hydrate of retry scheduling anchors; gap row retained for inventory honesty',
    honestyRequirement: 'Does not authorize retry scheduling functional from slice a',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-scheduling-restart-recovery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — gap resolved by W5-N19-c',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'missing-retry-scheduling-operational-continuity',
    artifact: 'Missing retry scheduling operational continuity projection',
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Not implemented — planned for W5-N19-d',
    honestyRequirement: 'Does not authorize retry scheduling functional from slice a',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-implementation-package.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n19-d' as const,
    honestProductState: 'planned' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — planned',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'missing-retry-scheduling-ui',
    artifact: 'Missing operator retry scheduling UI',
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Not implemented — inventory only; deferred to later W5-N19 slices',
    honestyRequirement: 'Does not authorize retry scheduling functional from slice a',
    futureW5N19Responsibility: 'W5-N19-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-implementation-package.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'not-implemented' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — not implemented',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'persist-notification-platform-retry-scheduling-anchor',
    artifact:
      'WorkspaceNotificationPlatformRetrySchedulingAnchor — canonical retry scheduling anchors (W5-N19-b)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — workspace_notification_platform_retry_scheduling_anchors; anchor-recorded only; restart recovery via W5-N19-c; no retry scheduling runtime',
    honestyRequirement: 'Does not authorize retry scheduling functional from slice a',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-scheduling-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'runtime-pc06-resolve-delivery-routing',
    artifact:
      'PC-06 resolve-delivery-routing runtime — consumed for retry scheduling planning context',
    kind: 'runtime' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Exists — routing runtime; not retry scheduling runtime',
    honestyRequirement: 'Routing ≠ retry scheduling; no duplicate routing',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retrySchedulingClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'command-retry-scheduling-inventory-freeze',
    artifact: 'W5-N19-a inventory freeze command surface — documentation/conformance only',
    kind: 'command' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — machine inventory and conformance registry for slice a',
    honestyRequirement: 'Inventory command does not schedule or execute retries',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n19-a-retry-scheduling-inventory.ts',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-conformance',
    customerVisibility: 'not customer-visible — inventory only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'projection-platform-readiness-retry-scheduling-missing',
    artifact: 'Platform Readiness notificationPlatformRetryScheduling — missing (W5-N19-d)',
    kind: 'projection' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Not implemented — deferred to W5-N19-d',
    honestyRequirement: 'Do not fabricate Platform Ready for retry scheduling from inventory',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-implementation-package.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n19-d' as const,
    honestProductState: 'not-implemented' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — not implemented',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'operational-retry-scheduling-inventory-diagnostics',
    artifact: 'Retry scheduling inventory conformance diagnostics',
    kind: 'operational' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — buildRetrySchedulingDiagnostics for slice a',
    honestyRequirement: 'Diagnostics prove inventory completeness only — not retry scheduling',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n19-a-retry-scheduling.ts',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — conformance only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'operator-visible-retry-scheduling-none',
    artifact: 'Operator-visible retry scheduling surfaces — none in slice a',
    kind: 'operator-visible' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'None — customer-visible functionality is none for W5-N19-a',
    honestyRequirement: 'No operator UI claims retry scheduling from inventory',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/notification-retry-scheduling-overview.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n19-d' as const,
    honestProductState: 'not-implemented' as const,
    retrySchedulingClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'none',
    customerVisibility: 'none — inventory foundation only',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-runtime',
    artifact: 'Retry Scheduling ≠ retry execution runtime',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ retry execution runtime — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-successful-delivery',
    artifact: 'Retry Scheduling ≠ successful delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ successful delivery — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-provider-acceptance',
    artifact: 'Retry Scheduling ≠ provider acceptance',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ provider acceptance — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-recipient-receipt',
    artifact: 'Retry Scheduling ≠ recipient receipt',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ recipient receipt — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-exactly-once',
    artifact: 'Retry Scheduling ≠ exactly-once delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ exactly-once delivery — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-delivery-guarantee',
    artifact: 'Retry Scheduling ≠ delivery guarantee',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ delivery guarantee — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-live-trading',
    artifact: 'Retry Scheduling ≠ Live Trading',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Scheduling ≠ Live Trading — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-retry-execution-not-retry-scheduling',
    artifact: 'W5-N18 retry execution ≠ retry scheduling',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'W5-N18 retry execution ≠ retry scheduling — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-scheduler-foundation-not-scheduler-platform',
    artifact: 'W5-N12 scheduler foundation ≠ Scheduler Platform',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'W5-N12 scheduler foundation ≠ Scheduler Platform — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-platform-ready-requires-retry-scheduling-evidence',
    artifact: 'Platform Ready for retry scheduling requires foundation evidence',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement:
      'Platform Ready for retry scheduling requires foundation evidence — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'honesty-notifications-not-control-plane',
    artifact: 'Notifications are delivery-only — never a control plane',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement:
      'Notifications are delivery-only — never a control plane — binding for W5-N19',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retrySchedulingClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-retry-scheduling-implementation-slice-a',
    artifact: 'Retry scheduling implementation — out of slice a',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Retry scheduling implementation — out of slice a',
    futureW5N19Responsibility: 'out-of-scope-platform-retry-scheduling-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n19-b-durable-persistence',
    artifact: 'W5-N19-b durable scheduling persistence — completed as foundation slice',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus:
      'W5-N19-b durable persistence implemented — still OUT of slice-a authorization surface; does not authorize scheduling runtime',
    honestyRequirement: 'W5-N19-b durable scheduling persistence — not retry scheduling runtime',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-b-implementation-report.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n19-c-restart-safe-recovery',
    artifact: 'W5-N19-c restart-safe recovery — completed as foundation slice',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus:
      'W5-N19-c restart recovery implemented — still OUT of slice-a authorization surface; does not authorize scheduling runtime',
    honestyRequirement: 'W5-N19-c restart-safe recovery — not retry scheduling runtime',
    futureW5N19Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-c-implementation-report.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n19-d-operational-continuity',
    artifact: 'W5-N19-d operational continuity — deferred',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'W5-N19-d operational continuity — deferred',
    futureW5N19Responsibility: 'W5-N19-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n19-e-close-evidence',
    artifact: 'W5-N19-e Close Evidence — deferred',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'W5-N19-e Close Evidence — deferred',
    futureW5N19Responsibility: 'W5-N19-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-retry-execution-runtime',
    artifact: 'Retry execution runtime — out of W5-N19 foundation',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Retry execution runtime — out of W5-N19 foundation',
    futureW5N19Responsibility: 'out-of-scope-retry-execution-runtime' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-transport-execution',
    artifact: 'Transport execution — out of W5-N19 foundation',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Transport execution — out of W5-N19 foundation',
    futureW5N19Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-retry-policies-backoff',
    artifact: 'Retry policies / backoff algorithms — out',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Retry policies / backoff algorithms — out',
    futureW5N19Responsibility: 'out-of-scope-retry-policies' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-cron-scheduling',
    artifact: 'Cron scheduling — out',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Cron scheduling — out',
    futureW5N19Responsibility: 'out-of-scope-cron-scheduling' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-scheduler-platform',
    artifact: 'Scheduler Platform — forbidden (N12 consumed only)',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Scheduler Platform — forbidden (N12 consumed only)',
    futureW5N19Responsibility: 'out-of-scope-scheduler-platform' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-workflow-engine',
    artifact: 'Workflow Engine — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Workflow Engine — forbidden',
    futureW5N19Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-event-bus-product',
    artifact: 'Event Bus product — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Event Bus product — forbidden',
    futureW5N19Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-orchestration-platform',
    artifact: 'Orchestration platform — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Orchestration platform — forbidden',
    futureW5N19Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-notification-platform-complete',
    artifact: 'Notification Platform Complete — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Notification Platform Complete — not claimed',
    futureW5N19Responsibility: 'out-of-scope-notification-platform-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-live-notifications',
    artifact: 'Live Notifications — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Live Notifications — not claimed',
    futureW5N19Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-production-ready',
    artifact: 'Production Ready — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Production Ready — not claimed',
    futureW5N19Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-wave-5-complete',
    artifact: 'Wave 5 COMPLETE — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Wave 5 COMPLETE — not claimed',
    futureW5N19Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading Wave 6 — out of scope',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'Live Trading Wave 6 — out of scope',
    futureW5N19Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n18-reopen',
    artifact: 'W5-N18 reopen — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'W5-N18 reopen — forbidden',
    futureW5N19Responsibility: 'out-of-scope-w5-n18-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetrySchedulingFunctional: false as const,
    authorizesW5N19Complete: false as const,
    artifactId: 'out-w5-n12-reopen',
    artifact: 'W5-N12 reopen — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N19-a',
    honestyRequirement: 'W5-N12 reopen — forbidden',
    futureW5N19Responsibility: 'out-of-scope-w5-n12-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n19-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retrySchedulingClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
]);

export const W5_N19_A_BINDING_FINDINGS = Object.freeze({
  retrySchedulingFunctionalAuthorized: false,
  retrySchedulingFunctionsAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  w5N12SchedulerFoundationExists: true,
  w5N18RetryExecutionExists: true,
  w5N13RetryFoundationExists: true,
  w5N17DeliveryReliabilityExists: true,
  unifiedPlatformRetrySchedulingLayerMissing: true,
  retrySchedulingPersistenceMissing: false,
  retrySchedulingRecoveryMissing: false,
  retrySchedulingOperationalContinuityMissing: true,
  productionTransportsDeferred: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N19_A_EXPLICIT_OUT = Object.freeze([
  'retry-scheduling-implementation',
  'retry-execution-runtime',
  'production-transport-i/o',
  'notification-platform-complete',
  'live-trading-enablement',
  'live-notifications',
  'production-ready',
  'w5-n19-b',
  'w5-n19-c',
  'w5-n19-d',
  'w5-n19-e',
  'w5-n19-complete',
  'wave-5-complete',
  'scheduler-platform',
  'workflow-engine',
  'event-bus-product',
  'orchestration-platform',
  'retry-policies-backoff',
  'cron-scheduling',
  'w5-n12-reopen',
  'w5-n18-reopen',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N19_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateSchedulerSubsystem: false,
  duplicateRoutingEngine: false,
  schedulerPlatformIntroduced: false,
  workflowEngineIntroduced: false,
  retryPlatformIntroduced: false,
  eventBusProductIntroduced: false,
  orchestrationPlatformIntroduced: false,
  notificationControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  inventoryOnly: true,
  w5N19CompleteClaimed: false,
  retrySchedulingFunctionalClaimed: false,
  notificationPlatformCompleteClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  liveNotificationsClaimed: false,
  productionReadyClaimed: false,
  customerVisibleFeature: false,
  w5N12Reopened: false,
  w5N18Reopened: false,
} as const);

export const W5_N19_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible Notification Retry Scheduling functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'Per-channel N01…N04 notification anchors on notification-delivery owner',
    'W5-N05…N17 platform foundations on notification-delivery owner (consumed)',
    'W5-N12 scheduler foundation (consumed)',
    'W5-N13 platform retry anchors, recovery, and continuity (consumed)',
    'W5-N18 retry execution inventory, durable anchors, recovery, and continuity (consumed)',
    'W5-N19-b durable retry scheduling eligibility-timing anchors on notification-delivery',
    'W5-N19-c restart-safe hydrate of retry scheduling anchors on notification-delivery',
    'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    'PC-07 notification-product — per-channel settings and history',
    'Notification Durable Queue — W3-O02 on notification-delivery owner (consumed)',
    'W5-N01…N18-a machine inventories — foundation reference patterns',
    'Exchange Adapter / Wave 4 — reference only; untouched',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N19-d — Retry Scheduling Operational Continuity Foundation',
    'W5-N19-e — Package Close Evidence',
    'Operator retry scheduling honesty surfaces (when authorized)',
    'Unified cross-channel retry scheduling honesty projection (when authorized)',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Unified cross-channel platform retry scheduling layer',
    'Retry scheduling operational continuity projection',
    'Operator retry scheduling UI',
    'Retry scheduling runtime / scheduler execution',
    'Transport execution / provider runtimes',
    'Production transport I/O (TD-049 / TD-050)',
    'Notification Platform Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'Wave 6 — Live Trading (LT-02)',
    'Wave 7 — Anthropic / AI Gateway (out of W5-N19 scope)',
  ] as const),
} as const);

export const W5_N19_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze([
    'Retry Scheduling inventory baseline established',
    'Durable Retry Scheduling persistence foundation',
    'Retry Scheduling restart recovery foundation',
  ] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze(['W5-N19-d', 'W5-N19-e'] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N19AArtifactKind): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsNotificationRetrySchedulingSurvive(): readonly W5N19AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N19_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsNotificationRetrySchedulingEphemeral(): readonly W5N19AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N19_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N19ACapabilityCategory,
): readonly W5N19AInventoryRow[] {
  return W5_N19_A_RETRY_SCHEDULING_INVENTORY.filter((row) => row.capabilityCategory === category);
}
