/**
 * w5-n18-a — Notification Platform Retry Execution Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Notification Platform Retry Execution implementation. Not production transport I/O.
 * Not retry execution / transport execution / Retry Platform / Workflow Engine / Scheduler product / Event Bus.
 * Not W5-N18 COMPLETE. Not Notification Platform Complete. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - FOUNDATION: retry execution foundation layer artifact on notification-delivery owner (planned or reference).
 * - DURABLE: artifact persists across API restart today on existing owner.
 * - RECOVERABLE: artifact has defined restart recovery on existing owner or consumed foundation.
 * - EPHEMERAL: transient, missing retry execution layer, UI-only, process-local, or absent.
 * - OUT OF SCOPE: explicit deferral — must not authorize retry execution functional.
 *
 * W5-N01…N17 per-channel and platform foundations consumed as reference patterns only — not reopened.
 */

export const W5_N18_A_SLICE_ID = 'W5-N18-a' as const;

export const W5_N18_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'ai-gateway-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N18AOwner = (typeof W5_N18_A_ALLOWED_OWNERS)[number];

/** Existing notification / platform retry execution substrate owners — no new owner. */
export const W5_N18_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'platform-readiness',
] as const);

export const W5_N18_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N18AArtifactKind = (typeof W5_N18_A_ARTIFACT_KINDS)[number];

export const W5_N18_A_REQUIRED_ARTIFACT_KINDS = W5_N18_A_ARTIFACT_KINDS;

export const W5_N18_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N18ACapabilityCategory = (typeof W5_N18_A_CAPABILITY_CATEGORIES)[number];

export const W5_N18_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N18ADurabilityClass = (typeof W5_N18_A_DURABILITY_CLASSES)[number];

export const W5_N18_A_RETRY_CLASSIFICATIONS = Object.freeze([
  'FOUNDATION',
  'DURABLE',
  'RECOVERABLE',
  'EPHEMERAL',
  'OUT OF SCOPE',
] as const);

export type W5N18ARetryClassification = (typeof W5_N18_A_RETRY_CLASSIFICATIONS)[number];

export const W5_N18_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N18ADependencyDirection = (typeof W5_N18_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N18_A_PERSISTENCE_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'w5-n18-b',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N18APersistenceResponsibility =
  (typeof W5_N18_A_PERSISTENCE_RESPONSIBILITIES)[number];

export const W5_N18_A_RECOVERY_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'w5-n18-c',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N18ARecoveryResponsibility = (typeof W5_N18_A_RECOVERY_RESPONSIBILITIES)[number];

export const W5_N18_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES = Object.freeze([
  'platform-readiness',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'w5-n18-d',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N18AOperationalContinuityResponsibility =
  (typeof W5_N18_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES)[number];

export const W5_N18_A_HONEST_PRODUCT_STATES = Object.freeze([
  'not-implemented',
  'infrastructure-only',
  'implemented-today',
  'reserved-inactive',
  'planned',
  'deferred',
  'binding-honesty',
  'explicit-out',
  'not-applicable',
] as const);

export type W5N18AHonestProductState = (typeof W5_N18_A_HONEST_PRODUCT_STATES)[number];

export const W5_N18_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N18-b',
  'W5-N18-c',
  'W5-N18-d',
  'W5-N18-e',
  'honesty-baseline',
  'out-of-scope-live-trading',
  'out-of-scope-platform-retry-execution-slice-a',
  'out-of-scope-production-transport-i/o',
  'out-of-scope-exchange-adapter',
  'out-of-scope-w5-n18-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-notification-platform-complete',
  'out-of-scope-w5-n13-reopen',
  'out-of-scope-w5-n17-complete',
  'out-of-scope-ai-gateway',
  'out-of-scope-scheduler',
  'out-of-scope-retry-orchestration',
  'out-of-scope-dead-letter-processing',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
] as const);

export type W5N18AFutureResponsibility = (typeof W5_N18_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N18AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N18AArtifactKind;
  owner: W5N18AOwner;
  durabilityClass: W5N18ADurabilityClass;
  capabilityCategory: W5N18ACapabilityCategory;
  dependencyDirection?: W5N18ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N18Responsibility: W5N18AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesRetryExecutionFunctional: boolean;
  authorizesW5N18Complete: boolean;
  persistenceResponsibility: W5N18APersistenceResponsibility;
  recoveryResponsibility: W5N18ARecoveryResponsibility;
  operationalContinuityResponsibility: W5N18AOperationalContinuityResponsibility;
  honestProductState: W5N18AHonestProductState;
  retryClassification: W5N18ARetryClassification;
  operationalVisibility: string;
  customerVisibility: string;
}>;

export const W5_N18_A_RETRY_EXECUTION_INVENTORY: readonly W5N18AInventoryRow[] = Object.freeze([
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-platform-retry-execution-layer',
    artifact: 'Cross-channel Notification Platform Retry Execution — notification-delivery owner',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — CLOSED W5-N13 retry foundation and W5-N17 delivery reliability exist; unified retry execution layer absent',
    honestyRequirement:
      'Retry execution extends notification-delivery only; no Retry Platform, Workflow Engine, or Event Bus',
    futureW5N18Responsibility: 'W5-N18-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'w5-n18-b' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'not-implemented' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only — not operator-visible',
    customerVisibility: 'not customer-visible — not implemented',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-platform-retry-execution-persistence',
    artifact: 'Platform retry execution eligibility and sequencing anchors — workspace-scoped',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — workspace_notification_platform_retry_execution_anchors on notification-delivery owner',
    honestyRequirement:
      'Retry execution persistence on notification-delivery owner only; not a new persistence owner',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-notification-delivery-domain',
    artifact:
      'Notification Delivery bounded context — sole owner for retry execution foundation artifacts',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — notification-delivery owns channels, foundations, retry, and reliability substrates',
    honestyRequirement:
      'Retry execution remains a capability of notification-delivery; no new bounded context',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-pc06-routing-delivery',
    artifact: 'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    kind: 'ownership' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — PC-06 routing SoT; retry execution consumes routing, does not own it',
    honestyRequirement: 'No duplicate routing engine; PC-06 unchanged',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-w5-n13-retry-foundation-consume',
    artifact: 'W5-N13 CLOSED retry foundation — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N13 CLOSED — retry anchors/recovery/continuity on notification-delivery; execution builds on top',
    honestyRequirement: 'Retry foundation ≠ retry execution; N13 not reopened',
    futureW5N18Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-w5-n17-delivery-reliability-consume',
    artifact: 'W5-N17 CLOSED delivery reliability foundation — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N17 CLOSED — reliability anchors/recovery/continuity; retry execution depends on restart-safe reliability',
    honestyRequirement: 'Delivery reliability ≠ retry execution; N17 not reopened',
    futureW5N18Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-reliability-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-w5-n06-delivery-foundation-consume',
    artifact: 'W5-N06 CLOSED delivery foundation — consumed',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'W5-N06 CLOSED — delivery foundation consumed by retry execution planning',
    honestyRequirement: 'Delivery foundation not reopened',
    futureW5N18Responsibility: 'w5-n06-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-delivery-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n06-reference' as const,
    recoveryResponsibility: 'w5-n06-reference' as const,
    operationalContinuityResponsibility: 'w5-n06-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-w5-n08-queue-foundation-consume',
    artifact: 'W5-N08 CLOSED queue foundation — consumed',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'W5-N08 CLOSED — queue foundation consumed; not a Scheduler product',
    honestyRequirement: 'Queue foundation not reopened; no Scheduler product from N18',
    futureW5N18Responsibility: 'w5-n08-reference' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n08-reference' as const,
    recoveryResponsibility: 'w5-n08-reference' as const,
    operationalContinuityResponsibility: 'w5-n08-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-w5-n12-scheduler-foundation-consume',
    artifact: 'W5-N12 CLOSED scheduler foundation — consumed; no Scheduler product',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N12 CLOSED — scheduler foundation consumed; N18 does not introduce Scheduler product',
    honestyRequirement: 'No Scheduler product; W5-N12 consumed only',
    futureW5N18Responsibility: 'w5-n12-reference' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n13-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n12-reference' as const,
    recoveryResponsibility: 'w5-n12-reference' as const,
    operationalContinuityResponsibility: 'w5-n12-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-secret-vault-consume',
    artifact: 'Secret Vault — credential owner consumed only',
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — Vault owns credentials; retry execution does not store secrets',
    honestyRequirement: 'No local secret store; no plaintext echo',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-security-review.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-connection-management-consume',
    artifact: 'Connection Management facade — consumed not redesigned',
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — operator connect surfaces consumed; ownership unchanged',
    honestyRequirement: 'Connection Management not redesigned',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-workspace-isolation-notifications',
    artifact: 'Workspace Isolation — retry execution state workspace-scoped',
    kind: 'ownership' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — Isolation boundary unchanged; fail closed on missing workspace',
    honestyRequirement: 'No cross-workspace retry execution state',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-security-review.md',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-notification-durable-queue',
    artifact: 'W3-O02 durable notification queue — substrate consumed',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — durable queue on notification-delivery; retry execution may resume eligible work after N18-b+',
    honestyRequirement: 'Queue substrate owner unchanged; not transport execution',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-per-channel-foundations-reference',
    artifact: 'W5-N01…N04 per-channel foundations — reference only',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED — per-channel foundations consumed as reference; transport I/O deferred',
    honestyRequirement: 'Per-channel honesty preserved; no transport success from inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'own-honest-product-boundaries',
    artifact: 'Honest Product boundaries for Retry Execution Foundation',
    kind: 'ownership' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus:
      'Documented — Retry Execution ≠ successful delivery / acceptance / receipt / guarantee / exactly-once',
    honestyRequirement: 'Binding Honest Product rules frozen at planning and inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'documentation-only',
    customerVisibility: 'not customer-visible — documentation honesty',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n13-retry-anchor',
    artifact: 'W5-N13 retry anchors — workspace_notification_platform_retry_anchors',
    kind: 'dependency' as const,
    owner: 'w5-n13-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n13-retry-restart-recovery',
    artifact: 'W5-N13 retry restart recovery service',
    kind: 'dependency' as const,
    owner: 'w5-n13-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-restart-recovery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n13-retry-continuity',
    artifact: 'W5-N13 retry operational continuity projection',
    kind: 'dependency' as const,
    owner: 'w5-n13-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n13-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-operational-continuity.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n13-reference' as const,
    recoveryResponsibility: 'w5-n13-reference' as const,
    operationalContinuityResponsibility: 'w5-n13-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n17-reliability-anchor',
    artifact: 'W5-N17 reliability anchors — workspace_notification_platform_reliability_anchors',
    kind: 'dependency' as const,
    owner: 'w5-n17-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-reliability-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n17-reliability-restart-recovery',
    artifact: 'W5-N17 reliability restart recovery service',
    kind: 'dependency' as const,
    owner: 'w5-n17-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-reliability-restart-recovery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n17-reliability-continuity',
    artifact: 'W5-N17 reliability operational continuity projection',
    kind: 'dependency' as const,
    owner: 'w5-n17-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n17-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-reliability-operational-continuity.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n17-reference' as const,
    recoveryResponsibility: 'w5-n17-reference' as const,
    operationalContinuityResponsibility: 'w5-n17-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n06-delivery-anchor',
    artifact: 'W5-N06 delivery foundation anchors consumed',
    kind: 'dependency' as const,
    owner: 'w5-n06-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n06-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-delivery-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n06-reference' as const,
    recoveryResponsibility: 'w5-n06-reference' as const,
    operationalContinuityResponsibility: 'w5-n06-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n05-integration-anchor',
    artifact: 'W5-N05 integration foundation anchors consumed',
    kind: 'dependency' as const,
    owner: 'w5-n05-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n05-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/durable-notification-platform-integration-anchor.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n05-reference' as const,
    recoveryResponsibility: 'w5-n05-reference' as const,
    operationalContinuityResponsibility: 'w5-n05-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n14-dead-letter-persistence',
    artifact: 'W5-N14 dead-letter anchors consumed — not dead-letter processing',
    kind: 'dependency' as const,
    owner: 'w5-n14-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n14-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-dead-letter-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n14-reference' as const,
    recoveryResponsibility: 'w5-n14-reference' as const,
    operationalContinuityResponsibility: 'w5-n14-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n15-telemetry-persistence',
    artifact: 'W5-N15 telemetry anchors consumed — not telemetry platform',
    kind: 'dependency' as const,
    owner: 'w5-n15-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n15-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-telemetry-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n15-reference' as const,
    recoveryResponsibility: 'w5-n15-reference' as const,
    operationalContinuityResponsibility: 'w5-n15-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'consume-w5-n16-metrics-persistence',
    artifact: 'W5-N16 metrics anchors consumed — not metrics platform',
    kind: 'dependency' as const,
    owner: 'w5-n16-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner',
    honestyRequirement: 'Consumed not redesigned; does not authorize retry execution functional',
    futureW5N18Responsibility: 'w5-n16-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-metrics-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'w5-n16-reference' as const,
    recoveryResponsibility: 'w5-n16-reference' as const,
    operationalContinuityResponsibility: 'w5-n16-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'channel-w5-n01-telegram-anchor',
    artifact: 'W5-N01 Telegram notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry execution inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-telegram-notification-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'channel-w5-n02-email-anchor',
    artifact: 'W5-N02 Email notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry execution inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-email-notification-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'channel-w5-n03-webhook-anchor',
    artifact: 'W5-N03 Slack/Discord/Teams anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry execution inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'channel-w5-n04-push-anchor',
    artifact: 'W5-N04 Push notification anchors — reference',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'CLOSED per-channel foundation — reference only; transport I/O deferred',
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry execution inventory',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-unified-platform-retry-execution-view',
    artifact: 'Unified cross-channel retry execution view — Platform Readiness projection',
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Implemented — PlatformOperationalProjection exposes notificationPlatformRetryExecution continuity view',
    honestyRequirement:
      'Platform Readiness projection only; not unified functional retry execution layer',
    futureW5N18Responsibility: 'W5-N18-e' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n18-d' as const,
    honestProductState: 'not-implemented' as const,
    retryClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection',
    customerVisibility: 'operator — Retry Execution readiness via Platform Readiness',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-retry-eligibility-anchors',
    artifact: 'Missing durable retry eligibility anchors',
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved as durable anchor persistence (W5-N18-b); eligibility evaluation not executed',
    honestyRequirement: 'Does not authorize retry execution functional from slice a',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-retry-execution-sequencing',
    artifact: 'Missing retry execution sequencing foundation',
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved as durable anchor persistence (W5-N18-b); sequencing evaluation not executed',
    honestyRequirement: 'Does not authorize retry execution functional from slice a',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-restart-safe-retry-planning',
    artifact: 'Missing restart-safe retry execution planning',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — NotificationPlatformRetryExecutionRestartRecoveryService hydrates W5-N18-b anchors on module init',
    honestyRequirement:
      'Restart recovery restores canonical retry execution anchors only; operational continuity is W5-N18-d',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-restart-recovery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only — restart recovery hydrate',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-retry-execution-operational-continuity',
    artifact:
      'Retry execution operational continuity — buildNotificationPlatformRetryExecutionView',
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — buildNotificationPlatformRetryExecutionView derives readiness from W5-N18-c recovery record',
    honestyRequirement: 'Retry execution continuity follows restart recovery (W5-N18-c/d)',
    futureW5N18Responsibility: 'W5-N18-e' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-operational-continuity.ts',
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection',
    customerVisibility: 'operator — Retry Execution readiness via Platform Readiness',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'missing-retry-execution-ui',
    artifact: 'Missing operator retry execution UI',
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Not implemented — inventory only; deferred to later W5-N18 slices',
    honestyRequirement: 'Does not authorize retry execution functional from slice a',
    futureW5N18Responsibility: 'W5-N18-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-implementation-package.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'not-implemented' as const,
    retryClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — not implemented',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'persist-notification-platform-retry-execution-anchor',
    artifact:
      'WorkspaceNotificationPlatformRetryExecutionAnchor — canonical retry execution anchors (W5-N18-b)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — workspace_notification_platform_retry_execution_anchors; anchor-recorded only; no retry execution runtime',
    honestyRequirement: 'Does not authorize retry execution functional from slice a',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts',
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'runtime-pc06-resolve-delivery-routing',
    artifact:
      'PC-06 resolve-delivery-routing runtime — consumed for retry execution planning context',
    kind: 'runtime' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Exists — routing runtime; not retry execution runtime',
    honestyRequirement: 'Routing ≠ retry execution; no duplicate routing',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — infrastructure only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'command-retry-execution-inventory-freeze',
    artifact: 'W5-N18-a inventory freeze command surface — documentation/conformance only',
    kind: 'command' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — machine inventory and conformance registry for slice a',
    honestyRequirement: 'Inventory command does not execute retries',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n18-a-retry-execution-inventory.ts',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-conformance',
    customerVisibility: 'not customer-visible — inventory only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'projection-platform-readiness-retry-execution-missing',
    artifact: 'Platform Readiness notificationPlatformRetryExecution — projected (W5-N18-d)',
    kind: 'projection' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — notificationPlatformRetryExecution on PlatformOperationalProjection',
    honestyRequirement: 'Do not fabricate Platform Ready for retry execution from inventory',
    futureW5N18Responsibility: 'W5-N18-e' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection',
    customerVisibility: 'operator — Retry Execution readiness via Platform Readiness',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'operational-retry-execution-inventory-diagnostics',
    artifact: 'Retry execution inventory conformance diagnostics',
    kind: 'operational' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — buildRetryExecutionDiagnostics for slice a',
    honestyRequirement: 'Diagnostics prove inventory completeness only — not retry execution',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n18-a-retry-execution.ts',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — conformance only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'operator-visible-retry-execution-none',
    artifact: 'Operator-visible retry execution surfaces — none in slice a',
    kind: 'operator-visible' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'None — customer-visible functionality is none for W5-N18-a',
    honestyRequirement: 'No operator UI claims retry execution from inventory',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/notification-retry-execution-overview.md',
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n18-d' as const,
    honestProductState: 'not-implemented' as const,
    retryClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'none',
    customerVisibility: 'none — inventory foundation only',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-successful-delivery',
    artifact: 'Retry Execution ≠ successful delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ successful delivery — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-provider-acceptance',
    artifact: 'Retry Execution ≠ provider acceptance',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ provider acceptance — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-recipient-receipt',
    artifact: 'Retry Execution ≠ recipient receipt',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ recipient receipt — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-exactly-once',
    artifact: 'Retry Execution ≠ exactly-once delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ exactly-once delivery — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-delivery-guarantee',
    artifact: 'Retry Execution ≠ delivery guarantee',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ delivery guarantee — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-execution-not-live-trading',
    artifact: 'Retry Execution ≠ Live Trading',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'Retry Execution ≠ Live Trading — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-platform-ready-requires-retry-execution-evidence',
    artifact: 'Platform Ready for retry execution requires foundation evidence',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement:
      'Platform Ready for retry execution requires foundation evidence — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-retry-foundation-not-retry-execution',
    artifact: 'W5-N13 retry foundation ≠ retry execution',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'W5-N13 retry foundation ≠ retry execution — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-delivery-reliability-not-retry-execution',
    artifact: 'W5-N17 delivery reliability ≠ retry execution',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement: 'W5-N17 delivery reliability ≠ retry execution — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'honesty-workers-only-not-control-plane',
    artifact: 'Notifications are delivery-only — never a control plane',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory',
    honestyRequirement:
      'Notifications are delivery-only — never a control plane — binding for W5-N18',
    futureW5N18Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — honesty documentation',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-retry-execution-implementation-slice-a',
    artifact: 'Retry execution implementation — out of slice a',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Retry execution implementation — out of slice a',
    futureW5N18Responsibility: 'out-of-scope-platform-retry-execution-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n18-b-durable-eligibility-sequencing',
    artifact: 'W5-N18-b durable eligibility & sequencing — deferred',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'W5-N18-b durable eligibility & sequencing — deferred',
    futureW5N18Responsibility: 'W5-N18-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n18-c-restart-safe-planning',
    artifact: 'W5-N18-c restart-safe planning — deferred',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'W5-N18-c restart-safe planning — deferred',
    futureW5N18Responsibility: 'W5-N18-c' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n18-d-operational-continuity',
    artifact: 'W5-N18-d operational continuity — deferred',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'W5-N18-d operational continuity — deferred',
    futureW5N18Responsibility: 'W5-N18-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n18-e-close-evidence',
    artifact: 'W5-N18-e Close Evidence — assembled (not authorizing Complete)',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus:
      'Explicit OUT from slice a alone — Close Evidence assembled in W5-N18-e; does not authorize W5-N18 CLOSED',
    honestyRequirement:
      'W5-N18-e Close Evidence assembled; Final Package Integration Verification still deferred',
    futureW5N18Responsibility: 'W5-N18-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-transport-execution',
    artifact: 'Transport execution — out of W5-N18 foundation',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Transport execution — out of W5-N18 foundation',
    futureW5N18Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-smtp-telegram-discord-slack-webhook-runtime',
    artifact: 'Provider runtimes SMTP/Telegram/Discord/Slack/Webhook — out',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Provider runtimes SMTP/Telegram/Discord/Slack/Webhook — out',
    futureW5N18Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-dead-letter-processing',
    artifact: 'Dead-letter processing — out of W5-N18',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Dead-letter processing — out of W5-N18',
    futureW5N18Responsibility: 'out-of-scope-dead-letter-processing' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-retry-platform',
    artifact: 'Retry Platform product — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Retry Platform product — forbidden',
    futureW5N18Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-workflow-engine',
    artifact: 'Workflow Engine — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Workflow Engine — forbidden',
    futureW5N18Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-scheduler-product',
    artifact: 'Scheduler product — forbidden (N12 consumed only)',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Scheduler product — forbidden (N12 consumed only)',
    futureW5N18Responsibility: 'out-of-scope-scheduler' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-event-bus-product',
    artifact: 'Event Bus product — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Event Bus product — forbidden',
    futureW5N18Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-notification-platform-complete',
    artifact: 'Notification Platform Complete — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Notification Platform Complete — not claimed',
    futureW5N18Responsibility: 'out-of-scope-notification-platform-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-live-notifications',
    artifact: 'Live Notifications — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Live Notifications — not claimed',
    futureW5N18Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-production-ready',
    artifact: 'Production Ready — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Production Ready — not claimed',
    futureW5N18Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-wave-5-complete',
    artifact: 'Wave 5 COMPLETE — not claimed',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Wave 5 COMPLETE — not claimed',
    futureW5N18Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading Wave 6 — out of scope',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'Live Trading Wave 6 — out of scope',
    futureW5N18Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n13-reopen',
    artifact: 'W5-N13 reopen — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'W5-N13 reopen — forbidden',
    futureW5N18Responsibility: 'out-of-scope-w5-n13-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
  Object.freeze({
    authorizesRetryExecutionFunctional: false as const,
    authorizesW5N18Complete: false as const,
    artifactId: 'out-w5-n17-reopen',
    artifact: 'W5-N17 reopen — forbidden',
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N18-a',
    honestyRequirement: 'W5-N17 reopen — forbidden',
    futureW5N18Responsibility: 'out-of-scope-w5-n17-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n18-product-scope.md',
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only',
    customerVisibility: 'not customer-visible — explicit out',
  }),
]);

export const W5_N18_A_BINDING_FINDINGS = Object.freeze({
  retryExecutionFunctionalAuthorized: false,
  retryExecutionFunctionsAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  w5N13RetryFoundationExists: true,
  w5N17DeliveryReliabilityExists: true,
  w5N06DeliveryFoundationExists: true,
  w5N08QueueFoundationExists: true,
  w5N12SchedulerFoundationExists: true,
  unifiedPlatformRetryExecutionLayerMissing: true,
  retryExecutionEligibilityMissing: false,
  retryExecutionSequencingMissing: false,
  restartSafeRetryPlanningMissing: false,
  retryExecutionOperationalContinuityMissing: false,
  productionTransportsDeferred: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N18_A_EXPLICIT_OUT = Object.freeze([
  'retry-execution-implementation',
  'production-transport-i/o',
  'notification-platform-complete',
  'live-trading-enablement',
  'live-notifications',
  'production-ready',
  'w5-n18-b',
  'w5-n18-c',
  'w5-n18-d',
  'w5-n18-e',
  'w5-n18-complete',
  'wave-5-complete',
  'retry-platform',
  'workflow-engine',
  'scheduler-product',
  'event-bus-product',
  'dead-letter-processing-implementation',
  'w5-n13-reopen',
  'w5-n17-reopen',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N18_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRetrySubsystem: false,
  duplicateRoutingEngine: false,
  retryPlatformIntroduced: false,
  workflowEngineIntroduced: false,
  schedulerProductIntroduced: false,
  eventBusProductIntroduced: false,
  orchestrationPlatformIntroduced: false,
  notificationControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  inventoryOnly: true,
  w5N18CompleteClaimed: false,
  retryExecutionFunctionalClaimed: false,
  notificationPlatformCompleteClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  liveNotificationsClaimed: false,
  productionReadyClaimed: false,
  customerVisibleFeature: false,
  w5N13Reopened: false,
  w5N17Reopened: false,
} as const);

export const W5_N18_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible Notification Platform Retry Execution functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'Per-channel N01…N04 notification anchors on notification-delivery owner',
    'W5-N05…N12 platform foundations on notification-delivery owner (consumed)',
    'W5-N13 platform retry anchors, recovery, and continuity (consumed)',
    'W5-N14 dead-letter / W5-N15 telemetry / W5-N16 metrics foundations (consumed)',
    'W5-N17 delivery reliability anchors, recovery, and continuity (consumed)',
    'W5-N18-b durable retry execution anchors on notification-delivery owner',
    'W5-N18-c restart recovery hydrate for retry execution anchors on notification-delivery owner',
    'W5-N18-d retry execution operational continuity on Platform Readiness (derived)',
    'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    'PC-07 notification-product — per-channel settings and history',
    'Notification Durable Queue — W3-O02 on notification-delivery owner (consumed)',
    'W5-N01…N17-a machine inventories — foundation reference patterns',
    'Exchange Adapter / Wave 4 — reference only; untouched',
  ] as const),
  plannedCapabilities: Object.freeze(['Final Package Integration Verification'] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Unified cross-channel platform retry execution layer',
    'Operator retry execution UI',
    'Transport execution / provider runtimes',
    'Production transport I/O (TD-049 / TD-050)',
    'Notification Platform Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'Wave 6 — Live Trading (LT-02)',
    'Wave 7 — Anthropic / AI Gateway (out of W5-N18 scope)',
  ] as const),
} as const);

export const W5_N18_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze([
    'Retry Execution inventory baseline established',
    'Durable Retry Execution persistence foundation',
    'W5-N18-c — Restart Recovery Foundation',
    'W5-N18-d — Operational Continuity Foundation',
    'Notification Platform Retry Execution Package Close Evidence',
  ] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'Final Package Integration Verification',
    'Product Owner Final Close',
    'Retry execution runtime',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N18AArtifactKind): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsNotificationPlatformRetryExecutionSurvive(): readonly W5N18AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N18_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsNotificationPlatformRetryExecutionEphemeral(): readonly W5N18AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N18_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N18ACapabilityCategory,
): readonly W5N18AInventoryRow[] {
  return W5_N18_A_RETRY_EXECUTION_INVENTORY.filter((row) => row.capabilityCategory === category);
}
