/**
 * W5-N07-a — Notification Platform Dispatch Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Notification Platform Dispatch implementation. Not production transport I/O.
 * Not dispatcher / scheduler / retry / orchestration implementation.
 * Not W5-N07 COMPLETE. Not Notification Platform Complete. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Notification Delivery / Vault / Connection / Queue owners.
 * - EPHEMERAL: artifact is transient, per-channel-only, missing dispatch layer,
 *   UI-only, process-local, or absent — must not be treated as platform-dispatch truth.
 *
 * W5-N01…N04 per-channel foundations and CLOSED W5-N05 integration and W5-N06 delivery foundations
 * consumed as reference patterns only — not reopened.
 */

export const W5_N07_A_SLICE_ID = 'W5-N07-a' as const;

export const W5_N07_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'ai-gateway-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N07AOwner = (typeof W5_N07_A_ALLOWED_OWNERS)[number];

/** Existing notification / platform dispatch substrate owners — no new owner. */
export const W5_N07_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'platform-readiness',
] as const);

export const W5_N07_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N07AArtifactKind = (typeof W5_N07_A_ARTIFACT_KINDS)[number];

export const W5_N07_A_REQUIRED_ARTIFACT_KINDS = W5_N07_A_ARTIFACT_KINDS;

export const W5_N07_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N07ACapabilityCategory = (typeof W5_N07_A_CAPABILITY_CATEGORIES)[number];

export const W5_N07_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N07ADurabilityClass = (typeof W5_N07_A_DURABILITY_CLASSES)[number];

export const W5_N07_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N07ADependencyDirection = (typeof W5_N07_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N07_A_PERSISTENCE_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-b',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N07APersistenceResponsibility =
  (typeof W5_N07_A_PERSISTENCE_RESPONSIBILITIES)[number];

export const W5_N07_A_RECOVERY_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-c',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N07ARecoveryResponsibility = (typeof W5_N07_A_RECOVERY_RESPONSIBILITIES)[number];

export const W5_N07_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES = Object.freeze([
  'platform-readiness',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-d',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N07AOperationalContinuityResponsibility =
  (typeof W5_N07_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES)[number];

export const W5_N07_A_HONEST_PRODUCT_STATES = Object.freeze([
  'not-implemented',
  'infrastructure-only',
  'implemented-today',
  'reserved-inactive',
  'planned',
  'deferred',
  'binding-honesty',
  'explicit-out',
  'not-applicable',
] as const);

export type W5N07AHonestProductState = (typeof W5_N07_A_HONEST_PRODUCT_STATES)[number];

export const W5_N07_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N07-b',
  'W5-N07-c',
  'W5-N07-d',
  'W5-N07-e',
  'honesty-baseline',
  'out-of-scope-live-trading',
  'out-of-scope-platform-dispatch-slice-a',
  'out-of-scope-production-transport-i/o',
  'out-of-scope-exchange-adapter',
  'out-of-scope-w5-n07-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-notification-platform-complete',
  'out-of-scope-w5-n01-reopen',
  'out-of-scope-w5-n02-reopen',
  'out-of-scope-w5-n03-reopen',
  'out-of-scope-w5-n04-reopen',
  'out-of-scope-w5-n05-reopen',
  'out-of-scope-ai-gateway',
  'out-of-scope-dispatcher',
  'out-of-scope-scheduler',
  'out-of-scope-retry-orchestration',
  'out-of-scope-platform-dispatch-queue',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'out-of-scope-w5-n06-reopen',
] as const);

export type W5N07AFutureResponsibility = (typeof W5_N07_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N07AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N07AArtifactKind;
  owner: W5N07AOwner;
  durabilityClass: W5N07ADurabilityClass;
  capabilityCategory: W5N07ACapabilityCategory;
  dependencyDirection?: W5N07ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N07Responsibility: W5N07AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesPlatformDispatchFunctional: boolean;
  authorizesW5N07Complete: boolean;
  persistenceResponsibility: W5N07APersistenceResponsibility;
  recoveryResponsibility: W5N07ARecoveryResponsibility;
  operationalContinuityResponsibility: W5N07AOperationalContinuityResponsibility;
  honestProductState: W5N07AHonestProductState;
}>;

export const W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY: readonly W5N07AInventoryRow[] =
  Object.freeze([
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-platform-dispatch-layer',
      artifact: 'Cross-channel Notification Platform Dispatch — notification-delivery owner',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — per-channel N01…N04, CLOSED W5-N05 integration, and CLOSED W5-N06 delivery exist; unified platform dispatch layer absent',
      honestyRequirement:
        'Platform dispatch extends notification-delivery only; no second engine or dispatch execution engine',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: false as const,
      persistenceResponsibility: 'w5-n07-b' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-notification-delivery-domain',
      artifact: 'Notification Delivery — deliver / test / queue / connection domain owner',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Verified existing owner — sole delivery-domain SoT; consume not redesign',
      honestyRequirement: 'No second notification engine; Wave 5 extends adapters only',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-pc06-routing-delivery',
      artifact: 'PC-06 routing — delivery routing SoT consumed at platform delivery scope',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — resolve-delivery-routing; Wave 5 consumes unchanged at delivery scope',
      honestyRequirement: 'Routing owner unchanged; platform delivery consumes only',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-w5-n06-delivery-foundation-consume',
      artifact: 'W5-N06 Notification Platform Delivery foundation — consumed not reopened',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'W5-N06 CLOSED — delivery anchors, recovery, and continuity exist; dispatch builds on top',
      honestyRequirement: 'Delivery foundation consumed; no N06 redesign from dispatch slice a',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n06-product-owner-close-record.md',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n06-reference' as const,
      recoveryResponsibility: 'w5-n06-reference' as const,
      operationalContinuityResponsibility: 'w5-n06-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-secret-vault-consume',
      artifact: 'Vault — credential owner consumed by all channel adapters',
      kind: 'ownership' as const,
      owner: 'secret-vault' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented vault substrate — platform delivery retrieves only',
      honestyRequirement: 'Vault remains sole credential owner; no new secret types in slice a',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-connection-management-consume',
      artifact: 'Connection Management — operator connect facade for all channels',
      kind: 'ownership' as const,
      owner: 'connection-management' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Wave 2 owner — consumed; not redesigned by platform delivery',
      honestyRequirement: 'Connect product per channel; platform layer does not replace facade',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-workspace-isolation-notifications',
      artifact: 'Workspace Isolation — notification and delivery state per workspace',
      kind: 'ownership' as const,
      owner: 'workspace-isolation' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Consumed — workspace-bound delivery, prefs, anchors, connections',
      honestyRequirement: 'Cross-workspace delivery state leak forbidden',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-security-review.md',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-notification-durable-queue',
      artifact: 'Notification Durable Queue — W3-O02 work items (TD-045)',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — queue domain + durable store on notification-delivery owner; not platform delivery dispatcher',
      honestyRequirement: 'Queue survival ≠ platform delivery Complete; no dispatcher from slice a',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-per-channel-foundations-reference',
      artifact: 'Per-channel N01…N04 foundations — consumed not reopened',
      kind: 'ownership' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'W5-N01…N04 CLOSED — telegram/email/slack-discord-teams/push anchors on same owner',
      honestyRequirement: 'Platform delivery consumes channel artifacts; no redesign',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-w5-n05-integration-foundation-consume',
      artifact: 'W5-N05 Notification Platform Integration foundation — consumed not reopened',
      kind: 'ownership' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'W5-N05 CLOSED — integration anchors, recovery, continuity exist; delivery builds on top',
      honestyRequirement: 'Integration foundation consumed; no N05 redesign from delivery slice a',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n05-product-owner-close-record.md',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'own-honest-product-boundaries',
      artifact: 'Honest Product boundaries — Wave 5 platform dispatch invariants',
      kind: 'ownership' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 planning scope; inventory slice a catalogues only',
      honestyRequirement:
        'Platform dispatch foundation ≠ dispatch execution; dispatch foundation ≠ Live Trading; foundation ≠ production transport I/O',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'channel-w5-n01-telegram-anchor',
      artifact: 'W5-N01 Telegram notification anchor — workspace_telegram_notification_anchors',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Implemented — W5 N01 REFERENCE CLOSED; anchor on notification-delivery owner',
      honestyRequirement: 'N01 foundation consumed; not reopened by platform delivery',
      futureW5N07Responsibility: 'w5-n01-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-telegram-notification-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'channel-w5-n02-email-anchor',
      artifact: 'W5-N02 Email notification anchor — workspace_email_notification_anchors',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Implemented — W5 N02 REFERENCE CLOSED; anchor on notification-delivery owner',
      honestyRequirement: 'N02 foundation consumed; not reopened by platform delivery',
      futureW5N07Responsibility: 'w5-n02-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-email-notification-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'channel-w5-n03-webhook-anchor',
      artifact:
        'W5-N03 Slack/Discord/Teams anchor — workspace_slack_discord_teams_notification_anchors',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Implemented — W5 N03 REFERENCE CLOSED; anchor on notification-delivery owner',
      honestyRequirement: 'N03 foundation consumed; not reopened by platform delivery',
      futureW5N07Responsibility: 'w5-n03-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-slack-discord-teams-notification-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'channel-w5-n04-push-anchor',
      artifact: 'W5-N04 Push notification anchor — workspace_push_notification_anchors',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Implemented — W5 N04 REFERENCE CLOSED; anchor on notification-delivery owner',
      honestyRequirement: 'N04 foundation consumed; not reopened by platform delivery',
      futureW5N07Responsibility: 'w5-n04-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-push-notification-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n05-integration-anchor',
      artifact:
        'W5-N05 platform integration anchor — workspace_notification_platform_integration_anchors',
      kind: 'persistence-candidate' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus:
        'Implemented — W5-N05 CLOSED; integration anchor on notification-delivery owner',
      honestyRequirement: 'Integration anchor consumed; delivery does not reopen N05 persistence',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-integration-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n05-integration-restart-recovery',
      artifact:
        'W5-N05 platform integration restart recovery — NotificationPlatformIntegrationRestartRecoveryService',
      kind: 'runtime' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus:
        'Implemented — integration recovery exists; no platform delivery recovery service',
      honestyRequirement: 'Integration recovery consumed; delivery recovery is separate W5-N07-c',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/notification-platform-integration-restart-recovery.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n05-integration-operational-continuity',
      artifact:
        'W5-N05 platform integration operational continuity — buildNotificationPlatformIntegrationView',
      kind: 'operational' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — integration continuity projection exists; no delivery continuity builder',
      honestyRequirement: 'Integration continuity ≠ platform delivery Complete',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/notification-platform-integration-operational-continuity.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n05-integration-continuity-view',
      artifact:
        'Platform Readiness notificationPlatformIntegration — W5-N05-d integration projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — integration continuity in operational-continuity.service; not delivery layer',
      honestyRequirement: 'Integration Ready ≠ platform delivery Complete',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n06-delivery-continuity-view',
      artifact:
        'Platform Readiness notificationPlatformDelivery — W5-N06-d delivery projection consumed',
      kind: 'projection' as const,
      owner: 'w5-n06-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — delivery continuity in operational-continuity.service; not dispatch layer',
      honestyRequirement: 'Delivery Ready ≠ platform dispatch Complete',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n06-reference' as const,
      recoveryResponsibility: 'w5-n06-reference' as const,
      operationalContinuityResponsibility: 'w5-n06-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n06-delivery-restart-recovery',
      artifact:
        'W5-N06 platform delivery restart recovery — NotificationPlatformDeliveryRestartRecoveryService',
      kind: 'runtime' as const,
      owner: 'w5-n06-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus:
        'Implemented — delivery recovery exists; no platform dispatch recovery service',
      honestyRequirement: 'Delivery recovery consumed; dispatch recovery is separate W5-N07-c',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/notification-platform-delivery-restart-recovery.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n06-reference' as const,
      recoveryResponsibility: 'w5-n06-reference' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n06-delivery-operational-continuity',
      artifact:
        'W5-N06 platform delivery operational continuity — buildNotificationPlatformDeliveryView',
      kind: 'operational' as const,
      owner: 'w5-n06-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — delivery continuity projection exists; no dispatch continuity builder',
      honestyRequirement: 'Delivery continuity ≠ platform dispatch Complete',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/notification-platform-delivery-operational-continuity.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n06-reference' as const,
      recoveryResponsibility: 'w5-n06-reference' as const,
      operationalContinuityResponsibility: 'w5-n06-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n06-inventory-reference',
      artifact: 'W5-N06-a Notification Platform Delivery inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n06-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume delivery foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath:
        'apps/api/src/platform-conformance/w5-n06-a-notification-platform-delivery-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n06-reference' as const,
      recoveryResponsibility: 'w5-n06-reference' as const,
      operationalContinuityResponsibility: 'w5-n06-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-unified-platform-dispatch-view',
      artifact: 'Unified platform dispatch view — cross-channel Platform Ready dispatch projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — PlatformOperationalProjection has delivery view but no notificationPlatformDispatch field',
      honestyRequirement: 'Platform Ready at dispatch scope requires dispatch foundation evidence',
      futureW5N07Responsibility: 'W5-N07-d' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'w5-n07-d' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-restart-recovery',
      artifact: 'Platform dispatch restart recovery — hydrate dispatch anchors',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — delivery recovery exists; no NotificationPlatformDispatchRestartRecoveryService',
      honestyRequirement: 'Dispatch recovery requires durable dispatch anchors first (W5-N07-b)',
      futureW5N07Responsibility: 'W5-N07-c' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
      existsToday: false as const,
      persistenceResponsibility: 'w5-n07-b' as const,
      recoveryResponsibility: 'w5-n07-c' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-operational-continuity',
      artifact: 'Platform dispatch operational continuity — buildNotificationPlatformDispatchView',
      kind: 'operational' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — operational-continuity.service has no platform dispatch builder',
      honestyRequirement: 'Dispatch continuity follows dispatch recovery (W5-N07-c/d)',
      futureW5N07Responsibility: 'W5-N07-d' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'w5-n07-d' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-cross-channel-dispatch-honesty-unification',
      artifact:
        'Cross-channel honest dispatch rule unification — Platform Ready dispatch semantics',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — per-channel and delivery honesty rules exist; no unified platform dispatch rules',
      honestyRequirement:
        'Unification deferred to post-inventory slices; no fake Platform Ready at dispatch scope',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-validation-plan.md',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-dispatcher',
      artifact: 'Platform dispatch dispatcher — cross-channel dispatch execution orchestration',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no platform dispatch dispatcher; deliver() is sync per-channel only; OutboxDispatcher is event-processing only',
      honestyRequirement:
        'Dispatcher not implemented; inventory must not claim dispatch capability',
      futureW5N07Responsibility: 'out-of-scope-dispatcher' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-scheduler',
      artifact: 'Platform dispatch scheduler — deferred / quiet-hours dispatch orchestration',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — PC-06 quiet-hours routing only; no platform dispatch scheduler',
      honestyRequirement: 'Scheduler not implemented; routing quiet-hours ≠ dispatch scheduler',
      futureW5N07Responsibility: 'out-of-scope-scheduler' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-retry-orchestration',
      artifact: 'Platform dispatch retry orchestration — cross-channel retry policy engine',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — queue has retryable status; no platform dispatch retry orchestration',
      honestyRequirement: 'Queue retryable status ≠ platform dispatch retry implementation',
      futureW5N07Responsibility: 'out-of-scope-retry-orchestration' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-orchestration-layer',
      artifact:
        'Platform dispatch orchestration layer — unified cross-channel dispatch coordinator',
      kind: 'ephemeral-artifact' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Missing — no dispatch orchestration layer above delivery foundation and W3-O02 queue',
      honestyRequirement: 'Orchestration deferred; foundation inventory only in slice a',
      futureW5N07Responsibility: 'out-of-scope-dispatcher' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-implementation-package.md',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'continuity-telegram-notification-view',
      artifact: 'Platform Readiness telegramNotification — W5-N01-d per-channel projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — per-channel continuity; not platform delivery layer',
      honestyRequirement: 'Per-channel Ready ≠ Notification Platform Dispatch Complete',
      futureW5N07Responsibility: 'w5-n01-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'continuity-email-notification-view',
      artifact: 'Platform Readiness emailNotification — W5-N02-d per-channel projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — per-channel continuity; not platform delivery layer',
      honestyRequirement: 'Per-channel Ready ≠ Notification Platform Dispatch Complete',
      futureW5N07Responsibility: 'w5-n02-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'continuity-slack-discord-teams-view',
      artifact:
        'Platform Readiness slackDiscordTeamsNotification — W5-N03-d per-channel projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — per-channel continuity; not platform delivery layer',
      honestyRequirement: 'Per-channel Ready ≠ Notification Platform Dispatch Complete',
      futureW5N07Responsibility: 'w5-n03-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'continuity-push-notification-view',
      artifact: 'Platform Readiness pushNotification — W5-N04-d per-channel projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus: 'Implemented — per-channel continuity; not platform delivery layer',
      honestyRequirement: 'Per-channel Ready ≠ Notification Platform Dispatch Complete',
      futureW5N07Responsibility: 'w5-n04-reference' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-continuity.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'continuity-notification-queue-view',
      artifact: 'Platform Readiness notificationQueue — W3-O02-d aggregate projection',
      kind: 'projection' as const,
      owner: 'platform-readiness' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'observed-by' as const,
      currentStatus:
        'Implemented — queue continuity consumed; not platform delivery dispatcher queue',
      honestyRequirement: 'Queue continuity ≠ platform delivery Complete',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'runtime-pc06-resolve-delivery-routing',
      artifact:
        'resolve-delivery-routing — PC-06 routing + quiet-hours (platform delivery consumes)',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — routing SoT; all channels including reserved-inactive',
      honestyRequirement: 'Routing ≠ production transport; platform delivery consumes only',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'runtime-notification-channel-catalog-all',
      artifact:
        'NOTIFICATION_CHANNEL_CATALOG — telegram active; email/slack/discord/teams/push reserved',
      kind: 'state' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — multi-channel catalog; most channels reserved-inactive',
      honestyRequirement: 'Catalog truth must not imply platform delivery Complete',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'consumed-not-owned' as const,
      honestProductState: 'reserved-inactive' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'runtime-notification-delivery-deliver',
      artifact: 'NotificationDeliveryService.deliver() — sync pipeline all channels',
      kind: 'runtime' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'implemented-today' as const,
      currentStatus:
        'Implemented — reserved channels skip; only telegram has active transport path today; not platform dispatcher',
      honestyRequirement:
        'deliver() skip ≠ platform delivery foundation; production I/O TD-049/TD-050 deferred',
      futureW5N07Responsibility: 'out-of-scope-production-transport-i/o' as const,
      evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'implemented-today' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'rest-notification-product-pc07',
      artifact: 'PC-07 REST — notification channel settings, routing, delivery history',
      kind: 'command' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Implemented — product adapter; per-channel surfaces; no platform delivery UI',
      honestyRequirement: 'Product queries only; platform delivery UI deferred',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'apps/api/src/modules/notification-product/notification-product.service.ts',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'rest-pc07-channel-matrix',
      artifact: 'PC-07 Channel Matrix — multi-channel reserved-inactive honesty',
      kind: 'state' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Binding — most channels Not offered; telegram partial; platform delivery not implemented',
      honestyRequirement:
        'Matrix must not claim Notification Platform Complete or delivery foundation',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/pc-07-channel-matrix.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n01-inventory-reference',
      artifact: 'W5-N01-a Telegram notification inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n01-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n01-reference' as const,
      evidencePath: 'apps/api/src/platform-conformance/w5-n01-a-telegram-notification-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n02-inventory-reference',
      artifact: 'W5-N02-a Email notification inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n02-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n02-reference' as const,
      evidencePath: 'apps/api/src/platform-conformance/w5-n02-a-email-notification-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n03-inventory-reference',
      artifact: 'W5-N03-a Slack/Discord/Teams inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n03-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n03-reference' as const,
      evidencePath:
        'apps/api/src/platform-conformance/w5-n03-a-slack-discord-teams-notification-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n04-inventory-reference',
      artifact: 'W5-N04-a Push notification inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n04-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n04-reference' as const,
      evidencePath: 'apps/api/src/platform-conformance/w5-n04-a-push-notification-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'notification-delivery' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n05-inventory-reference',
      artifact: 'W5-N05-a Notification Platform Integration inventory — foundation reference',
      kind: 'dependency' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath:
        'apps/api/src/platform-conformance/w5-n05-a-notification-platform-integration-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-w5-n05-integration-foundation-closed',
      artifact: 'W5-N05 integration foundation — anchors, recovery, continuity CLOSED',
      kind: 'dependency' as const,
      owner: 'w5-n05-reference' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference — consumed not reopened',
      honestyRequirement: 'Consume foundation patterns; no redesign',
      futureW5N07Responsibility: 'w5-n05-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/domain/durable-notification-platform-integration-anchor.ts',
      existsToday: true as const,
      persistenceResponsibility: 'w5-n05-reference' as const,
      recoveryResponsibility: 'w5-n05-reference' as const,
      operationalContinuityResponsibility: 'w5-n05-reference' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-blocked-by-td049-td050',
      artifact: 'TD-049 / TD-050 — production transports deferred; blocks platform Complete',
      kind: 'dependency' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus:
        'Active gap — Telegram production Bot API + reserved channels; out of W5-N06 foundation scope',
      honestyRequirement: 'Platform delivery foundation ≠ production transport operational',
      futureW5N07Responsibility: 'out-of-scope-production-transport-i/o' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'deferred' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-exchange-adapter-untouched',
      artifact: 'Exchange Adapter / Wave 4 — not consumed; unchanged',
      kind: 'dependency' as const,
      owner: 'exchange-adapter' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'depends-on' as const,
      currentStatus: 'Reference only — Wave 5 must not modify exchange I/O',
      honestyRequirement: 'Notifications ≠ exchange connectivity; adapter untouched',
      futureW5N07Responsibility: 'out-of-scope-exchange-adapter' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-ai-gateway-out-of-scope',
      artifact: 'OpenRouter / AI Gateway (Wave 7 CM-17 path) — explicitly out of W5-N06 scope',
      kind: 'dependency' as const,
      owner: 'ai-gateway-deferred' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      dependencyDirection: 'blocked-by' as const,
      currentStatus: 'Out of scope — W5-N06 CM-18 is Notification Platform Dispatch only',
      honestyRequirement: 'Must not conflate Wave 7 OpenRouter with Wave 5 platform delivery',
      futureW5N07Responsibility: 'out-of-scope-ai-gateway' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-summary.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'deferred' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'dep-consumes-authentication',
      artifact: 'Authentication — signed-in operator for delivery surfaces',
      kind: 'dependency' as const,
      owner: 'authentication' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      dependencyDirection: 'consumes' as const,
      currentStatus: 'Consumed — fail closed when missing',
      honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-security-review.md',
      existsToday: true as const,
      persistenceResponsibility: 'consumed-not-owned' as const,
      recoveryResponsibility: 'consumed-not-owned' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-production-transport-delivery',
      artifact:
        'Production transport I/O at platform delivery scope — TD-049 / TD-050 resolution path',
      kind: 'command' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — platform delivery inventory only; transports remain deferred',
      honestyRequirement: 'Must not claim transports operational from platform delivery slice a',
      futureW5N07Responsibility: 'out-of-scope-production-transport-i/o' as const,
      evidencePath: 'docs/project/technical-debt.md',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'consume-w5-n06-delivery-anchor',
      artifact:
        'WorkspaceNotificationPlatformDeliveryAnchor — W5-N06 CLOSED delivery anchors consumed',
      kind: 'persistence-candidate' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'SURVIVE' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus:
        'Implemented — W5-N06 CLOSED; delivery anchors on notification-delivery owner; dispatch slice a consumes only',
      honestyRequirement: 'Delivery anchor consumed; dispatch anchors deferred to W5-N07-b',
      futureW5N07Responsibility: 'w5-n06-reference' as const,
      evidencePath:
        'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-delivery-anchor.repository.ts',
      existsToday: true as const,
      persistenceResponsibility: 'notification-delivery' as const,
      recoveryResponsibility: 'w5-n07-c' as const,
      operationalContinuityResponsibility: 'platform-readiness' as const,
      honestProductState: 'infrastructure-only' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'missing-platform-dispatch-ui',
      artifact: 'Operator UI — unified platform dispatch state across channels',
      kind: 'operator-visible' as const,
      owner: 'notification-product' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus: 'Missing — per-channel notification UI only; no platform dispatch dashboard',
      honestyRequirement: 'UI must not show Platform Ready without dispatch foundation evidence',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath: 'apps/web/src/notifications/NotificationChannelsView.tsx',
      existsToday: false as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'gap-delivery-vs-unified-platform-dispatch',
      artifact: 'Parallel gap — N01…N06 delivery foundations vs unified platform dispatch layer',
      kind: 'ephemeral-artifact' as const,
      owner: 'notification-delivery' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'not-implemented' as const,
      currentStatus:
        'Disconnected — per-channel, integration, and delivery foundations exist; unified platform dispatch layer absent',
      honestyRequirement:
        'Must converge only under notification-delivery dispatch layer at W5-N07-b; no duplicate SoT',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath:
        'apps/api/src/platform-conformance/w5-n05-a-notification-platform-integration-inventory.ts',
      existsToday: true as const,
      persistenceResponsibility: 'none-missing' as const,
      recoveryResponsibility: 'none-missing' as const,
      operationalContinuityResponsibility: 'none-missing' as const,
      honestProductState: 'not-implemented' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'op-w5-n07-planning-approved',
      artifact: 'W5-N06 Planning Package — APPROVED; slice a inventory only',
      kind: 'operational' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus:
        'Planning APPROVED — slice a inventory only; platform dispatch implementation deferred',
      honestyRequirement: 'Planning Approval ≠ Notification Platform Dispatch implemented',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-approval.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'planned' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'honesty-platform-dispatch-not-live-trading',
      artifact: 'Platform dispatch foundation ≠ Live Trading; dispatch ≠ order submission',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 scope',
      honestyRequirement: 'Platform delivery outside process ≠ live capital trading enablement',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'honesty-platform-ready-requires-dispatch-evidence',
      artifact: 'Platform Ready label requires cross-channel dispatch foundation evidence',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 scope',
      honestyRequirement:
        'No fake Platform Ready from per-channel, integration, or delivery foundations alone',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'honesty-foundation-not-transport-i/o',
      artifact: 'Platform delivery foundation ≠ production transport I/O operational',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 scope',
      honestyRequirement:
        'Durable dispatch anchors ≠ SMTP/webhook/push production dispatch execution',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'honesty-delivery-not-dispatch-complete',
      artifact: 'W5-N05 integration Close ≠ Notification Platform Dispatch Complete',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 scope',
      honestyRequirement: 'Delivery foundation is separate from dispatch foundation',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'honesty-dispatch-only-not-control-plane',
      artifact: 'Notifications delivery-only — never trading control plane',
      kind: 'honesty-boundary' as const,
      owner: 'wave-5-documentation' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'infrastructure-only' as const,
      currentStatus: 'Binding — frozen in W5-N06 scope',
      honestyRequirement: 'Dispatch foundation must not enable live orders',
      futureW5N07Responsibility: 'honesty-baseline' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: true as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'binding-honesty' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-platform-dispatch-implementation-slice-a',
      artifact: 'Notification Platform Dispatch implementation in W5-N07-a',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — inventory only; W5-N07-b implements durable dispatch',
      futureW5N07Responsibility: 'out-of-scope-platform-dispatch-slice-a' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-implementation-package.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n07-b-durable-dispatch',
      artifact: 'W5-N07-b — Durable Notification Platform Dispatch Foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Deferred — named slice; not opened from slice a',
      futureW5N07Responsibility: 'W5-N07-b' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-summary.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n07-c-restart-recovery',
      artifact: 'W5-N07-c — Platform dispatch restart recovery',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Deferred — hydrate dispatch anchors post W5-N07-b',
      futureW5N07Responsibility: 'W5-N07-c' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-summary.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n07-d-operational-continuity',
      artifact: 'W5-N07-d — Platform dispatch operational continuity',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Deferred — continuity projection post dispatch recovery',
      futureW5N07Responsibility: 'W5-N07-d' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-summary.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n07-e-close-evidence',
      artifact: 'W5-N07-e — Security verification + package Close evidence',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'planned' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Deferred — Close evidence assembly post implementation slices',
      futureW5N07Responsibility: 'W5-N07-e' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-planning-summary.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-notification-platform-complete',
      artifact: 'Notification Platform Complete declaration',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — requires N01…N06 Close + PO act + production transports',
      futureW5N07Responsibility: 'out-of-scope-notification-platform-complete' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-live-trading-wave6',
      artifact: 'Live Trading / live order submission (Wave 6)',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Out of W5-N06 platform delivery scope',
      futureW5N07Responsibility: 'out-of-scope-live-trading' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-dispatcher-implementation',
      artifact: 'Platform delivery dispatcher implementation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden from slice a — no dispatcher',
      futureW5N07Responsibility: 'out-of-scope-dispatcher' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-implementation-package.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-scheduler-implementation',
      artifact: 'Platform delivery scheduler implementation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden from slice a — no scheduler',
      futureW5N07Responsibility: 'out-of-scope-scheduler' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-implementation-package.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-retry-orchestration-implementation',
      artifact: 'Platform delivery retry orchestration implementation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden from slice a — no retry orchestration',
      futureW5N07Responsibility: 'out-of-scope-retry-orchestration' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-implementation-package.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-platform-dispatch-queue-implementation',
      artifact: 'Platform dispatch queue / dispatch work queue orchestration implementation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement:
        'Forbidden from slice a — W3-O02 queue consumed only; no dispatch orchestration queue',
      futureW5N07Responsibility: 'out-of-scope-platform-dispatch-queue' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n07-product-scope.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n01-reopen',
      artifact: 'Reopen W5-N01 Telegram Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N01 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n01-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n01-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n02-reopen',
      artifact: 'Reopen W5-N02 Email Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N02 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n02-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n03-reopen',
      artifact: 'Reopen W5-N03 Slack/Discord/Teams Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N03 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n03-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n03-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n04-reopen',
      artifact: 'Reopen W5-N04 Push Notification foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N04 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n04-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n06-reopen',
      artifact: 'Reopen W5-N06 Notification Platform Delivery foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N06 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n06-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n06-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
    Object.freeze({
      authorizesPlatformDispatchFunctional: false as const,
      authorizesW5N07Complete: false as const,
      artifactId: 'out-w5-n05-reopen',
      artifact: 'Reopen W5-N05 Notification Platform Integration foundation',
      kind: 'explicit-out' as const,
      owner: 'release-governance' as const,
      durabilityClass: 'EPHEMERAL' as const,
      capabilityCategory: 'future-roadmap' as const,
      currentStatus: 'Deferred or forbidden — not authorized from slice a',
      honestyRequirement: 'Forbidden — W5-N05 Closed; consume patterns only',
      futureW5N07Responsibility: 'out-of-scope-w5-n05-reopen' as const,
      evidencePath: 'docs/project/version-3/wave-5/w5-n05-product-owner-close-record.md',
      existsToday: false as const,
      persistenceResponsibility: 'not-applicable' as const,
      recoveryResponsibility: 'not-applicable' as const,
      operationalContinuityResponsibility: 'not-applicable' as const,
      honestProductState: 'explicit-out' as const,
    }),
  ]);
export const W5_N07_A_BINDING_FINDINGS = Object.freeze({
  platformDispatchFunctionalAuthorized: false,
  platformDispatchFunctionsAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  w5N05IntegrationFoundationExists: true,
  w5N06DeliveryFoundationExists: true,
  unifiedPlatformDispatchLayerMissing: true,
  platformDispatchAnchorsMissing: true,
  productionTransportsDeferred: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N07_A_EXPLICIT_OUT = Object.freeze([
  'platform-dispatch-implementation',
  'production-transport-i/o',
  'notification-platform-complete',
  'live-trading-enablement',
  'w5-n07-b',
  'w5-n07-c',
  'w5-n07-d',
  'w5-n07-e',
  'w5-n07-complete',
  'wave-5-complete',
  'w5-n01-reopen',
  'w5-n02-reopen',
  'w5-n03-reopen',
  'w5-n04-reopen',
  'w5-n05-reopen',
  'w5-n06-reopen',
  'dispatcher-implementation',
  'scheduler-implementation',
  'retry-orchestration-implementation',
  'platform-dispatch-queue-implementation',
  'ai-gateway-scope',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N07_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRoutingEngine: false,
  notificationControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  w5N07CompleteClaimed: false,
  platformDispatchFunctionalClaimed: false,
  notificationPlatformCompleteClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  customerVisibleFeature: false,
  dispatcherImplemented: false,
  schedulerImplemented: false,
  retryOrchestrationImplemented: false,
  w5N01Reopened: false,
  w5N02Reopened: false,
  w5N03Reopened: false,
  w5N04Reopened: false,
  w5N05Reopened: false,
  w5N06Reopened: false,
} as const);

export const W5_N07_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible Notification Platform Dispatch functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'Per-channel N01…N04 notification anchors on notification-delivery owner',
    'W5-N05 platform integration anchors, recovery, and continuity on notification-delivery owner',
    'W5-N06 platform delivery anchors, recovery, and continuity on notification-delivery owner',
    'Platform Readiness notificationPlatformDelivery — W5-N06-d delivery projection',
    'Per-channel, integration, and delivery operational continuity projections in Platform Readiness',
    'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    'PC-07 notification-product — per-channel settings and history',
    'NOTIFICATION_CHANNEL_CATALOG — multi-channel with reserved-inactive honesty',
    'Notification Durable Queue — W3-O02 on notification-delivery owner (consumed, not dispatch orchestration)',
    'W5-N01…N06-a machine inventories — foundation reference patterns',
    'Exchange Adapter / Wave 4 — reference only; untouched',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N07-b — Durable Notification Platform Dispatch Foundation',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Unified cross-channel platform dispatch layer',
    'Platform dispatch restart recovery',
    'Platform dispatch operational continuity projection',
    'Cross-channel honest dispatch rule unification',
    'Platform dispatch dispatcher execution',
    'Platform dispatch queue orchestration',
    'Platform dispatch retry orchestration',
    'Platform dispatch scheduler',
    'Operator platform dispatch UI',
    'Production transport I/O (TD-049 / TD-050)',
    'Notification Platform Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'W5-N07-c — Platform dispatch restart recovery',
    'W5-N07-d — Platform dispatch operational continuity',
    'W5-N07-e — Package Close Evidence',
    'Wave 6 — Live Trading (LT-02)',
    'Wave 7 — Gemini / AI Gateway (out of W5-N07 scope)',
  ] as const),
} as const);

export const W5_N07_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze(['Notification Platform Dispatch Inventory Foundation'] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N07-b — Durable Notification Platform Dispatch Foundation',
    'W5-N07-c — Notification Platform Dispatch Restart Recovery Foundation',
    'W5-N07-d — Notification Platform Dispatch Operational Continuity Foundation',
    'W5-N07-e — Package Close Evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N07AArtifactKind): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter(
    (row) => row.durabilityClass === 'SURVIVE',
  );
}

export function rowsEphemeral(): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter(
    (row) => row.durabilityClass === 'EPHEMERAL',
  );
}

export function rowsNotificationPlatformDispatchSurvive(): readonly W5N07AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N07_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsNotificationPlatformDispatchEphemeral(): readonly W5N07AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N07_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter(
    (row) => row.kind === 'honesty-boundary',
  );
}

export function rowsExplicitOut(): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter(
    (row) => row.kind === 'explicit-out',
  );
}

export function rowsByCapabilityCategory(
  category: W5N07ACapabilityCategory,
): readonly W5N07AInventoryRow[] {
  return W5_N07_A_NOTIFICATION_PLATFORM_DISPATCH_INVENTORY.filter(
    (row) => row.capabilityCategory === category,
  );
}
