/**
 * W5-N04-a — Push Notification Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Push implementation. Not Web Push implementation. Not FCM implementation.
 * Not browser delivery. Not device token persistence. Not W5-N04 COMPLETE. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Notification Delivery / Vault / Connection / Queue owners.
 * - EPHEMERAL: artifact is transient, stub, reserved-inactive transport, UI-only,
 *   process-local, or missing — must not be treated as production Push truth.
 *
 * W5-N01 Telegram, W5-N02 Email, and W5-N03 Slack/Discord/Teams foundations consumed as reference patterns only.
 */

export const W5_N04_A_SLICE_ID = 'W5-N04-a' as const;

export const W5_N04_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N04AOwner = (typeof W5_N04_A_ALLOWED_OWNERS)[number];

/** Existing notification / Push substrate owners — no new owner. */
export const W5_N04_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
] as const);

export const W5_N04_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N04AArtifactKind = (typeof W5_N04_A_ARTIFACT_KINDS)[number];

export const W5_N04_A_REQUIRED_ARTIFACT_KINDS = W5_N04_A_ARTIFACT_KINDS;

export const W5_N04_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N04ACapabilityCategory = (typeof W5_N04_A_CAPABILITY_CATEGORIES)[number];

export const W5_N04_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N04ADurabilityClass = (typeof W5_N04_A_DURABILITY_CLASSES)[number];

export const W5_N04_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N04ADependencyDirection = (typeof W5_N04_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N04_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N04-b',
  'W5-N04-c',
  'W5-N04-d',
  'W5-N04-e',
  'honesty-baseline',
  'out-of-scope-live-trading',
  'out-of-scope-push-slice-a',
  'out-of-scope-push-control-plane',
  'out-of-scope-exchange-adapter',
  'out-of-scope-w5-n04-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-w5-n01-reopen',
  'out-of-scope-w5-n02-reopen',
  'out-of-scope-w5-n03-reopen',
  'out-of-scope-browser-delivery-slice-a',
  'out-of-scope-fcm-slice-a',
  'out-of-scope-device-token-slice-a',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
] as const);

export type W5N04AFutureResponsibility = (typeof W5_N04_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N04AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N04AArtifactKind;
  owner: W5N04AOwner;
  durabilityClass: W5N04ADurabilityClass;
  capabilityCategory: W5N04ACapabilityCategory;
  dependencyDirection?: W5N04ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N04Responsibility: W5N04AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesPushRealDelivery: boolean;
  authorizesW5N04Complete: boolean;
}>;

/**
 * Frozen inventory of Push notification transport surfaces,
 * notification delivery paths, vault/connection substrates, operator-visible
 * artifacts, platform dependencies, ownership boundaries, and honesty rules
 * for Wave 5 slice W5-N04-a.
 */
export const W5_N04_A_PUSH_NOTIFICATION_INVENTORY: readonly W5N04AInventoryRow[] = Object.freeze([
  // ── Ownership surfaces (required minimum) ────────────────────────────────
  Object.freeze({
    artifactId: 'own-push-transport',
    artifact: 'Push transport — Notification Delivery adapter owner (extend only)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Verified existing owner — push channel reserved-inactive today; W5-N04-b extends to Web Push/FCM I/O',
    honestyRequirement:
      'Transport I/O owned by notification-delivery; connection-management is connect product only',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-delivery-domain',
    artifact: 'Notification Delivery — deliver / test / queue / connection domain owner',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Verified existing owner — sole delivery-domain SoT; consume not redesign',
    honestyRequirement: 'No second notification engine; Wave 5 extends adapters only',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-delivery-pipeline',
    artifact: 'Delivery pipeline — deliver() → routing → channel adapter → history/queue',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented sync pipeline — push routes skip with channel-reserved',
    honestyRequirement: 'Pipeline exists; production push round-trip is W5-N04-b',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-persistence',
    artifact: 'Notification persistence — DurableNotificationStore (history + queue snapshot)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — W3-O01 history + W3-O02-b queue on existing owner',
    honestyRequirement: 'Persistence ≠ production transport; no new persistence owner',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-secret-vault-push',
    artifact: 'Vault — HoldableSecretType VAPID/FCM credential owner (Push types absent)',
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented vault substrate — no VAPID/FCM/Push secret types in holdable catalog today',
    honestyRequirement:
      'Vault remains sole credential owner; adapter retrieve-only at W5-N04-b; no Push types yet',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-connection-management-push',
    artifact: 'Connection Management — operator connect product facade for Push channel',
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Wave 2 owner — no Push connection catalog entries consumed by delivery today',
    honestyRequirement:
      'Connect product follows N01/N02/N03 patterns at W5-N04-b; facade not redesigned',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-workspace-isolation-notifications',
    artifact: 'Workspace Isolation — notification credentials and state per workspace',
    kind: 'ownership' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Consumed — workspace-bound delivery, prefs, and connections',
    honestyRequirement: 'Cross-workspace push bind, device token, or send forbidden',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-security-review.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-user-notification-preferences',
    artifact: 'User notification preferences — routing inputs including push enablement',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — type routing, quiet hours, channel enablement (push reserved)',
    honestyRequirement: 'Preferences drive routing only; not transport or vault owner',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-device-token-registry',
    artifact: 'Device token registry — workspace-scoped browser/device registration (planned)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no device token store, schema, or repository; planned under notification-delivery owner at W5-N04-b',
    honestyRequirement:
      'Device registry must not be invented in slice a; no persistence owner drift',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-durable-queue',
    artifact: 'Notification Durable Queue — W3-O02 work items (TD-045)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — queue domain + durable store; sync deliver() still terminal',
    honestyRequirement: 'Queue survival ≠ production push send; distinct from push I/O',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-honest-product-boundaries',
    artifact: 'Honest Product boundaries — Wave 5 Push delivery-only invariants',
    kind: 'ownership' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — frozen in W5-N04 planning scope; inventory slice a catalogues only',
    honestyRequirement:
      'Real delivery ≠ Live Trading; push ≠ control plane; reserved-inactive ≠ Connected',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Push artifact surfaces ───────────────────────────────────────────────
  Object.freeze({
    artifactId: 'push-device-browser-binding-disclosure',
    artifact:
      'Push device/browser binding — PC-07 disclosure field (Device, Browser; not collected)',
    kind: 'state' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Disclosure only — RESERVED_CHANNEL_REQUIRED_FIELDS lists Device, Browser; configurable=false',
    honestyRequirement:
      'Device/browser binding must not be treated as registered push device today',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-product/notification-channel.view.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-vapid-fcm-vault-absent',
    artifact: 'VAPID/FCM credentials — vault-backed (no HoldableSecretType for Push today)',
    kind: 'persistence-candidate' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — holdable-secret-type has no VAPID/FCM/Push types',
    honestyRequirement: 'Credential storage deferred to W5-N04-b; vault retrieve-only at adapter',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-channel-mapping-routing',
    artifact: 'Push channel mapping — prefs typeRouting channels[] includes push when enabled',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented routing inputs — push in NOTIFICATION_CHANNELS; reserved-inactive skips delivery',
    honestyRequirement: 'Routing mapping ≠ push notification delivery',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-web-push-endpoint-transport',
    artifact: 'Web Push endpoint — outbound browser push HTTP transport (missing)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no Web Push adapter; no push service endpoint I/O; channel-reserved skip only',
    honestyRequirement: 'Web Push I/O is W5-N04-b; SSRF allowlist required at implementation',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-fcm-endpoint-transport',
    artifact: 'FCM endpoint — outbound Firebase Cloud Messaging transport (missing)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no FCM adapter; no Firebase HTTP v1 I/O; channel-reserved skip only',
    honestyRequirement: 'FCM I/O is W5-N04-b; provider endpoint allowlist required',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-browser-registration',
    artifact: 'Browser registration — Service Worker / PushManager subscription capture (missing)',
    kind: 'command' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no browser registration REST, no web push subscription endpoint, no device token capture',
    honestyRequirement: 'Browser registration deferred to W5-N04-b; no fake device registry',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/web/src/notifications/NotificationChannelDetailPage.tsx',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-device-token-registry-store',
    artifact: 'Device token registry — workspace-scoped push subscription persistence (missing)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no prisma-push-device-token.repository; no device token table or anchor',
    honestyRequirement: 'Device token SoT is W5-N04-b on notification-delivery owner only',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'push-delivery-metadata-attempts',
    artifact: 'Push delivery metadata — ChannelDeliveryAttempt with channel-reserved skipReason',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — push attempts record channel-reserved skipReason when routed',
    honestyRequirement: 'Skip metadata must not be relabeled as delivered to device',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Shared substrate surfaces ────────────────────────────────────────────
  Object.freeze({
    artifactId: 'shared-notification-durable-queue',
    artifact: 'Shared notification queue — W3-O02 durable work items for all channels',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — pending|in-flight|retryable states; not push execution',
    honestyRequirement: 'Queue durability ≠ Push notification delivery Complete',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'shared-delivery-result-metadata',
    artifact: 'Shared delivery metadata — DeliveryResult immutable record with channel attempts',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — deliveryId, attempts[], outcome; push channel attempts show channel-reserved',
    honestyRequirement: 'Delivery metadata records skip truth; not vendor delivery proof for push',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'shared-user-notification-preferences',
    artifact: 'Shared user preferences — channel enablement for push',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — channels.push boolean enablement in prefs',
    honestyRequirement: 'Preference enablement ≠ push transport active',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'shared-workspace-bindings',
    artifact: 'Shared workspace bindings — workspaceId scoped prefs, deliveries, and connections',
    kind: 'state' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Consumed — all notification state keyed by workspaceId',
    honestyRequirement: 'Cross-workspace push credential bind or send forbidden',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-security-review.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'shared-integrity-delivery-result-immutable',
    artifact: 'Shared integrity metadata — DeliveryResult deep-freeze immutable delivery record',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — createDeliveryResult deep-freezes attempts and outcome',
    honestyRequirement: 'Immutable record preserves honest skip/deliver truth for push channel',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'shared-integrity-queue-correlation',
    artifact:
      'Shared integrity metadata — queue item deliveryId correlation queue ↔ DeliveryResult',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — queueItem.deliveryId set on deliver() completion',
    honestyRequirement: 'Correlation supports audit; not push delivery proof',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Runtime / transport (reserved-inactive today) ────────────────────────
  Object.freeze({
    artifactId: 'runtime-reserved-inactive-push-adapter',
    artifact: 'ReservedInactiveChannelAdapter — push channel port (no Web Push/FCM I/O)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — active=false; send() returns channel-reserved skip',
    honestyRequirement: 'Reserved-inactive must not be labeled production Push delivery',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-delivery-deliver',
    artifact: 'NotificationDeliveryService.deliver() — sync terminal delivery (push skip path)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus:
      'Implemented — push routes get channel-reserved skip; records history + queue row',
    honestyRequirement: 'deliver() skip ≠ notification reached browser/device',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-resolve-delivery-routing-pc06',
    artifact: 'resolve-delivery-routing.ts — PC-06 routing + quiet-hours evaluation',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — type/channel routing SoT; push in routes when enabled in prefs',
    honestyRequirement: 'Routing owner remains PC-06; Wave 5 must not redesign routing',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-push-channel-boundary-inactive',
    artifact: 'NOTIFICATION_DELIVERY_BOUNDARY — pushChannel active port false',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — pushChannel: false in boundary flags',
    honestyRequirement: 'Boundary flags must remain false until W5-N04-b activates transport',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-boundary.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-channel-catalog-push',
    artifact: 'NOTIFICATION_CHANNEL_CATALOG — push reserved-inactive descriptor',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — push status reserved-inactive; only telegram active',
    honestyRequirement: 'Catalog reserved status must not imply push transport exists',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-ports-active-push-false',
    artifact: 'NOTIFICATION_PORTS_ACTIVE — pushChannel false',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — port active flag false for push channel',
    honestyRequirement: 'Port flags must remain false until W5-N04-b push adapters registered',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/ports/notification.port.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Commands / REST / catalog ──────────────────────────────────────────
  Object.freeze({
    artifactId: 'rest-notification-product-pc07',
    artifact: 'PC-07 REST — notification channel settings, routing, delivery history',
    kind: 'command' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — product adapter; does not deliver or connect Push transport',
    honestyRequirement: 'Product queries only; transport remains notification-delivery owner',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-product/notification-product.service.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'rest-pc07-channel-matrix',
    artifact: 'PC-07 Channel Matrix — Push reserved-inactive catalog truth',
    kind: 'state' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Binding — Push offered=No; disclosure only: Device, Browser; Send Test hidden; transport None',
    honestyRequirement: 'Matrix must not claim push transport offered before W5-N04-b',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/pc-07-channel-matrix.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Producing paths ──────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'produce-report-notification-consumer',
    artifact: 'ReportNotificationConsumerService — requestAndDeliver / deliverCompletedRun',
    kind: 'runtime' as const,
    owner: 'product-flow' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus:
      'Implemented — sync call into notification-delivery; push channel skipped when routed',
    honestyRequirement: 'Producer is not Live Trading; push send remains reserved-inactive',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/product-flow/report-notification-consumer.service.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'meta-channel-delivery-view-push-projection',
    artifact: 'ChannelDeliveryView — reservedChannels projection including push skip',
    kind: 'projection' as const,
    owner: 'product-flow' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — reservedChannels[] with skipReason for push when attempted',
    honestyRequirement: 'Projection reflects reserved-inactive truth; not push delivery proof',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/product-flow/channel-delivery.view.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Persistence candidates ───────────────────────────────────────────────
  Object.freeze({
    artifactId: 'persist-durable-notification-store',
    artifact: 'DurableNotificationStore — prefs + deliveries + queue (no push anchor today)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — analytical + queue snapshot; survives restart',
    honestyRequirement: 'Durable state ≠ production push delivery truth',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-push-notification-anchor',
    artifact: 'WorkspacePushNotificationAnchor — canonical Push delivery anchors (W5-N04-b)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — workspace_push_notification_anchors; anchor-recorded only; no Web Push/FCM I/O',
    honestyRequirement: 'Anchor persistence ≠ push delivery Complete; hydrate is W5-N04-c',
    futureW5N04Responsibility: 'W5-N04-c' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-push-notification-anchor.repository.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-vault-no-push-types',
    artifact: 'Vault ciphertext — no VAPID/FCM HoldableSecretType entries today',
    kind: 'persistence-candidate' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Exists vault substrate — Binance/Bybit/Okx/Telegram/Smtp/OpenRouter only; no Push types',
    honestyRequirement: 'Vault stores credentials; Push types added at W5-N04-b only',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Operator-visible ─────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ui-notification-channels-view-push',
    artifact: 'NotificationChannelsView — Push listed as reserved channel',
    kind: 'operator-visible' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Routed — Push stays reserved; Telegram active',
    honestyRequirement: 'UI must not claim Connected without push round-trip after W5-N04-b',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/web/src/notifications/NotificationChannelsView.tsx',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'ui-notification-channel-detail-push',
    artifact: 'NotificationChannelDetailView — reserved push detail (no registration form today)',
    kind: 'operator-visible' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Routed — Device/Browser fields not collected; reserved-inactive copy',
    honestyRequirement:
      'Detail view must not collect push credentials or device tokens until W5-N04-b',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/web/src/notifications/NotificationChannelDetailPage.tsx',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'ui-notifications-push-labels',
    artifact: 'notifications.ts — push channel label mapping',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — human label Push for reserved channel id',
    honestyRequirement: 'Label must not imply active transport',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/web/src/notifications/notifications.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Platform Readiness / foundation references ───────────────────────────
  Object.freeze({
    artifactId: 'dep-platform-readiness-notification-queue',
    artifact: 'Platform Readiness notificationQueue projection — aggregate continuity',
    kind: 'dependency' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'observed-by' as const,
    currentStatus: 'Implemented — W3-O02-d derived view on operational readiness',
    honestyRequirement: 'Queue continuity ≠ push transport Complete',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-w5-n01-telegram-foundation-reference',
    artifact: 'W5-N01 Telegram foundation — anchor/recovery/continuity pattern reference',
    kind: 'dependency' as const,
    owner: 'w5-n01-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — W5-N01 Closed; Push follows same owner patterns',
    honestyRequirement: 'Consume N01 patterns; do not redesign Telegram artifacts',
    futureW5N04Responsibility: 'w5-n01-reference' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n01-a-telegram-notification-inventory.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-w5-n02-email-foundation-reference',
    artifact: 'W5-N02 Email foundation — anchor/recovery/continuity pattern reference',
    kind: 'dependency' as const,
    owner: 'w5-n02-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — W5-N02 Closed; Push follows same owner patterns',
    honestyRequirement: 'Consume N02 patterns; do not redesign Email artifacts',
    futureW5N04Responsibility: 'w5-n02-reference' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n02-a-email-notification-inventory.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-w5-n03-webhook-foundation-reference',
    artifact: 'W5-N03 Slack/Discord/Teams foundation — anchor/recovery pattern reference',
    kind: 'dependency' as const,
    owner: 'w5-n03-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — W5-N03 Closed; Push follows same owner patterns',
    honestyRequirement: 'Consume N03 patterns; do not redesign webhook artifacts',
    futureW5N04Responsibility: 'w5-n03-reference' as const,
    evidencePath:
      'apps/api/src/platform-conformance/w5-n03-a-slack-discord-teams-notification-inventory.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authentication',
    artifact: 'Authentication — signed-in operator for connect/test/delivery surfaces',
    kind: 'dependency' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — fail closed when missing',
    honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-security-review.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authorization',
    artifact: 'Authorization — PermissionClass.Projection for notification surfaces',
    kind: 'dependency' as const,
    owner: 'authorization' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — connect/test requires permitted role',
    honestyRequirement: 'Unauthorized deny; no new IAM',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-security-review.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-vault-no-push-types',
    artifact: 'Vault VAPID/FCM credentials not in holdable catalog — transport blocker',
    kind: 'dependency' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus:
      'Active gap — no VAPID/FCM HoldableSecretType; no vault retrieve for push credentials',
    honestyRequirement:
      'W5-N04-b must add vault types and wire retrieve inside adapter boundary only',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-no-device-tokens',
    artifact: 'Device token registry absent — push delivery blocker',
    kind: 'dependency' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus:
      'Active gap — no workspace-scoped device token store; cannot target browser/device',
    honestyRequirement: 'Device registry is W5-N04-b; must not fake registered devices',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-exchange-adapter-untouched',
    artifact: 'Exchange Adapter / Wave 4 Exchange Connectivity — not consumed; unchanged',
    kind: 'dependency' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — Wave 5 must not modify exchange I/O',
    honestyRequirement: 'Push notifications ≠ exchange connectivity; adapter untouched',
    futureW5N04Responsibility: 'out-of-scope-exchange-adapter' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Missing / honesty blockers (catalogued honestly) ─────────────────────
  Object.freeze({
    artifactId: 'missing-production-push-transports',
    artifact: 'Production push transports — Web Push / FCM provider round-trip',
    kind: 'command' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — TD-050 deferred; push channel reserved-inactive; no Web Push/FCM I/O',
    honestyRequirement: 'Must not fake vendor round-trip; W5-N04-b implements real I/O',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-runtime-push-delivery',
    artifact: 'Runtime push delivery — HTTP to Web Push / FCM endpoints',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — notification-delivery module has no push adapter imports or provider I/O',
    honestyRequirement: 'Runtime delivery requires W5-N04-b adapter; no outbound HTTP today',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-push-restart-recovery',
    artifact: 'Push restart recovery — hydrate canonical anchors after restart',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no PushNotificationRestartRecoveryService; N01/N02/N03 recovery exists as reference',
    honestyRequirement: 'Recovery requires durable anchors first (W5-N04-b); hydrate is W5-N04-c',
    futureW5N04Responsibility: 'W5-N04-c' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-push-operational-continuity',
    artifact: 'Push operational continuity — Platform Readiness projection',
    kind: 'operational' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no push channel continuity projection; queue continuity exists only',
    honestyRequirement: 'Continuity slice follows durable transport implementation (W5-N04-d)',
    futureW5N04Responsibility: 'W5-N04-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-durable-push-anchors',
    artifact: 'Durable Push notification anchors — workspace-scoped persistence',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no prisma-push-notification-anchor.repository; N01/N02/N03 anchor repos exist',
    honestyRequirement: 'Anchor persistence is W5-N04-b; must not invent SoT in slice a',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-push-delivery-execution',
    artifact: 'Push delivery execution — queue retry / async outbound send',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — deliver() is sync terminal; queue persists work items without push retry execution',
    honestyRequirement: 'Delivery execution deferred; push transport retry is post W5-N04-b',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/README.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-push-connect-product',
    artifact: 'Push connect / test / disconnect product surface (PC-07 push channel)',
    kind: 'command' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no push-specific connect REST; reserved-inactive only',
    honestyRequirement: 'Connect product follows N01/N02/N03 patterns at W5-N04-b',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'gap-vault-push-types-absent',
    artifact: 'Parallel gap — Vault holdable catalog vs VAPID/FCM credentials required',
    kind: 'ephemeral-artifact' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Disconnected — Telegram/Smtp/OpenRouter types exist; VAPID/FCM Push types absent',
    honestyRequirement:
      'Must converge only under Notification Delivery adapter at W5-N04-b; no local secret store',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Operational / planning ───────────────────────────────────────────────
  Object.freeze({
    artifactId: 'op-w5-n04-planning-approved',
    artifact: 'W5-N04 Planning Package — APPROVED; slice a inventory only',
    kind: 'operational' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus:
      'Planning APPROVED — slice a inventory only; push implementation deferred to W5-N04-b',
    honestyRequirement: 'Planning Approval ≠ production push delivery Complete',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-approval.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'op-td050-reserved-channels-debt',
    artifact: 'TD-050 — Reserved notification channels (SMTP / Slack / Discord / Teams / Push)',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — push reserved-inactive until Wave 5 W5-N04-b',
    honestyRequirement: 'Debt label ≠ closed; must not claim push from inventory alone',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Honesty boundaries ───────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'honesty-real-delivery-not-live-trading',
    artifact: 'Real push delivery ≠ Live Trading; delivery ≠ order submission',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — frozen in W5-N04 scope',
    honestyRequirement: 'Push alerts outside process ≠ live capital trading enablement',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-push-delivery-only-not-control-plane',
    artifact: 'Push delivery-only — cannot start/stop/approve trades via push transport',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — no trading commands via Push transport',
    honestyRequirement: 'Notification channel only; control plane forbidden',
    futureW5N04Responsibility: 'out-of-scope-push-control-plane' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-reserved-inactive-not-production-push',
    artifact: 'ReservedInactiveChannelAdapter ≠ production Push delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — channel-reserved skip is not push send',
    honestyRequirement: 'deliver() skip must not imply notification reached browser/device',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-connected-requires-push-round-trip',
    artifact: 'Connected / Delivering labels require real push provider round-trip evidence',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — reserved-inactive violates today; W5-N04-b fixes',
    honestyRequirement: 'No fake Connected from reserved-inactive adapter alone',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-validation-plan.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w5-n04-not-wave5-complete',
    artifact: 'W5-N04 ≠ Wave 5 COMPLETE; N04 ≠ Notification Platform Complete',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — final Wave 5 transport package; wave Complete requires PO act',
    honestyRequirement: 'Push-only package; no wave-level Complete claims from slice a',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-overview.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-no-plaintext-secret-echo',
    artifact: 'No plaintext VAPID/FCM secret echo — vault retrieve adapter-side only',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — security review intent; fail closed on missing vault context',
    honestyRequirement: 'Push credentials never echoed in API responses or logs',
    futureW5N04Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-security-review.md',
    existsToday: true,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),

  // ── Explicit OUT ─────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'out-push-implementation-slice-a',
    artifact: 'Production push implementation in W5-N04-a',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Forbidden — inventory only; W5-N04-b implements push I/O',
    honestyRequirement: 'Slice a catalogues surfaces; does not implement transport I/O',
    futureW5N04Responsibility: 'out-of-scope-push-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-implementation-package.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-web-push-implementation-slice-a',
    artifact: 'Web Push implementation in W5-N04-a',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Forbidden — no browser push delivery in slice a',
    honestyRequirement: 'Web Push deferred to W5-N04-b',
    futureW5N04Responsibility: 'out-of-scope-browser-delivery-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-implementation-package.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-fcm-implementation-slice-a',
    artifact: 'FCM implementation in W5-N04-a',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Forbidden — no FCM delivery in slice a',
    honestyRequirement: 'FCM deferred to W5-N04-b',
    futureW5N04Responsibility: 'out-of-scope-fcm-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-implementation-package.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-device-token-persistence-slice-a',
    artifact: 'Device token registry persistence in W5-N04-a',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Forbidden — no device token store in slice a',
    honestyRequirement: 'Device registry deferred to W5-N04-b',
    futureW5N04Responsibility: 'out-of-scope-device-token-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-implementation-package.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n04-b-durable-anchors',
    artifact: 'W5-N04-b — Durable Push notification anchors + device token registry',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — named slice; not opened from slice a',
    honestyRequirement: 'Anchor persistence is post-inventory work',
    futureW5N04Responsibility: 'W5-N04-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n04-c-restart-recovery',
    artifact: 'W5-N04-c — Push notification restart recovery',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — restart hydrate post W5-N04-b',
    honestyRequirement: 'Recovery requires durable anchors first',
    futureW5N04Responsibility: 'W5-N04-c' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n04-d-operational-continuity',
    artifact: 'W5-N04-d — Push operational continuity foundation',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — transport continuity post push implementation',
    honestyRequirement: 'Continuity slice follows durable transport implementation',
    futureW5N04Responsibility: 'W5-N04-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n04-e-close-evidence',
    artifact: 'W5-N04-e — Security verification + package Close evidence',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — Close evidence assembly post implementation slices',
    honestyRequirement: 'Close requires FIV + PO act; not authorized from slice a',
    futureW5N04Responsibility: 'W5-N04-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading / live order submission (Wave 6)',
    kind: 'explicit-out' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Out of W5-N04 push notification scope',
    honestyRequirement: 'Push alerts ≠ live capital orders',
    futureW5N04Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-push-control-plane',
    artifact: 'Push as trading control plane — start/stop/approve via push transport',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — architecture invariant for all Wave 5',
    honestyRequirement: 'Delivery-only channel; no command bus via push',
    futureW5N04Responsibility: 'out-of-scope-push-control-plane' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-product-scope.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n01-reopen',
    artifact: 'Reopen W5-N01 Telegram Notification foundation',
    kind: 'explicit-out' as const,
    owner: 'w5-n01-reference' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — W5-N01 Closed; consume patterns only',
    honestyRequirement: 'Telegram artifacts remain frozen; Push extends adapters only',
    futureW5N04Responsibility: 'out-of-scope-w5-n01-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n02-reopen',
    artifact: 'Reopen W5-N02 Email Notification foundation',
    kind: 'explicit-out' as const,
    owner: 'w5-n02-reference' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — W5-N02 Closed; consume patterns only',
    honestyRequirement: 'Email artifacts remain frozen; Push extends adapters only',
    futureW5N04Responsibility: 'out-of-scope-w5-n02-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n03-reopen',
    artifact: 'Reopen W5-N03 Slack/Discord/Teams Notification foundation',
    kind: 'explicit-out' as const,
    owner: 'w5-n03-reference' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — W5-N03 Closed; consume patterns only',
    honestyRequirement: 'Webhook artifacts remain frozen; Push extends adapters only',
    futureW5N04Responsibility: 'out-of-scope-w5-n03-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n04-planning-summary.md',
    existsToday: false,
    authorizesPushRealDelivery: false,
    authorizesW5N04Complete: false,
  }),
]);

export const W5_N04_A_BINDING_FINDINGS = Object.freeze({
  pushRealDeliveryAuthorized: false,
  pushNotificationsFunctionAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  reservedInactivePushAdapterExists: true,
  vaultPushTypesAbsent: true,
  productionPushTransportsMissing: true,
  deviceTokenRegistryMissing: true,
  browserRegistrationMissing: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N04_A_EXPLICIT_OUT = Object.freeze([
  'push-implementation',
  'web-push-implementation',
  'fcm-implementation',
  'browser-delivery',
  'device-token-persistence',
  'outbound-production-notifications',
  'runtime-delivery-to-browser-device',
  'real-push-round-trip',
  'push-control-plane',
  'live-trading-enablement',
  'w5-n04-b',
  'w5-n04-c',
  'w5-n04-d',
  'w5-n04-e',
  'w5-n04-complete',
  'wave-5-complete',
  'w5-n01-reopen',
  'w5-n02-reopen',
  'w5-n03-reopen',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N04_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRoutingEngine: false,
  pushControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  w5N04CompleteClaimed: false,
  pushRealDeliveryClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  customerVisibleFeature: false,
  w5N01Reopened: false,
  w5N02Reopened: false,
  w5N03Reopened: false,
} as const);

export const W5_N04_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible production Push notification functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'ReservedInactiveChannelAdapter — push channel reserved-inactive (TD-050 deferred)',
    'NotificationDeliveryService deliver() / sendTestNotification() sync pipeline (push skip path)',
    'PC-06 resolve-delivery-routing — type/channel routing + quiet hours',
    'PC-07 notification-product — channel settings, routing views, delivery history',
    'NOTIFICATION_CHANNEL_CATALOG — push reserved-inactive descriptor',
    'NOTIFICATION_DELIVERY_BOUNDARY — pushChannel active=false',
    'User notification preferences — routing inputs including push channel enablement',
    'DurableNotificationStore — W3-O01 history + W3-O02 queue snapshot',
    'DeliveryResult + ChannelDeliveryAttempt metadata — honest skip/deliver records',
    'PC-07 Channel Matrix — Push disclosure-only; not offered',
    'Platform Readiness notificationQueue continuity projection (derived)',
    'ReportNotificationConsumer — product-flow producer into delivery',
    'W5-N01 Telegram foundation — anchor/recovery pattern reference',
    'W5-N02 Email foundation — anchor/recovery pattern reference',
    'W5-N03 Slack/Discord/Teams foundation — anchor/recovery pattern reference',
    'Exchange Adapter / Wave 4 — reference only; untouched by Wave 5',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N04-b — Production push connect / test / disconnect via vault-backed adapters + device token registry',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Web Push / FCM provider round-trip (TD-050)',
    'Durable push notification anchors (W5-N04-b)',
    'Workspace-scoped device token registry (W5-N04-b)',
    'Browser registration / PushManager subscription capture',
    'Vault VAPID/FCM secret types and retrieve in delivery path',
    'Push connect / test product surface',
    'Honest Connected / Delivering labels from push round-trip',
    'W5-N04 Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'W5-N04-c — Push notification restart recovery',
    'W5-N04-d — Push operational continuity foundation',
    'W5-N04-e — Security verification + package Close evidence',
    'Wave 6 — Live Trading (LT-02)',
  ] as const),
} as const);

export const W5_N04_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze(['Push Notification Inventory Foundation'] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N04-b — Durable Push notification foundation + device token registry',
    'W5-N04-c — Push notification restart recovery',
    'W5-N04-d — Push operational continuity foundation',
    'W5-N04-e — Security verification + package Close evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N04AArtifactKind): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsPushNotificationSurvive(): readonly W5N04AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N04_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsPushNotificationEphemeral(): readonly W5N04AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N04_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N04ACapabilityCategory,
): readonly W5N04AInventoryRow[] {
  return W5_N04_A_PUSH_NOTIFICATION_INVENTORY.filter((row) => row.capabilityCategory === category);
}
