/**
 * w5-n20-a — Notification Retry Policy Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not Notification Retry Policy implementation. Not production transport I/O.
 * Not retry policy evaluation runtime / backoff / scheduler runtime / retry execution / Policy Engine / Retry Platform / Workflow Engine / Event Bus.
 * Not W5-N20 COMPLETE. Not Notification Platform Complete. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - FOUNDATION: retry policy foundation layer artifact on notification-delivery owner (planned or reference).
 * - DURABLE: artifact persists across API restart today on existing owner.
 * - RECOVERABLE: artifact has defined restart recovery on existing owner or consumed foundation.
 * - EPHEMERAL: transient, missing retry policy layer, UI-only, process-local, or absent.
 * - OUT OF SCOPE: explicit deferral — must not authorize retry policy functional.
 *
 * W5-N01…N19 per-channel and platform foundations consumed as reference patterns only — not reopened.
 */

export const W5_N20_A_SLICE_ID = 'W5-N20-a' as const;

export const W5_N20_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n02-reference',
  'w5-n03-reference',
  'w5-n04-reference',
  'w5-n05-reference',
  'w5-n06-reference',
  'w5-n07-reference',
  'w5-n08-reference',
  'w5-n09-reference',
  'w5-n10-reference',
  'w5-n11-reference',
  'w5-n12-reference',
  'w5-n13-reference',
  'w5-n14-reference',
  'w5-n15-reference',
  'w5-n16-reference',
  'w5-n17-reference',
  'w5-n18-reference',
  'w5-n19-reference',
  'ai-gateway-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N20AOwner = (typeof W5_N20_A_ALLOWED_OWNERS)[number];

/** Existing notification / platform retry policy substrate owners — no new owner. */
export const W5_N20_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'platform-readiness',
] as const);

export const W5_N20_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N20AArtifactKind = (typeof W5_N20_A_ARTIFACT_KINDS)[number];

export const W5_N20_A_REQUIRED_ARTIFACT_KINDS = W5_N20_A_ARTIFACT_KINDS;

export const W5_N20_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N20ACapabilityCategory = (typeof W5_N20_A_CAPABILITY_CATEGORIES)[number];

export const W5_N20_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N20ADurabilityClass = (typeof W5_N20_A_DURABILITY_CLASSES)[number];

export const W5_N20_A_RETRY_POLICY_CLASSIFICATIONS = Object.freeze([
  'FOUNDATION',
  'DURABLE',
  'RECOVERABLE',
  'EPHEMERAL',
  'OUT OF SCOPE',
] as const);

export type W5N20ARetryPolicyClassification =
  (typeof W5_N20_A_RETRY_POLICY_CLASSIFICATIONS)[number];

export const W5_N20_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N20ADependencyDirection = (typeof W5_N20_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N20_A_PERSISTENCE_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n18-reference',
  'w5-n19-reference',
  'w5-n20-b',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N20APersistenceResponsibility =
  (typeof W5_N20_A_PERSISTENCE_RESPONSIBILITIES)[number];

export const W5_N20_A_RECOVERY_RESPONSIBILITIES = Object.freeze([
  'notification-delivery',
  'w5-n18-reference',
  'w5-n19-reference',
  'w5-n20-c',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N20ARecoveryResponsibility = (typeof W5_N20_A_RECOVERY_RESPONSIBILITIES)[number];

export const W5_N20_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES = Object.freeze([
  'platform-readiness',
  'w5-n18-reference',
  'w5-n19-reference',
  'w5-n20-d',
  'none-missing',
  'consumed-not-owned',
  'not-applicable',
] as const);

export type W5N20AOperationalContinuityResponsibility =
  (typeof W5_N20_A_OPERATIONAL_CONTINUITY_RESPONSIBILITIES)[number];

export const W5_N20_A_HONEST_PRODUCT_STATES = Object.freeze([
  'not-implemented',
  'infrastructure-only',
  'implemented-today',
  'reserved-inactive',
  'planned',
  'deferred',
  'binding-honesty',
  'explicit-out',
  'not-applicable',
] as const);

export type W5N20AHonestProductState = (typeof W5_N20_A_HONEST_PRODUCT_STATES)[number];

export const W5_N20_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N20-b',
  'W5-N20-c',
  'W5-N20-d',
  'W5-N20-e',
  'honesty-baseline',
  'out-of-scope-live-trading',
  'out-of-scope-platform-retry-policy-slice-a',
  'out-of-scope-production-transport-i/o',
  'out-of-scope-exchange-adapter',
  'out-of-scope-w5-n20-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-notification-platform-complete',
  'out-of-scope-w5-n18-reopen',
  'out-of-scope-w5-n19-reopen',
  'out-of-scope-ai-gateway',
  'out-of-scope-policy-engine',
  'out-of-scope-retry-platform',
  'out-of-scope-retry-orchestration',
  'out-of-scope-retry-execution-runtime',
  'out-of-scope-retry-scheduler-runtime',
  'out-of-scope-policy-evaluation-runtime',
  'out-of-scope-backoff-calculation',
  'w5-n18-reference',
  'w5-n19-reference',
] as const);

export type W5N20AFutureResponsibility = (typeof W5_N20_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N20AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N20AArtifactKind;
  owner: W5N20AOwner;
  durabilityClass: W5N20ADurabilityClass;
  capabilityCategory: W5N20ACapabilityCategory;
  dependencyDirection?: W5N20ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N20Responsibility: W5N20AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesRetryPolicyFunctional: boolean;
  authorizesW5N20Complete: boolean;
  persistenceResponsibility: W5N20APersistenceResponsibility;
  recoveryResponsibility: W5N20ARecoveryResponsibility;
  operationalContinuityResponsibility: W5N20AOperationalContinuityResponsibility;
  honestProductState: W5N20AHonestProductState;
  retryPolicyClassification: W5N20ARetryPolicyClassification;
  operationalVisibility: string;
  customerVisibility: string;
}>;

export const W5_N20_A_RETRY_POLICY_INVENTORY: readonly W5N20AInventoryRow[] = Object.freeze([
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-platform-retry-policy-layer' as const,
    artifact: 'Cross-channel Notification Retry Policy — notification-delivery owner' as const,
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — durable retry policy description anchors on notification-delivery; unified policy evaluation runtime still absent' as const,
    honestyRequirement:
      'Retry policy extends notification-delivery only; no Policy Engine, Retry Platform, Workflow Engine, or Event Bus' as const,
    futureW5N20Responsibility: 'W5-N20-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-policy-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-notification-delivery-domain' as const,
    artifact:
      'Notification Delivery bounded context — sole owner for retry policy foundation artifacts' as const,
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — notification-delivery owns channels, foundations, retry execution, scheduling, and policy substrate path' as const,
    honestyRequirement:
      'Retry policy remains a capability of notification-delivery; no new bounded context' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/notification-delivery.module.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-pc06-routing-delivery' as const,
    artifact: 'PC-06 resolve-delivery-routing — routing SoT consumed unchanged' as const,
    kind: 'ownership' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — PC-06 routing SoT; retry policy consumes routing, does not own it' as const,
    honestyRequirement: 'No duplicate routing engine; PC-06 unchanged' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/notification-delivery.service.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-w5-n18-retry-execution-consume' as const,
    artifact: 'W5-N18 CLOSED retry execution foundation — consumed not redesigned' as const,
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N18 CLOSED — retry execution inventory/persistence/recovery/continuity; policy builds on top' as const,
    honestyRequirement: 'Retry execution ≠ retry policy; N18 not reopened' as const,
    futureW5N20Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-w5-n19-retry-scheduling-consume' as const,
    artifact: 'W5-N19 CLOSED retry scheduling foundation — consumed not redesigned' as const,
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'W5-N19 CLOSED — retry scheduling inventory/persistence/recovery/continuity; policy builds on top' as const,
    honestyRequirement: 'Retry scheduling ≠ retry policy; N19 not reopened' as const,
    futureW5N20Responsibility: 'w5-n19-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-scheduling-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n19-reference' as const,
    recoveryResponsibility: 'w5-n19-reference' as const,
    operationalContinuityResponsibility: 'w5-n19-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-secret-vault-consume' as const,
    artifact: 'Secret Vault — credential owner consumed only' as const,
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — Vault owns credentials; retry policy does not store secrets' as const,
    honestyRequirement: 'No local secret store; no plaintext echo' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-security-review.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-connection-management-consume' as const,
    artifact: 'Connection Management facade — consumed not redesigned' as const,
    kind: 'ownership' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — operator connect surfaces consumed; ownership unchanged' as const,
    honestyRequirement: 'Connection Management not redesigned' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-workspace-isolation-notifications' as const,
    artifact: 'Workspace Isolation — retry policy state workspace-scoped' as const,
    kind: 'ownership' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — Isolation boundary unchanged; fail closed on missing workspace' as const,
    honestyRequirement: 'No cross-workspace retry policy state' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-security-review.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-notification-durable-queue' as const,
    artifact: 'W3-O02 durable notification queue — substrate consumed' as const,
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Exists — durable queue on notification-delivery; policy may consume after N20-b+' as const,
    honestyRequirement: 'Queue substrate owner unchanged; not policy evaluation runtime' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'own-honest-product-boundaries' as const,
    artifact: 'Honest Product boundaries for Retry Policy Foundation' as const,
    kind: 'ownership' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus:
      'Documented — Retry Policy ≠ evaluation runtime / backoff / scheduler / execution / delivery guarantee' as const,
    honestyRequirement: 'Binding Honest Product rules frozen at planning and inventory' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'documentation-only' as const,
    customerVisibility: 'not customer-visible — documentation honesty' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-anchor' as const,
    artifact:
      'W5-N18 retry execution anchors — workspace_notification_platform_retry_execution_anchors' as const,
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-execution-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-restart-recovery' as const,
    artifact: 'W5-N18 retry execution restart recovery service' as const,
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-restart-recovery.service.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n18-retry-execution-continuity' as const,
    artifact: 'W5-N18 retry execution operational continuity projection' as const,
    kind: 'dependency' as const,
    owner: 'w5-n18-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n18-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-execution-operational-continuity.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n18-reference' as const,
    recoveryResponsibility: 'w5-n18-reference' as const,
    operationalContinuityResponsibility: 'w5-n18-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n19-retry-scheduling-anchor' as const,
    artifact:
      'W5-N19 retry scheduling anchors — workspace_notification_platform_retry_scheduling_anchors' as const,
    kind: 'dependency' as const,
    owner: 'w5-n19-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n19-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-scheduling-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n19-reference' as const,
    recoveryResponsibility: 'w5-n19-reference' as const,
    operationalContinuityResponsibility: 'w5-n19-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n19-retry-scheduling-restart-recovery' as const,
    artifact: 'W5-N19 retry scheduling restart recovery service' as const,
    kind: 'dependency' as const,
    owner: 'w5-n19-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n19-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-scheduling-restart-recovery.service.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n19-reference' as const,
    recoveryResponsibility: 'w5-n19-reference' as const,
    operationalContinuityResponsibility: 'w5-n19-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'consume-w5-n19-retry-scheduling-continuity' as const,
    artifact: 'W5-N19 retry scheduling operational continuity projection' as const,
    kind: 'dependency' as const,
    owner: 'w5-n19-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'CLOSED foundation consumed — ownership retained on existing owner' as const,
    honestyRequirement:
      'Consumed not redesigned; does not authorize retry policy functional' as const,
    futureW5N20Responsibility: 'w5-n19-reference' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-scheduling-operational-continuity.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'w5-n19-reference' as const,
    recoveryResponsibility: 'w5-n19-reference' as const,
    operationalContinuityResponsibility: 'w5-n19-reference' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'channel-w5-n01-telegram-anchor' as const,
    artifact: 'W5-N01 Telegram notification anchors — reference' as const,
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'CLOSED per-channel foundation — reference only; transport I/O deferred' as const,
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry policy inventory' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-telegram-notification-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'channel-w5-n02-email-anchor' as const,
    artifact: 'W5-N02 Email notification anchors — reference' as const,
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'CLOSED per-channel foundation — reference only; transport I/O deferred' as const,
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry policy inventory' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-email-notification-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'channel-w5-n03-webhook-anchor' as const,
    artifact: 'W5-N03 Slack/Discord/Teams anchors — reference' as const,
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'CLOSED per-channel foundation — reference only; transport I/O deferred' as const,
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry policy inventory' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-channel.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'channel-w5-n04-push-anchor' as const,
    artifact: 'W5-N04 Push notification anchors — reference' as const,
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'CLOSED per-channel foundation — reference only; transport I/O deferred' as const,
    honestyRequirement:
      'Per-channel Connected/Delivering requires real transport — not from retry policy inventory' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-channel.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'missing-unified-platform-retry-policy-view' as const,
    artifact: 'Unified cross-channel retry policy view — Platform Readiness projection' as const,
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Implemented — PlatformOperationalProjection exposes notificationPlatformRetryPolicy continuity view' as const,
    honestyRequirement:
      'Platform Readiness projection only; not unified functional retry policy layer' as const,
    futureW5N20Responsibility: 'W5-N20-e' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n20-d' as const,
    honestProductState: 'not-implemented' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection' as const,
    customerVisibility: 'operator — Retry Policy readiness via Platform Readiness' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'missing-retry-policy-persistence' as const,
    artifact: 'Missing durable retry policy description anchors' as const,
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved by W5-N20-b — see persist-notification-platform-retry-policy-anchor; gap row retained for inventory honesty' as const,
    honestyRequirement: 'Does not authorize retry policy functional from slice a' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-policy-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — gap resolved by W5-N20-b' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'missing-retry-policy-recovery' as const,
    artifact: 'Missing restart-safe retry policy recovery' as const,
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Resolved by W5-N20-c — integrity-gated hydrate of retry policy anchors; gap row retained for inventory honesty' as const,
    honestyRequirement: 'Does not authorize retry policy functional from slice a' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-policy-restart-recovery.service.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — gap resolved by W5-N20-c' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'missing-retry-policy-operational-continuity' as const,
    artifact:
      'Retry policy operational continuity — buildNotificationPlatformRetryPolicyView' as const,
    kind: 'ephemeral-artifact' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — buildNotificationPlatformRetryPolicyView derives readiness from W5-N20-c recovery record' as const,
    honestyRequirement: 'Retry policy continuity follows restart recovery (W5-N20-c/d)' as const,
    futureW5N20Responsibility: 'W5-N20-e' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/notification-platform-retry-policy-operational-continuity.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection' as const,
    customerVisibility: 'operator — Retry Policy readiness via Platform Readiness' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'missing-retry-policy-ui' as const,
    artifact: 'Missing operator retry policy UI' as const,
    kind: 'ephemeral-artifact' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Not implemented — inventory only; deferred to later W5-N20 slices' as const,
    honestyRequirement: 'Does not authorize retry policy functional from slice a' as const,
    futureW5N20Responsibility: 'W5-N20-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-implementation-package.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'not-implemented' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — not implemented' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'persist-notification-platform-retry-policy-anchor' as const,
    artifact:
      'WorkspaceNotificationPlatformRetryPolicyAnchor — canonical retry policy anchors (W5-N20-b)' as const,
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — workspace_notification_platform_retry_policy_anchors; anchor-recorded only; restart recovery via W5-N20-c; no policy evaluation runtime' as const,
    honestyRequirement: 'Does not authorize retry policy functional from slice a' as const,
    futureW5N20Responsibility: 'W5-N20-d' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/persistence/prisma-notification-platform-retry-policy-anchor.repository.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'notification-delivery' as const,
    recoveryResponsibility: 'notification-delivery' as const,
    operationalContinuityResponsibility: 'none-missing' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'DURABLE' as const,
    operationalVisibility: 'internal-only — durable anchor persistence' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'projection-platform-readiness-retry-policy-missing' as const,
    artifact: 'Platform Readiness notificationPlatformRetryPolicy — projected (W5-N20-d)' as const,
    kind: 'projection' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — notificationPlatformRetryPolicy on PlatformOperationalProjection' as const,
    honestyRequirement: 'Do not fabricate Platform Ready for retry policy from inventory' as const,
    futureW5N20Responsibility: 'W5-N20-e' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'operator — Platform Readiness projection' as const,
    customerVisibility: 'operator — Retry Policy readiness via Platform Readiness' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'runtime-pc06-resolve-delivery-routing' as const,
    artifact:
      'PC-06 resolve-delivery-routing runtime — consumed for retry policy planning context' as const,
    kind: 'runtime' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Exists — routing runtime; not retry policy evaluation runtime' as const,
    honestyRequirement: 'Routing ≠ retry policy; no duplicate routing' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/notification-delivery.service.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'consumed-not-owned' as const,
    recoveryResponsibility: 'consumed-not-owned' as const,
    operationalContinuityResponsibility: 'platform-readiness' as const,
    honestProductState: 'infrastructure-only' as const,
    retryPolicyClassification: 'RECOVERABLE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — infrastructure only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'command-retry-policy-inventory-freeze' as const,
    artifact: 'W5-N20-a inventory freeze command surface — documentation/conformance only' as const,
    kind: 'command' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — machine inventory and conformance registry for slice a' as const,
    honestyRequirement: 'Inventory command does not evaluate policies or execute retries' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n20-a-retry-policy-inventory.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-conformance' as const,
    customerVisibility: 'not customer-visible — inventory only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'operational-retry-policy-inventory-diagnostics' as const,
    artifact: 'Retry policy inventory conformance diagnostics' as const,
    kind: 'operational' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — buildRetryPolicyDiagnostics for slice a' as const,
    honestyRequirement: 'Diagnostics prove inventory completeness only — not retry policy' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n20-a-retry-policy.ts' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'implemented-today' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — conformance only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'operator-visible-retry-policy-none' as const,
    artifact: 'Operator-visible retry policy surfaces — none in slice a' as const,
    kind: 'operator-visible' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'None — customer-visible functionality is none for W5-N20-a' as const,
    honestyRequirement: 'No operator UI claims retry policy from inventory' as const,
    futureW5N20Responsibility: 'W5-N20-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/notification-retry-policy-overview.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'none-missing' as const,
    recoveryResponsibility: 'none-missing' as const,
    operationalContinuityResponsibility: 'w5-n20-d' as const,
    honestProductState: 'not-implemented' as const,
    retryPolicyClassification: 'EPHEMERAL' as const,
    operationalVisibility: 'none' as const,
    customerVisibility: 'none — inventory foundation only' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-evaluation-runtime' as const,
    artifact: 'Retry Policy ≠ retry policy evaluation runtime' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement:
      'Retry Policy ≠ retry policy evaluation runtime — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-backoff' as const,
    artifact: 'Retry Policy ≠ backoff calculation' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ backoff calculation — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-scheduler-runtime' as const,
    artifact: 'Retry Policy ≠ retry scheduler runtime' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ retry scheduler runtime — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-execution-runtime' as const,
    artifact: 'Retry Policy ≠ retry execution runtime' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ retry execution runtime — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-successful-delivery' as const,
    artifact: 'Retry Policy ≠ successful delivery' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ successful delivery — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-provider-acceptance' as const,
    artifact: 'Retry Policy ≠ provider acceptance' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ provider acceptance — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-recipient-receipt' as const,
    artifact: 'Retry Policy ≠ recipient receipt' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ recipient receipt — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-exactly-once' as const,
    artifact: 'Retry Policy ≠ exactly-once delivery' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ exactly-once delivery — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-delivery-guarantee' as const,
    artifact: 'Retry Policy ≠ delivery guarantee' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ delivery guarantee — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-policy-not-live-trading' as const,
    artifact: 'Retry Policy ≠ Live Trading' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'Retry Policy ≠ Live Trading — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-scheduling-not-retry-policy' as const,
    artifact: 'W5-N19 retry scheduling ≠ retry policy' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'W5-N19 retry scheduling ≠ retry policy — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-retry-execution-not-retry-policy' as const,
    artifact: 'W5-N18 retry execution ≠ retry policy' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'W5-N18 retry execution ≠ retry policy — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-no-policy-engine' as const,
    artifact: 'No Policy Engine product' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement: 'No Policy Engine product — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-platform-ready-requires-retry-policy-evidence' as const,
    artifact: 'Platform Ready for retry policy requires foundation evidence' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement:
      'Platform Ready for retry policy requires foundation evidence — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'honesty-notifications-not-control-plane' as const,
    artifact: 'Notifications are delivery-only — never a control plane' as const,
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Binding honesty rule frozen in planning and inventory' as const,
    honestyRequirement:
      'Notifications are delivery-only — never a control plane — binding for W5-N20' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'binding-honesty' as const,
    retryPolicyClassification: 'FOUNDATION' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — honesty documentation' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-retry-policy-implementation-slice-a' as const,
    artifact: 'Retry policy implementation — out of slice a' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Retry policy implementation — out of slice a' as const,
    futureW5N20Responsibility: 'out-of-scope-platform-retry-policy-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n20-b-durable-persistence' as const,
    artifact: 'W5-N20-b durable policy persistence — completed as foundation slice' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus:
      'W5-N20-b durable persistence implemented — still OUT of slice-a authorization; does not authorize policy evaluation runtime' as const,
    honestyRequirement:
      'W5-N20-b durable policy persistence — not retry policy evaluation runtime' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-b-implementation-report.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n20-c-restart-safe-recovery' as const,
    artifact: 'W5-N20-c restart-safe recovery — completed as foundation slice' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus:
      'W5-N20-c restart recovery implemented — still OUT of slice-a authorization surface; does not authorize policy evaluation runtime' as const,
    honestyRequirement:
      'W5-N20-c restart-safe recovery — not retry policy evaluation runtime' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-c-implementation-report.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n20-d-operational-continuity' as const,
    artifact: 'W5-N20-d operational continuity — completed as foundation slice' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus:
      'W5-N20-d operational continuity implemented — still OUT of slice-a authorization surface; does not authorize policy evaluation runtime' as const,
    honestyRequirement:
      'W5-N20-d operational continuity — not retry policy evaluation runtime' as const,
    futureW5N20Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-d-implementation-report.md' as const,
    existsToday: true as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n20-e-close-evidence' as const,
    artifact: 'W5-N20-e Close Evidence — not in slice a' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a; deferred to W5-N20-e' as const,
    honestyRequirement: 'W5-N20-e Close Evidence — not in slice a' as const,
    futureW5N20Responsibility: 'W5-N20-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-policy-evaluation-runtime' as const,
    artifact: 'Policy evaluation runtime — out of W5-N20 foundation' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Policy evaluation runtime — out of W5-N20 foundation' as const,
    futureW5N20Responsibility: 'out-of-scope-policy-evaluation-runtime' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-backoff-calculation' as const,
    artifact: 'Backoff calculation — out' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Backoff calculation — out' as const,
    futureW5N20Responsibility: 'out-of-scope-backoff-calculation' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-retry-scheduler-runtime' as const,
    artifact: 'Retry scheduler runtime — out of W5-N20 foundation' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Retry scheduler runtime — out of W5-N20 foundation' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-scheduler-runtime' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-retry-execution-runtime' as const,
    artifact: 'Retry execution runtime — out of W5-N20 foundation' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Retry execution runtime — out of W5-N20 foundation' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-execution-runtime' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-transport-execution' as const,
    artifact: 'Transport execution — out of W5-N20 foundation' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Transport execution — out of W5-N20 foundation' as const,
    futureW5N20Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-policy-engine' as const,
    artifact: 'Policy Engine — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Policy Engine — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-policy-engine' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-retry-platform' as const,
    artifact: 'Retry Platform — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Retry Platform — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-platform' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-workflow-engine' as const,
    artifact: 'Workflow Engine — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Workflow Engine — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-event-bus-product' as const,
    artifact: 'Event Bus product — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Event Bus product — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-orchestration-platform' as const,
    artifact: 'Orchestration platform — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Orchestration platform — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-retry-orchestration' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-notification-platform-complete' as const,
    artifact: 'Notification Platform Complete — not claimed' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Notification Platform Complete — not claimed' as const,
    futureW5N20Responsibility: 'out-of-scope-notification-platform-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-live-notifications' as const,
    artifact: 'Live Notifications — not claimed' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Live Notifications — not claimed' as const,
    futureW5N20Responsibility: 'out-of-scope-production-transport-i/o' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-production-ready' as const,
    artifact: 'Production Ready — not claimed' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Production Ready — not claimed' as const,
    futureW5N20Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-wave-5-complete' as const,
    artifact: 'Wave 5 COMPLETE — not claimed' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Wave 5 COMPLETE — not claimed' as const,
    futureW5N20Responsibility: 'out-of-scope-wave-5-complete' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-live-trading-wave6' as const,
    artifact: 'Live Trading Wave 6 — out of scope' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'Live Trading Wave 6 — out of scope' as const,
    futureW5N20Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n18-reopen' as const,
    artifact: 'W5-N18 reopen — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'W5-N18 reopen — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-w5-n18-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
  Object.freeze({
    authorizesRetryPolicyFunctional: false as const,
    authorizesW5N20Complete: false as const,
    artifactId: 'out-w5-n19-reopen' as const,
    artifact: 'W5-N19 reopen — forbidden' as const,
    kind: 'explicit-out' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Explicit OUT — must not authorize from W5-N20-a' as const,
    honestyRequirement: 'W5-N19 reopen — forbidden' as const,
    futureW5N20Responsibility: 'out-of-scope-w5-n19-reopen' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n20-product-scope.md' as const,
    existsToday: false as const,
    persistenceResponsibility: 'not-applicable' as const,
    recoveryResponsibility: 'not-applicable' as const,
    operationalContinuityResponsibility: 'not-applicable' as const,
    honestProductState: 'explicit-out' as const,
    retryPolicyClassification: 'OUT OF SCOPE' as const,
    operationalVisibility: 'internal-only' as const,
    customerVisibility: 'not customer-visible — explicit out' as const,
  }),
]);

export const W5_N20_A_BINDING_FINDINGS = Object.freeze({
  retryPolicyFunctionalAuthorized: false,
  retryPolicyFunctionsAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  w5N18RetryExecutionExists: true,
  w5N19RetrySchedulingExists: true,
  unifiedPlatformRetryPolicyLayerMissing: true,
  retryPolicyPersistenceMissing: false,
  retryPolicyRecoveryMissing: false,
  retryPolicyOperationalContinuityMissing: false,
  productionTransportsDeferred: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N20_A_EXPLICIT_OUT = Object.freeze([
  'retry-policy-implementation',
  'policy-evaluation-runtime',
  'backoff-calculation',
  'retry-scheduler-runtime',
  'retry-execution-runtime',
  'production-transport-i/o',
  'notification-platform-complete',
  'live-trading-enablement',
  'live-notifications',
  'production-ready',
  'w5-n20-b',
  'w5-n20-c',
  'w5-n20-d',
  'w5-n20-e',
  'w5-n20-complete',
  'wave-5-complete',
  'policy-engine',
  'retry-platform',
  'workflow-engine',
  'event-bus-product',
  'orchestration-platform',
  'w5-n18-reopen',
  'w5-n19-reopen',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N20_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicatePolicySubsystem: false,
  duplicateRoutingEngine: false,
  policyEngineIntroduced: false,
  retryPlatformIntroduced: false,
  workflowEngineIntroduced: false,
  eventBusProductIntroduced: false,
  orchestrationPlatformIntroduced: false,
  notificationControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  inventoryOnly: true,
  w5N20CompleteClaimed: false,
  retryPolicyFunctionalClaimed: false,
  notificationPlatformCompleteClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  liveNotificationsClaimed: false,
  productionReadyClaimed: false,
  customerVisibleFeature: false,
  w5N18Reopened: false,
  w5N19Reopened: false,
} as const);

export const W5_N20_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible Notification Retry Policy functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'Per-channel N01…N04 notification anchors on notification-delivery owner',
    'W5-N05…N17 platform foundations on notification-delivery owner (consumed)',
    'W5-N18 retry execution inventory, durable anchors, recovery, and continuity (consumed)',
    'W5-N19 retry scheduling inventory, durable anchors, recovery, and continuity (consumed)',
    'W5-N20-b durable retry policy description anchors on notification-delivery',
    'W5-N20-c restart-safe hydrate of retry policy anchors on notification-delivery',
    'W5-N20-d operational continuity on Platform Readiness (notificationPlatformRetryPolicy)',
    'PC-06 resolve-delivery-routing — routing SoT consumed unchanged',
    'PC-07 notification-product — per-channel settings and history',
    'Notification Durable Queue — W3-O02 on notification-delivery owner (consumed)',
    'W5-N01…N19 machine inventories — foundation reference patterns',
    'Exchange Adapter / Wave 4 — reference only; untouched',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N20-e — Package Validation, Operational Verification & Close Evidence',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Unified cross-channel platform retry policy layer',
    'Operator retry policy UI',
    'Retry policy evaluation runtime',
    'Backoff calculation',
    'Retry scheduler runtime',
    'Retry execution runtime',
    'Transport execution / provider runtimes',
    'Production transport I/O (TD-049 / TD-050)',
    'Notification Platform Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'Wave 6 — Live Trading (LT-02)',
    'Wave 7 — Anthropic / AI Gateway (out of W5-N20 scope)',
  ] as const),
} as const);

export const W5_N20_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze([
    'Retry Policy inventory baseline established',
    'Durable Retry Policy persistence foundation',
    'Retry Policy restart recovery foundation',
    'Retry Policy operational continuity foundation',
  ] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N20-e — Package Validation, Operational Verification & Close Evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N20AArtifactKind): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsNotificationRetryPolicySurvive(): readonly W5N20AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N20_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsNotificationRetryPolicyEphemeral(): readonly W5N20AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N20_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N20ACapabilityCategory,
): readonly W5N20AInventoryRow[] {
  return W5_N20_A_RETRY_POLICY_INVENTORY.filter((row) => row.capabilityCategory === category);
}
