/**
 * W5-N02-a — Email Notification Inventory & Honest Product Baseline.
 *
 * Discovery and classification only.
 * Not SMTP implementation. Not outbound production notifications.
 * Not runtime delivery to customer SMTP servers. Not W5-N02 COMPLETE. Not Wave 5 CLOSED.
 *
 * Classification (binding for this slice):
 * - SURVIVE: artifact persists across API restart today or is the durable
 *   substrate on existing Notification Delivery / Vault / Connection / Queue owners.
 * - EPHEMERAL: artifact is transient, stub, reserved-inactive transport, UI-only,
 *   process-local, or missing — must not be treated as production Email truth.
 *
 * Auth host mail (S01-e) is SEPARATE from Notification Email — documented throughout.
 * W5-N01 Telegram foundation consumed as reference pattern only.
 */

export const W5_N02_A_SLICE_ID = 'W5-N02-a' as const;

export const W5_N02_A_ALLOWED_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
  'authentication',
  'authorization',
  'workspace-isolation',
  'security-platform',
  'security-audit',
  'product-flow',
  'command-center',
  'platform-readiness',
  'exchange-adapter',
  'event-processing',
  'release-governance',
  'wave-5-documentation',
  'w5-n01-reference',
  'w5-n03-deferred',
  'w5-n04-deferred',
  'live-trading-deferred',
  'strategy-trading-pipeline',
] as const);

export type W5N02AOwner = (typeof W5_N02_A_ALLOWED_OWNERS)[number];

/** Existing notification / Email substrate owners — no new owner. */
export const W5_N02_A_SUBSTRATE_OWNERS = Object.freeze([
  'notification-delivery',
  'notification-product',
  'connection-management',
  'secret-vault',
] as const);

export const W5_N02_A_ARTIFACT_KINDS = Object.freeze([
  'command',
  'state',
  'projection',
  'runtime',
  'operational',
  'operator-visible',
  'persistence-candidate',
  'ephemeral-artifact',
  'dependency',
  'ownership',
  'honesty-boundary',
  'explicit-out',
] as const);

export type W5N02AArtifactKind = (typeof W5_N02_A_ARTIFACT_KINDS)[number];

export const W5_N02_A_REQUIRED_ARTIFACT_KINDS = W5_N02_A_ARTIFACT_KINDS;

export const W5_N02_A_CAPABILITY_CATEGORIES = Object.freeze([
  'implemented-today',
  'infrastructure-only',
  'planned',
  'not-implemented',
  'future-roadmap',
] as const);

export type W5N02ACapabilityCategory = (typeof W5_N02_A_CAPABILITY_CATEGORIES)[number];

export const W5_N02_A_DURABILITY_CLASSES = Object.freeze(['SURVIVE', 'EPHEMERAL'] as const);

export type W5N02ADurabilityClass = (typeof W5_N02_A_DURABILITY_CLASSES)[number];

export const W5_N02_A_DEPENDENCY_DIRECTIONS = Object.freeze([
  'consumes',
  'produces',
  'depends-on',
  'observed-by',
  'blocked-by',
] as const);

export type W5N02ADependencyDirection = (typeof W5_N02_A_DEPENDENCY_DIRECTIONS)[number];

export const W5_N02_A_FUTURE_RESPONSIBILITIES = Object.freeze([
  'W5-N02-b',
  'W5-N02-c',
  'W5-N02-d',
  'W5-N02-e',
  'honesty-baseline',
  'out-of-scope-w5-n03',
  'out-of-scope-w5-n04',
  'out-of-scope-live-trading',
  'out-of-scope-smtp-slice-a',
  'out-of-scope-email-control-plane',
  'out-of-scope-exchange-adapter',
  'out-of-scope-message-templates',
  'out-of-scope-w5-n02-complete',
  'out-of-scope-wave-5-complete',
  'out-of-scope-auth-host-mail-merge',
  'w5-n01-reference',
] as const);

export type W5N02AFutureResponsibility = (typeof W5_N02_A_FUTURE_RESPONSIBILITIES)[number];

export type W5N02AInventoryRow = Readonly<{
  artifactId: string;
  artifact: string;
  kind: W5N02AArtifactKind;
  owner: W5N02AOwner;
  durabilityClass: W5N02ADurabilityClass;
  capabilityCategory: W5N02ACapabilityCategory;
  dependencyDirection?: W5N02ADependencyDirection;
  currentStatus: string;
  honestyRequirement: string;
  futureW5N02Responsibility: W5N02AFutureResponsibility;
  evidencePath: string;
  existsToday: boolean;
  authorizesEmailRealDelivery: boolean;
  authorizesW5N02Complete: boolean;
}>;

/**
 * Frozen inventory of Email SMTP transport surfaces, notification delivery paths,
 * vault/connection substrates, operator-visible artifacts, platform dependencies,
 * ownership boundaries, and honesty rules for Wave 5 slice W5-N02-a.
 */
export const W5_N02_A_EMAIL_NOTIFICATION_INVENTORY: readonly W5N02AInventoryRow[] = Object.freeze([
  // ── Ownership surfaces (required minimum) ────────────────────────────────
  Object.freeze({
    artifactId: 'own-email-smtp-transport',
    artifact: 'Email SMTP transport — Notification Delivery adapter owner (extend only)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Verified existing owner — ReservedInactiveChannelAdapter for email today; W5-N02-b extends to SMTP',
    honestyRequirement:
      'Transport I/O owned by notification-delivery; connection-management is connect product only',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-delivery-domain',
    artifact: 'Notification Delivery — deliver / test / queue / connection domain owner',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Verified existing owner — sole delivery-domain SoT; consume not redesign',
    honestyRequirement: 'No second notification engine; Wave 5 extends adapters only',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-delivery-pipeline',
    artifact: 'Delivery pipeline — deliver() → routing → channel adapter → history/queue',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented sync pipeline — email routes skip with channel-reserved',
    honestyRequirement: 'Pipeline exists; production SMTP round-trip is W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-persistence',
    artifact: 'Notification persistence — DurableNotificationStore (history + queue snapshot)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — W3-O01 history + W3-O02-b queue on existing owner',
    honestyRequirement: 'Persistence ≠ production transport; no new persistence owner',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-secret-vault-smtp',
    artifact: 'Vault — HoldableSecretType.Smtp credential ciphertext owner',
    kind: 'ownership' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — Smtp secret type exists; not consumed by delivery today',
    honestyRequirement: 'Vault remains sole credential owner; adapter retrieve-only at W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-workspace-isolation-notifications',
    artifact: 'Workspace Isolation — notification credentials and state per workspace',
    kind: 'ownership' as const,
    owner: 'workspace-isolation' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Consumed — workspace-bound delivery, prefs, and connections',
    honestyRequirement: 'Cross-workspace SMTP bind or send forbidden',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-security-review.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-user-notification-preferences',
    artifact: 'User notification preferences — routing inputs including email channel enablement',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — type routing, quiet hours, channel enablement (email reserved)',
    honestyRequirement: 'Preferences drive routing only; not transport or vault owner',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/domain/user-notification-preferences.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-message-template-catalog',
    artifact: 'Message template catalog — reusable notification body templates',
    kind: 'ownership' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no template catalog; inline subject/body at deliver() today',
    honestyRequirement: 'Must not invent template SoT in slice a; deferred beyond W5-N02',
    futureW5N02Responsibility: 'out-of-scope-message-templates' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-notification-durable-queue',
    artifact: 'Notification Durable Queue — W3-O02 work items (TD-045)',
    kind: 'ownership' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — queue domain + durable store; sync deliver() still terminal',
    honestyRequirement: 'Queue survival ≠ production Email send; distinct from SMTP I/O',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-auth-host-mail-separate',
    artifact:
      'Auth host mail (S01-e) — password recovery infrastructure owner (NOT Notification Email)',
    kind: 'ownership' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — HostMailPort + SmtpHostMail for recovery; separate from notification',
    honestyRequirement: 'Auth host mail ≠ Notification Email product; must not merge in W5-N02',
    futureW5N02Responsibility: 'out-of-scope-auth-host-mail-merge' as const,
    evidencePath: 'apps/api/src/modules/auth/host-mail.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'own-honest-product-boundaries',
    artifact: 'Honest Product boundaries — Wave 5 Email delivery-only invariants',
    kind: 'ownership' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — frozen in W5-N02 planning scope; inventory slice a catalogues only',
    honestyRequirement:
      'Real delivery ≠ Live Trading; Email ≠ control plane; Auth mail ≠ Notification',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Runtime / transport (reserved-inactive today) ────────────────────────
  Object.freeze({
    artifactId: 'runtime-reserved-inactive-email-adapter',
    artifact: 'ReservedInactiveChannelAdapter — email channel port (no SMTP I/O)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — active=false; send() returns channel-reserved skip',
    honestyRequirement: 'Reserved-inactive must not be labeled production Email delivery',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-delivery-deliver',
    artifact: 'NotificationDeliveryService.deliver() — sync terminal delivery (email skip path)',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus:
      'Implemented — email routes get channel-reserved skip; records history + queue row',
    honestyRequirement: 'deliver() skip ≠ message reached SMTP servers',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-delivery-send-test',
    artifact: 'NotificationDeliveryService.sendTestNotification() — operator test path',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — fixed test body via deliver(); email channel skipped when routed',
    honestyRequirement: 'Test send is not production SMTP round-trip (TD-050 deferred)',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-resolve-delivery-routing-pc06',
    artifact: 'resolve-delivery-routing.ts — PC-06 routing + quiet-hours evaluation',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — type/channel routing SoT; email in routes when enabled in prefs',
    honestyRequirement: 'Routing owner remains PC-06; Wave 5 must not redesign routing',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/routing/resolve-delivery-routing.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-email-channel-reserved-in-boundary',
    artifact: 'NOTIFICATION_DELIVERY_BOUNDARY — emailChannel active port false',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — emailChannel: false in boundary and port active flags',
    honestyRequirement: 'Boundary flag must remain false until W5-N02-b activates transport',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-boundary.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-notification-channel-catalog-email',
    artifact: 'NOTIFICATION_CHANNEL_CATALOG — email reserved-inactive descriptor',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — email status reserved-inactive; only telegram active',
    honestyRequirement: 'Catalog reserved status must not imply SMTP transport exists',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/notification-channel.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'runtime-auth-smtp-host-mail',
    artifact: 'SmtpHostMail — Auth recovery mail adapter (nodemailer; NOT notification channel)',
    kind: 'runtime' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — sendPasswordReset only; host env credentials; not vault-backed notification',
    honestyRequirement: 'Auth SMTP adapter must not be reused as Notification Email transport',
    futureW5N02Responsibility: 'out-of-scope-auth-host-mail-merge' as const,
    evidencePath: 'apps/api/src/modules/auth/host-mail.smtp.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Commands / REST / catalog ──────────────────────────────────────────
  Object.freeze({
    artifactId: 'rest-notification-product-pc06',
    artifact: 'PC-06 REST — notification settings, routing, delivery history',
    kind: 'command' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — product adapter; does not deliver or connect Email SMTP',
    honestyRequirement: 'Product queries only; transport remains notification-delivery owner',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-product/notification-product.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'rest-connections-smtp-catalog',
    artifact: 'Connection catalog SMTP provider entry',
    kind: 'state' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — NOTIFICATION type; host/port/username/password/sender fields',
    honestyRequirement: 'Catalog entry exists; not consumed by delivery adapter today',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/connections/connection-catalog.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'rest-connection-vault-smtp-mapping',
    artifact: 'Connection vault mapping SMTP → HoldableSecretType.Smtp',
    kind: 'runtime' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — write-only vault store; not consumed by delivery adapter',
    honestyRequirement: 'Vault path exists but delivery does not retrieve SMTP credentials today',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/connections/connection-vault.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'rest-vault-smtp-field-validation',
    artifact: 'Vault SMTP field validation — host/port/username/password/sender contracts',
    kind: 'runtime' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — validateHoldableSecretFields for Smtp; no vendor I/O',
    honestyRequirement: 'Validation ≠ SMTP handshake; adapter performs transport at W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/secret-validation.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Producing paths ──────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'produce-report-notification-consumer',
    artifact: 'ReportNotificationConsumerService — requestAndDeliver / deliverCompletedRun',
    kind: 'runtime' as const,
    owner: 'product-flow' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Implemented — sync call into notification-delivery; email skipped when routed',
    honestyRequirement: 'Producer is not Live Trading; Email send remains reserved-inactive',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/product-flow/report-notification-consumer.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Persistence candidates ───────────────────────────────────────────────
  Object.freeze({
    artifactId: 'persist-durable-notification-store',
    artifact: 'DurableNotificationStore — prefs + deliveries + queue (no email anchor today)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — analytical + queue snapshot; survives restart',
    honestyRequirement: 'Durable state ≠ production SMTP delivery truth',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/durable-notification-store.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-delivery-queue-w3-o02',
    artifact: 'NotificationDeliveryQueueItem — W3-O02 durable queue work items',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — pending|in-flight|retryable states; not SMTP execution',
    honestyRequirement: 'Queue durability ≠ Email message delivery Complete',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-email-notification-anchor',
    artifact:
      'WorkspaceEmailNotificationAnchor — canonical Email notification delivery anchors (W5-N02-b)',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Missing — no email anchor persistence; W5-N01-b Telegram anchor is reference pattern',
    honestyRequirement: 'Anchor persistence ≠ Email delivery Complete; W5-N02-b implements',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-validation-plan.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-vault-smtp-ciphertext',
    artifact: 'Vault ciphertext for HoldableSecretType.Smtp credentials',
    kind: 'persistence-candidate' as const,
    owner: 'secret-vault' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — secret type + validation; delivery path does not retrieve',
    honestyRequirement: 'Vault stores credentials; adapter must retrieve at W5-N02-b only',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/secret-vault/holdable-secret-type.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'persist-delivery-result-metadata',
    artifact: 'DeliveryResult — immutable delivery metadata with channel attempts',
    kind: 'persistence-candidate' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Exists — deliveryId, attempts[], outcome; email attempts show channel-reserved',
    honestyRequirement: 'Delivery metadata records skip truth; not vendor delivery proof for email',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Notification / retry metadata ────────────────────────────────────────
  Object.freeze({
    artifactId: 'meta-channel-delivery-attempt',
    artifact: 'ChannelDeliveryAttempt — per-channel outcome + skipReason metadata',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — email attempts record channel-reserved skipReason today',
    honestyRequirement: 'Skip metadata must not be relabeled as delivered for email',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'meta-channel-delivery-view-email-projection',
    artifact: 'ChannelDeliveryView — reservedChannels projection including email skip',
    kind: 'projection' as const,
    owner: 'product-flow' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — reservedChannels[] with skipReason for email when attempted',
    honestyRequirement: 'Projection reflects reserved-inactive truth; not SMTP delivery proof',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/product-flow/channel-delivery.view.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'retry-queue-retryable-status',
    artifact: 'NotificationDeliveryQueueItem retryable status — queue retry metadata',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus:
      'Implemented — retryable terminal status on failed delivery; not retry execution',
    honestyRequirement: 'Retry metadata ≠ SMTP retry execution; W3-O02-c hydrate only',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery-queue.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'retry-w3-o02-no-retry-execution',
    artifact: 'W3-O02 queue — persistence and hydrate without retry execution',
    kind: 'operational' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — queue survives restart; deliver() does not auto-retry SMTP',
    honestyRequirement: 'Retry execution deferred; email transport retry is post W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-d' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/README.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Operator-visible ─────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'ui-notification-channels-view-email',
    artifact: 'NotificationChannelsView — Email listed as reserved channel',
    kind: 'operator-visible' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Routed — Email/Slack/Discord/Teams/Push stay reserved; Telegram active',
    honestyRequirement: 'UI must not claim Email Connected without SMTP round-trip after W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/web/src/notifications/NotificationChannelsView.tsx',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'ui-notification-channel-detail-email',
    artifact: 'NotificationChannelDetailView — reserved channel detail (no SMTP form today)',
    kind: 'operator-visible' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Routed — SMTP/webhooks not collected; reserved-inactive copy',
    honestyRequirement:
      'Detail view must not collect SMTP credentials until W5-N02-b product slice',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/web/src/notifications/NotificationChannelDetailView.tsx',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'ui-connections-smtp-catalog',
    artifact: 'Connections UI — SMTP provider in connection catalog listing',
    kind: 'operator-visible' as const,
    owner: 'connection-management' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Routed — SMTP catalog entry visible; vault write path exists',
    honestyRequirement:
      'Connection form ≠ notification transport active; delivery does not consume',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/web/src/connections/ConnectionsPage.spec.tsx',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'ui-notifications-email-label',
    artifact: 'notifications.ts — email channel label mapping',
    kind: 'operator-visible' as const,
    owner: 'command-center' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'implemented-today' as const,
    currentStatus: 'Implemented — human label Email for reserved channel id',
    honestyRequirement: 'Label must not imply active transport',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/web/src/notifications/notifications.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Platform Readiness / W5-N01 reference dependencies ───────────────────
  Object.freeze({
    artifactId: 'dep-platform-readiness-notification-queue',
    artifact: 'Platform Readiness notificationQueue projection — aggregate continuity',
    kind: 'dependency' as const,
    owner: 'platform-readiness' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'observed-by' as const,
    currentStatus: 'Implemented — W3-O02-d derived view on operational readiness',
    honestyRequirement: 'Queue continuity ≠ Email transport Complete',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/operational-continuity/operational-readiness.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authentication',
    artifact: 'Authentication — signed-in operator for connect/test/delivery surfaces',
    kind: 'dependency' as const,
    owner: 'authentication' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — fail closed when missing; Auth host mail separate',
    honestyRequirement: 'Reuse Wave 1 Authentication; no parallel login; no host mail merge',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-security-review.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-authorization',
    artifact: 'Authorization — PermissionClass.Projection for notification surfaces',
    kind: 'dependency' as const,
    owner: 'authorization' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — connect/test requires permitted role',
    honestyRequirement: 'Unauthorized deny; no new IAM',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-security-review.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-consumes-security-audit',
    artifact: 'Security Audit — connect/test/disconnect attribution events',
    kind: 'dependency' as const,
    owner: 'security-audit' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'consumes' as const,
    currentStatus: 'Consumed — lifecycle audit expected at Close',
    honestyRequirement: 'Emit required outcomes; do not own audit store',
    futureW5N02Responsibility: 'W5-N02-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-security-review.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-w5-n01-telegram-foundation-reference',
    artifact: 'W5-N01 Telegram foundation — anchor/recovery/continuity pattern reference',
    kind: 'dependency' as const,
    owner: 'w5-n01-reference' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — W5-N01 Closed; Email follows same owner patterns',
    honestyRequirement: 'Consume N01 patterns; do not redesign Telegram artifacts',
    futureW5N02Responsibility: 'w5-n01-reference' as const,
    evidencePath: 'apps/api/src/platform-conformance/w5-n01-a-telegram-notification-inventory.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-exchange-adapter-untouched',
    artifact: 'Exchange Adapter / Wave 4 Exchange Connectivity — not consumed; unchanged',
    kind: 'dependency' as const,
    owner: 'exchange-adapter' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    dependencyDirection: 'depends-on' as const,
    currentStatus: 'Reference only — Wave 5 must not modify exchange I/O',
    honestyRequirement: 'Email notifications ≠ exchange connectivity; adapter untouched',
    futureW5N02Responsibility: 'out-of-scope-exchange-adapter' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'dep-blocked-by-vault-not-in-delivery',
    artifact: 'Vault SMTP credentials not consumed by delivery adapter — transport blocker',
    kind: 'dependency' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    dependencyDirection: 'blocked-by' as const,
    currentStatus: 'Active gap — no vault retrieve in notification-delivery module',
    honestyRequirement: 'W5-N02-b must wire vault retrieve inside adapter boundary only',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Parallel disconnected paths ──────────────────────────────────────────
  Object.freeze({
    artifactId: 'gap-auth-host-mail-vs-notification-smtp',
    artifact: 'Parallel paths — Auth host mail (S01-e) vs Notification Email (V3-N02)',
    kind: 'ephemeral-artifact' as const,
    owner: 'authentication' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus:
      'Disconnected — password-recovery mail exists; notification SMTP product does not',
    honestyRequirement:
      'Must converge only under Notification Delivery adapter at W5-N02-b; never merge',
    futureW5N02Responsibility: 'out-of-scope-auth-host-mail-merge' as const,
    evidencePath: 'apps/api/src/modules/auth/host-mail.smtp.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Integrity metadata ───────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'integrity-delivery-result-immutable',
    artifact: 'DeliveryResult deep-freeze — immutable notification delivery record',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — createDeliveryResult deep-freezes attempts and outcome',
    honestyRequirement: 'Immutable record preserves honest skip/deliver truth for email',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/domain/delivery.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'integrity-queue-item-correlation',
    artifact: 'Queue item deliveryId correlation — integrity link queue ↔ DeliveryResult',
    kind: 'state' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'SURVIVE' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Implemented — queueItem.deliveryId set on deliver() completion',
    honestyRequirement: 'Correlation supports audit; not SMTP delivery proof',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.service.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Missing / not-implemented (catalogued honestly) ──────────────────────
  Object.freeze({
    artifactId: 'missing-production-smtp-transport',
    artifact: 'Production SMTP transport — customer SMTP server round-trip',
    kind: 'command' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — TD-050 deferred; ReservedInactiveChannelAdapter is certified path',
    honestyRequirement: 'Must not fake vendor round-trip; W5-N02-b implements real I/O',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-email-connect-product',
    artifact: 'Email connect / test / disconnect product surface (PC-07 email channel)',
    kind: 'command' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no email-specific connect REST; reserved-inactive only',
    honestyRequirement: 'Connect product follows N01 Telegram pattern at W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-message-templates-catalog',
    artifact: 'Message templates catalog — reusable notification bodies for email',
    kind: 'state' as const,
    owner: 'notification-product' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — inline subject/body at deliver() only',
    honestyRequirement: 'No template SoT invented in slice a',
    futureW5N02Responsibility: 'out-of-scope-message-templates' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-vault-in-delivery-path',
    artifact: 'Vault retrieve in notification-delivery delivery path for SMTP',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — notification-delivery module has no secret-vault imports',
    honestyRequirement: 'Credentials retrieved adapter-side only at W5-N02-b; never echoed',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'apps/api/src/modules/notification-delivery/notification-delivery.module.ts',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'missing-real-smtp-round-trip',
    artifact: 'Real SMTP round-trip — verifiable test email to recipient inbox',
    kind: 'runtime' as const,
    owner: 'notification-delivery' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'not-implemented' as const,
    currentStatus: 'Missing — no SMTP handshake or sendMail in notification-delivery',
    honestyRequirement: 'Connected label requires vendor round-trip evidence after W5-N02-b',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-validation-plan.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Operational / planning ───────────────────────────────────────────────
  Object.freeze({
    artifactId: 'op-w5-n02-planning-open',
    artifact: 'W5-N02 Planning Package — OPEN; slices named not opened for implementation',
    kind: 'operational' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Planning OPEN — slice a inventory only; not APPROVED for SMTP implementation',
    honestyRequirement: 'Planning ≠ production Email delivery Complete',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-planning-summary.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'op-td050-reserved-channels-debt',
    artifact: 'TD-050 — Reserved notification channels (SMTP / Slack / Discord / Teams / Push)',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — email reserved-inactive until Wave 5 W5-N02-b',
    honestyRequirement: 'Debt label ≠ closed; must not claim SMTP from inventory alone',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'op-td045-notification-queue-debt',
    artifact: 'TD-045 — Notification durable delivery queue (substrate reference)',
    kind: 'operational' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — queue persists work items; not SMTP retry execution',
    honestyRequirement: 'Queue debt ≠ Email transport Complete',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/technical-debt.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Honesty boundaries ───────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'honesty-real-delivery-not-live-trading',
    artifact: 'Real Email delivery ≠ Live Trading; delivery ≠ order submission',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — frozen in W5-N02 scope',
    honestyRequirement: 'Alerts outside process ≠ live capital trading enablement',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-email-delivery-only-not-control-plane',
    artifact: 'Email delivery-only — cannot start/stop/approve trades',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — no trading commands via Email transport',
    honestyRequirement: 'Notification channel only; control plane forbidden',
    futureW5N02Responsibility: 'out-of-scope-email-control-plane' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-reserved-inactive-not-production-smtp',
    artifact: 'ReservedInactiveChannelAdapter ≠ production SMTP delivery',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — channel-reserved skip is not SMTP send',
    honestyRequirement: 'deliver() skip must not imply message reached SMTP server',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath:
      'apps/api/src/modules/notification-delivery/adapters/reserved-inactive-channel.adapter.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-connected-requires-smtp-round-trip',
    artifact: 'Connected / Verified labels require real SMTP round-trip evidence',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — reserved-inactive violates today; W5-N02-b fixes',
    honestyRequirement: 'No fake Connected from reserved-inactive adapter alone',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-auth-host-mail-not-notification-email',
    artifact: 'Auth host mail (S01-e) ≠ Notification Email product',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — SmtpHostMail is recovery infrastructure only',
    honestyRequirement: 'Password reset mail must not be conflated with notification alerts',
    futureW5N02Responsibility: 'out-of-scope-auth-host-mail-merge' as const,
    evidencePath: 'apps/api/src/modules/auth/host-mail.smtp.ts',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'honesty-w5-n02-not-wave5-complete',
    artifact: 'W5-N02 ≠ Wave 5 COMPLETE; N02 ≠ Slack/Push Complete',
    kind: 'honesty-boundary' as const,
    owner: 'wave-5-documentation' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'infrastructure-only' as const,
    currentStatus: 'Binding — N03–N04 sequenced separately',
    honestyRequirement: 'Email-only package; no wave-level Complete claims',
    futureW5N02Responsibility: 'honesty-baseline' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-overview.md',
    existsToday: true,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),

  // ── Explicit OUT ─────────────────────────────────────────────────────────
  Object.freeze({
    artifactId: 'out-smtp-implementation-slice-a',
    artifact: 'Production SMTP implementation in W5-N02-a',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Forbidden — inventory only; W5-N02-b implements SMTP',
    honestyRequirement: 'Slice a catalogues surfaces; does not implement transport I/O',
    futureW5N02Responsibility: 'out-of-scope-smtp-slice-a' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-implementation-package.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n02-b-durable-anchors',
    artifact: 'W5-N02-b — Durable email notification anchors',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — named slice; not opened from slice a',
    honestyRequirement: 'Anchor persistence is post-inventory work',
    futureW5N02Responsibility: 'W5-N02-b' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-planning-summary.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n02-c-restart-recovery',
    artifact: 'W5-N02-c — Email notification restart recovery',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — restart hydrate post W5-N02-b',
    honestyRequirement: 'Recovery requires durable anchors first',
    futureW5N02Responsibility: 'W5-N02-c' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-planning-summary.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n02-d-operational-continuity',
    artifact: 'W5-N02-d — Email operational continuity foundation',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — transport continuity post SMTP implementation',
    honestyRequirement: 'Continuity slice follows durable transport implementation',
    futureW5N02Responsibility: 'W5-N02-d' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-planning-summary.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n02-e-close-evidence',
    artifact: 'W5-N02-e — Security verification + package Close evidence',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'planned' as const,
    currentStatus: 'Deferred — Close evidence assembly post implementation slices',
    honestyRequirement: 'Close requires FIV + PO act; not authorized from slice a',
    futureW5N02Responsibility: 'W5-N02-e' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-planning-summary.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n03-slack-discord-teams',
    artifact: 'W5-N03 / V3-N03 — Slack / Discord / Teams production transports',
    kind: 'explicit-out' as const,
    owner: 'w5-n03-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Out of W5-N02 — sequenced after N02 Close',
    honestyRequirement: 'Webhook transports deferred; Email first in N02 package',
    futureW5N02Responsibility: 'out-of-scope-w5-n03' as const,
    evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-w5-n04-push',
    artifact: 'W5-N04 / V3-N04 — Push notification production transport',
    kind: 'explicit-out' as const,
    owner: 'w5-n04-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Out of W5-N02 — final Wave 5 transport package',
    honestyRequirement: 'Push deferred beyond Email + webhooks',
    futureW5N02Responsibility: 'out-of-scope-w5-n04' as const,
    evidencePath: 'docs/project/version-3/wave-5/wave-5-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-live-trading-wave6',
    artifact: 'Live Trading / live order submission (Wave 6)',
    kind: 'explicit-out' as const,
    owner: 'live-trading-deferred' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Out of W5-N02 paper notification scope',
    honestyRequirement: 'Email alerts ≠ live capital orders',
    futureW5N02Responsibility: 'out-of-scope-live-trading' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-email-control-plane',
    artifact: 'Email as trading control plane — start/stop/approve via mail',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — architecture invariant for all Wave 5',
    honestyRequirement: 'Delivery-only channel; no command bus via Email',
    futureW5N02Responsibility: 'out-of-scope-email-control-plane' as const,
    evidencePath: 'docs/project/version-3/wave-5/w5-n02-product-scope.md',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
  Object.freeze({
    artifactId: 'out-auth-host-mail-merge',
    artifact: 'Merge Auth host mail with Notification Email product',
    kind: 'explicit-out' as const,
    owner: 'release-governance' as const,
    durabilityClass: 'EPHEMERAL' as const,
    capabilityCategory: 'future-roadmap' as const,
    currentStatus: 'Forbidden — S01-e host mail remains separate infrastructure',
    honestyRequirement: 'Notification SMTP uses vault-backed customer credentials only',
    futureW5N02Responsibility: 'out-of-scope-auth-host-mail-merge' as const,
    evidencePath: 'apps/api/src/modules/auth/host-mail.ts',
    existsToday: false,
    authorizesEmailRealDelivery: false,
    authorizesW5N02Complete: false,
  }),
]);

export const W5_N02_A_BINDING_FINDINGS = Object.freeze({
  emailRealDeliveryAuthorized: false,
  emailNotificationsFunctionAfterSliceA: false,
  customerVisibleFeatureFromSliceA: false,
  reservedInactiveEmailAdapterExists: true,
  vaultSmtpNotConsumedByDelivery: true,
  productionSmtpMissing: true,
  authHostMailSeparate: true,
  ownershipBoundariesVerified: true,
  ownershipBoundariesChanged: false,
  architecturalDeviations: false,
} as const);

export const W5_N02_A_EXPLICIT_OUT = Object.freeze([
  'smtp-implementation',
  'outbound-production-notifications',
  'runtime-delivery-to-customer-smtp',
  'real-smtp-round-trip',
  'message-template-catalog',
  'vault-in-delivery-path',
  'email-control-plane',
  'auth-host-mail-merge',
  'live-trading-enablement',
  'w5-n02-b',
  'w5-n02-c',
  'w5-n02-d',
  'w5-n02-e',
  'w5-n03',
  'w5-n04',
  'w5-n02-complete',
  'wave-5-complete',
  'master-plan-revision',
  'version-2-redesign',
  'ownership-change',
  'new-persistence-owner',
  'new-bounded-context',
  'exchange-adapter-modification',
] as const);

export const W5_N02_A_ARCHITECTURE_CLAIMS = Object.freeze({
  newPersistenceOwner: false,
  newBoundedContext: false,
  newSourceOfTruth: false,
  duplicateNotificationSubsystem: false,
  duplicateRoutingEngine: false,
  emailControlPlane: false,
  ownershipBoundariesChanged: false,
  masterPlanModified: false,
  version2Redesigned: false,
  wave1Modified: false,
  wave2Modified: false,
  wave3Modified: false,
  wave4Modified: false,
  exchangeAdapterUntouched: true,
  w5N02CompleteClaimed: false,
  emailRealDeliveryClaimed: false,
  wave5CompleteClaimed: false,
  liveTradingClaimed: false,
  customerVisibleFeature: false,
  authHostMailMerged: false,
} as const);

export const W5_N02_A_HONEST_PRODUCT_BASELINE = Object.freeze({
  implementedCapabilities: Object.freeze([
    'None — no customer-visible production Email notification functionality',
  ] as const),
  infrastructureCapabilities: Object.freeze([
    'ReservedInactiveChannelAdapter — email channel reserved-inactive (TD-050 deferred)',
    'NotificationDeliveryService deliver() / sendTestNotification() sync pipeline (email skip path)',
    'PC-06 resolve-delivery-routing — type/channel routing + quiet hours',
    'PC-06 notification-product — settings, routing views, delivery history',
    'Connection catalog SMTP + connection-vault mapping → HoldableSecretType.Smtp',
    'HoldableSecretType.Smtp + secret-validation field contracts',
    'User notification preferences — routing inputs including email channel enablement',
    'DurableNotificationStore — W3-O01 history + W3-O02 queue snapshot',
    'DeliveryResult + ChannelDeliveryAttempt metadata — honest skip/deliver records',
    'Auth host mail (S01-e) — HostMailPort + SmtpHostMail for password recovery (NOT notification)',
    'Platform Readiness notificationQueue continuity projection (derived)',
    'ReportNotificationConsumer — product-flow producer into delivery',
    'W5-N01 Telegram foundation — anchor/recovery pattern reference',
    'Exchange Adapter / Wave 4 — reference only; untouched by Wave 5',
  ] as const),
  plannedCapabilities: Object.freeze([
    'W5-N02-b — Production SMTP connect / test / disconnect via vault-backed adapter',
  ] as const),
  notYetImplementedCapabilities: Object.freeze([
    'Customer SMTP server round-trip (TD-050)',
    'Durable email notification anchors (W5-N02-b)',
    'Vault SMTP retrieve in notification-delivery delivery path',
    'Email connect / test product surface',
    'Message templates catalog',
    'Honest Connected / Verified labels from SMTP round-trip',
    'W5-N02 Complete',
  ] as const),
  futureRoadmapCapabilities: Object.freeze([
    'W5-N02-c — Email notification restart recovery',
    'W5-N02-d — Email operational continuity foundation',
    'W5-N02-e — Security verification + package Close evidence',
    'W5-N03 — Slack / Discord / Teams production transports (V3-N03 · CM-13–15)',
    'W5-N04 — Push notification production transport (V3-N04 · CM-16)',
    'Wave 6 — Live Trading (LT-02)',
  ] as const),
} as const);

export const W5_N02_A_TECHNICAL_DEBT_DELTA = Object.freeze({
  resolved: Object.freeze(['Email Notification Inventory Foundation'] as const),
  introduced: Object.freeze([] as const),
  deferred: Object.freeze([
    'W5-N02-b — Durable email notification anchors + production SMTP transport',
    'W5-N02-c — Email notification restart recovery',
    'W5-N02-d — Email operational continuity foundation',
    'W5-N02-e — Security verification + package Close evidence',
  ] as const),
} as const);

export function artifactIds(): readonly string[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.map((row) => row.artifactId);
}

export function rowsByKind(kind: W5N02AArtifactKind): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.kind === kind);
}

export function rowsSurvive(): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.durabilityClass === 'SURVIVE');
}

export function rowsEphemeral(): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.durabilityClass === 'EPHEMERAL');
}

export function rowsEmailNotificationSurvive(): readonly W5N02AInventoryRow[] {
  return rowsSurvive().filter((row) =>
    (W5_N02_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsEmailNotificationEphemeral(): readonly W5N02AInventoryRow[] {
  return rowsEphemeral().filter((row) =>
    (W5_N02_A_SUBSTRATE_OWNERS as readonly string[]).includes(row.owner),
  );
}

export function rowsHonestyBoundaries(): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'honesty-boundary');
}

export function rowsExplicitOut(): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.kind === 'explicit-out');
}

export function rowsByCapabilityCategory(
  category: W5N02ACapabilityCategory,
): readonly W5N02AInventoryRow[] {
  return W5_N02_A_EMAIL_NOTIFICATION_INVENTORY.filter((row) => row.capabilityCategory === category);
}
